### ISSUE TITLE
Package is scheduled for an update check. Still have to wait for 246 other packages to complete.

### ISSUE THREAD

**Issue by CyberShadow** [dlang/dub#1000]
Hi,

I've been experimenting with moving some things over to Dub, and have started using it for CI on some projects.

Today, I went to deploy a change in a project, together with one in a dependency (ae). I made a new tag in the dependency, pushed the tag and master branch, then updated the main project's `dub.sdl` to use the new tag and pushed that as well.

However, CI is failing for the main project, with the message:
```
Could not find a valid dependency tree configuration: 
```

I understand this to be because code.dlang.org doesn't know about the tag yet?

I went to my account on code.dlang.org to see if there was a way to get it updated, but all I saw was the titular message: "Package is scheduled for an update check. Still have to wait for 246 other packages to complete."

Am I missing something, or is Dub by itself insufficient for immediately deploying changes of a project and its dependencies?

**Comment by CyberShadow** [comment]
This turned out to be caused by an outdated Dub version, installed from Ubuntu's repositories instead of the DMD package. Closing.

**Comment by s-ludwig** [comment]
Although regarding immediate deployment, the registry currently polls GitHub for changes instead of using push notifications. We sill need to implement registering as an OAuth app to be able to do that (https://github.com/dlang/dub-registry/issues/10).
