### ISSUE TITLE
check (and assert) on empty flags

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1003]
had a cryptic `ld: file not found:` that was due to a dub.json auto generated that was populating an empty entry inside lflags:

```
"lflags":[
"",
],
```

would be nice to assert on empty flags to avoid these errors

**Comment by Samathy** [comment]
I'm going to start looking into this.

Looks like it can be reproduced still with dub `1.14.0`.
This occurs with `dub.sdl` as well as a JSON dubfile, simply add `lflags ""` and one gets `ld: cannot file : No such file or directory` as described above.
