### ISSUE TITLE
Any plans to support generation of Eclipse/DDT project/solution files?

### ISSUE THREAD

**Issue by ilya-stromberg** [dlang/dub#102]
Have you got any plans to support generation of Eclipse/DDT project/solution files?
I know that last public release was 2012-05-17, but DDT is still alive, last commit was today:
http://code.google.com/p/ddt/source/list

**Comment by dhasenan** [comment]
DDT is dead, and currently maintained IDEs / editor plugins support dub's package format directly. Close?
