### ISSUE TITLE
'dub fetch <pkg> --local' documented but not supported

### ISSUE THREAD

**Issue by jondegenhardt** [dlang/dub#1022]
The fetch '--local' option is documented but not supported. Details:
```
$ dub --version
DUB version 1.1.1, built on Nov 30 2016
```

```
$ dub fetch -h
USAGE: dub fetch <name> [<options...>]
...
Complete applications can be retrieved and run easily by e.g.
$ dub fetch vibelog --local
$ cd vibelog
$ dub

This will grab all needed dependencies and compile and run the application.
...
```

```
$ dub fetch vibelog --local
Unknown command line flags: --local
Type "dub fetch -h" to get a list of all supported flags.
```

The 'fetch --local' switch is also listed in the on-line documentation (text similar to the help text), here: https://code.dlang.org/docs/commandline#fetch

**Comment by Manuzor** [comment]
Would love to see at least some kind of statement for this as it is inexplicable to me why this feature isn't there if it's documented. Was it there before? Has --local been replaced by something? Any statement, or a link to some forum discussions, would be appreciated!

**Comment by s-ludwig** [comment]
This is actually a left over. The syntax was changed to `--cache=local` a while ago. I'll update the documentation accordingly.

**Comment by jondegenhardt** [comment]
Thank you! This will make a real difference for the tsv-utilities apps I open-sourced. They are executables, not libraries, having them get placed in a local directory makes much more sense than having them placed in the repository structure. Clearly it been available for a long time, but I had been unable to figure out how to achieve it.

**Comment by kunftep** [comment]
stumbled upon this because it is still in 'getting started':
[https://code.dlang.org/getting_started](https://code.dlang.org/getting_started)

	dub fetch --local <package name>

as well as the link mentioned above:
[https://code.dlang.org/docs/commandline#fetch](https://code.dlang.org/docs/commandline#fetch)

	$ dub fetch vibelog --local

**Comment by s-ludwig** [comment]
Fixed the getting stared page: https://github.com/dlang/dub-registry/commit/b24dedb562295355fda91bc9ae7e08c481a32300

The command line documentation will get updated automatically later when the site gets rebuilt with a new version of DUB.
