### ISSUE TITLE
Single-file packages

### ISSUE THREAD

**Issue by carlor** [dlang/dub#103]
(Note: I'd post it to the newsgroup, but [issue #8](https://github.com/rejectedsoftware/vibenews/issues/8) prevents me)

### Problem
When dealing with large libraries including multiple files, sub-packages, and so on, dub is well-designed and easy to use. There is one target audience, however, where the user interface could be simpler: packages with only a single file.

The current choice offered is either to make one repository for every single-file package (e.g. my own `embd`), or to lump together several often unrelated packages into one repo (e.g. the great `arsd`). The former option is clunky, and the latter requires users to download and compile several modules they won't need. Another option is needed.

### Solution
An SFP is a folder named `example` with a single file inside named `example.d` (not including `.git`, etc). Somewhere in the file will be a comment like so:

```
/+
dub:
 {
     ...what would be in package.json...
 }
+/
```

This file could be automatically generated by:
```
$ dub init --sfp example
    create folder example
    create file example/example.d
```

### Questions
Here's some additional ideas:

  * Requiring that the packages be `sfp/[name]` in the repository?
  * Adding support for [gist](https://gist.github.com/) and [dpaste](http://dpaste.dzfl.pl/)?
  * An option to generate a symlink in the parent folder: `example.d -> example/example.d`

School's about to start, so I'll be slow, but I'm willing to work on it.

Thoughts?
NMS

**Comment by Abscissa** [comment]
> or to lump together several often unrelated packages into one repo (e.g. the great arsd)[...]requires users to download and compile several modules they won't need.

I know I keep harping on it, but this option would *not* be a problem if dub packages had the ability to tell dub "Don't compile any of my files that aren't actually imported, rdmd-style". For MANY packages, the extra build time involved would be trivial. Larger packages that have longer compile times would NOT be under any obligation to to actually use this option and could freely stick with the current "all files" behavior.
