### ISSUE TITLE
How to make dub NOT to pass -Werror flag to gdc?

### ISSUE THREAD

**Issue by albert-jn** [dlang/dub#1030]
I am trying to `dub build` a project with gdc, but getting an error

`error: pragma(lib) not implemented [-Werror]`

Is it possible to make dub NOT to pass -Werror flag to gdc?

**Comment by s-ludwig** [comment]
Putting `buildRequirements "allowWarnings"` or `"silenceWarnings"` into dub.sdl should do that (`"buildRequirements": ["allowWarnings"]` for dub.json).

Ideally, the library that emits that `pragma(lib)` should also be fixed to wrap that in `version (DigitalMars) { ... }`.

**Comment by albert-jn** [comment]
Thanks!
