### ISSUE TITLE
Root package X reference Y cannot be satisfied: need to show why

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1037]
When you get `Root package X reference Y cannot be satisfied`, I don't see anything in the logs (--vverbose) showing what caused this.

In my case it should show:
```
"gtk-d ~>3.4" violates "gtk-d:gtkd": "~>3.3.0" in gtk-d (and maybe show dependency chain)
```

```
"dependencies": {
"gtk-d" : "~>3.4",
"ggplotd": ">=1.1.2",
},
```

**Comment by burner** [comment]
the same problem as in https://github.com/dlang/dub/issues/1001

The problem I found is that
package A depends on package C of version 1.0.0 and
package B depends on package C of version 1.0.1

The question is what version of package C to use?

**Comment by SingingBush** [comment]
in this scenario could dub inform the user of the problem and let the user decide by putting package C as a dependency in the users project and using that version. 

As a developer making use of package A and package B, I have decided that I want to specifically use version 1.0.3 of package C and am fully aware the it's down to me to test and make sure that packages A & B are ok with that.

**Comment by timotheecour** [comment]
Can you try with https://github.com/dlang/dub/pull/1038 ? this is meant as a simple hotfix for cases like that
