### ISSUE TITLE
dub fetch should consider git submodules 

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#1044]
If a package has git submodules, they are usually required to build the project. 

For example for the Dlang Tour all translations are submodules, see e.g. [this issue](https://github.com/stonemaster/dlang-tour/issues/482).

IIRC `dub` just uses the GitHub archive tool to download a depedency, but I heard (e.g. #632, #104) that there are plans to use e.g. [libgit2](https://github.com/s-ludwig/dlibgit), s.t. a proper, recursive git clone can be done.

I couldn't find any specific issue for this, but I think it belongs to "native git support" milestone.

**Comment by Member1221** [comment]
Idea: Could dub itself check for .gitmodules in dependencies so that it could fetch the submodules before building everything?

Would be **_really_** useful.

**Comment by Geod24** [comment]
I made a (hopefully complete enough) proposal for submodules support at #1840 .
While that proposal is much bigger than what is described here, I think having half-supported submodules support does not make much sense, so I propose to move the discussion there.
Feel free to re-open and argue if you think this should be a feature / issue of its own :)
