### ISSUE TITLE
Let interactive init be able to add dependencies to sub packages

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#1048]
Currently the name of the entered dependencies are treated as base package names, resulting in a bogus "package not found" error. Instead, the name should be split into base name and sub package name.

**Comment by cup** [comment]
https://github.com/vibe-d/vibe.d/issues/2282

**Comment by cup** [comment]
https://github.com/adamdruppe/arsd/issues/194

**Comment by andre2007** [comment]
Maybe fixed by https://github.com/dlang/dub/pull/1756, have to check.

**Comment by andre2007** [comment]
Is working fine now.
