### ISSUE TITLE
Can't add generic files to ide solutions

### ISSUE THREAD

**Issue by Flamaros** [dlang/dub#1053]
Hi,

It seems that it is not possible to add some files to ide solutions that will not be compiled.
I want to add my shader files,... to a visuald solution.

I took a look and it seems that it is partially possible, the dub.sdl file is added with a special flag to avoid his compilation.

I would create a pull request with "genericFiles" and "genericPaths" sdl commands.
I think that I will able to do it for sdl and json parser and visuald generator + the documentation update.

Will it be ok?

**Comment by veelo** [comment]
I'd like to see this functionality also.

**Comment by s-ludwig** [comment]
It sounds like the VS generator should add `extraDependencyFiles` to the solution as data files.

**Comment by andre2007** [comment]
I am not 100% sure, as extraDependenciesFiles  serves following purpose:

A list of globs matching files to be checked for rebuilding the dub project.

**Comment by rikkimax** [comment]
> I am not 100% sure, as extraDependenciesFiles serves following purpose:
> 
> A list of globs matching files to be checked for rebuilding the dub project.

Shaders can be pre-compiled. Both OpenGL and Direct3d (which requires it) use it. So it is a reasonable solution.

But having this supported on top would be preferable I think.

**Comment by veelo** [comment]
Background for my use case: We have some files that need to be deployed as-is. We do that with "copyFiles", but those files do not appear in the VS solution explorer. Maybe the "genericFiles" and "genericPaths" proposed by the OP can just be the existing "copyFiles", except it would be nice to see those files in the solution explorer, for example in corresponding `<Folder>` entries.

**Comment by s-ludwig** [comment]
The "genericFiles" functionality just seems like a strange leaky abstraction as part of the package. I'd go for either collecting all files with special roles (as mentioned, at least `extraDependencyFiles` and `copyFiles`), or just adding *all* files within the package directory (leaving out any possible sub package folders).

**Comment by veelo** [comment]
> ... adding _all_ files within the package directory (leaving out any possible sub package folders).

That would have the advantage that other useful files also appear in the project, like `readme`s and build scripts. But how to exclude generated files, temporary copies and user scribbles? Can't reliably ask RCS either because the user may do `dub generate` before staging all relevant files.

So option 1 is probably best:
> ... collecting all files with special roles (as mentioned, at least `extraDependencyFiles` and `copyFiles`) ...
