### ISSUE TITLE
Suggestion: Configuration-specific "sourceFiles" override package-wide "excludedSourceFiles"

### ISSUE THREAD

**Issue by dymk** [dlang/dub#107]
So you can have a `package.json` like this: 

``` json
{
    "name": "server-client-thing",

    "excludedSourceFiles": [
        "src/server.d", 
        "src/gui-client.d", 
        "src/cli-client.d"
    ],

    "configurations": [
        {
            "name": "cli-client",
            "targetName": "cli-client",
            "targetType": "executable",
            "sourceFiles": ["src/cli-client.d"]
        },      
        {
            "name": "gui-client",
            "targetName": "gui-client",
            "targetType": "executable",
            "sourceFiles": ["src/gui-client.d"]
        },
        {
            "name": "server",
            "targetName": "server",
            "targetType": "executable",
            "sourceFiles": ["src/server.d"]
        }
    ]
}

```

The current way of having to do the equivalent is by specifying the inverse: `"excludedSourceFiles": ["src/server.d", "src/gui-client.d"]` with a list of all files which include an entrypoint, except for the one you want to compile in. This makes for large, somewhat more difficult to read package files, when you begin to add more than two or three targets. 

The above isn't possible because "excludedSourceFiles" overrides _all_ "sourceFiles" directives, even configuration specific ones. I think it makes sense for a sub-configuration specific "sourceFiles" to override its the global configuration.

**Comment by WebFreak001** [comment]
configuration-specific source files seem to override the ignored source files in current dub versions already.
