### ISSUE TITLE
DUB init : Mistaking 'source' as a file.

### ISSUE THREAD

**Issue by dd86k** [dlang/dub#1070]
![image](https://cloud.githubusercontent.com/assets/8390674/22867912/dedb919a-f15d-11e6-8f94-7edf08f5709f.png)

Small time notice (as in, "ez2fix"), but `source` in this case is a directory, which could confuse an end-user.

A simple fix would be checking if it's a directory with `isDir`.

**Comment by daym** [comment]
... what? A directory is a file. So is a regular file, a device file, a named pipe file etc...

**Comment by dd86k** [comment]
Ah, I understand.
