### ISSUE TITLE
Missing docs for $DC variable

### ISSUE THREAD

**Issue by jacob-carlborg** [dlang/dub#1073]
In DStep, I have the need to run a configuration script written in D, using `preGenerateCommands`. Currently this just invokes DMD [1]. To support multiple compilers it would need to somehow, perhaps using an environment variable, be able to access the compiler Dub is using to build the project.

[1] https://github.com/jacob-carlborg/dstep/blob/static-linking-clang/configure#L1

**Comment by s-ludwig** [comment]
The compiler binary should be available in the `$DC` variable. Documenting this is still a TODO.

**Comment by jacob-carlborg** [comment]
Thanks, that works. I changed the title.

**Comment by jacob-carlborg** [comment]
I tried to use the `$DC` variable directly in a `preGenerateCommands` command. That fails with `Invalid variable: DC`. If move the content of `preGenerateCommands` to a shell script instead and invoke in the shell script in `preGenerateCommands` it works. Is that intentional?

**Comment by veelo** [comment]
> I tried to use the `$DC` variable directly in a `preGenerateCommands` command. That fails with `Invalid variable: DC`. If I move the content of `preGenerateCommands` to a shell script instead and invoke the shell script in `preGenerateCommands` it works. Is that intentional?

This is being addressed by #2217.

**Comment by veelo** [comment]
The `$DC` variable is currently documented, so I think we can close this.
