### ISSUE TITLE
What did happen to the "already up-to-date" message ?

### ISSUE THREAD

**Issue by BBasile** [dlang/dub#1091]
Since a few weeks I don't see it anymore. Was it removed on purpose ?

**Comment by s-ludwig** [comment]
Do you mean the `<package> <version>: target for configuration "<config>" is up to date.` one or something else? I still do get the former for GIT master.

**Comment by BBasile** [comment]
It happens when the target is a library. For example with DUB itself: 
`dub build --build=debug --config=library`, I never see the information message.

**Comment by BBasile** [comment]
It happens for example with x11: https://github.com/nomad-software/x11 and with the command
`dub build --build=release --config=library`. Repeat several times to be sure and you'll never see the message.

Strangely enough (and despite of what i've said in a comment that i've just deleted) if I build DUB as a lib the info message is well displayed.

**Comment by s-ludwig** [comment]
Verbose output reveals this: `File (...)\packages\x11-1.0.16\x11\dub.selections.json doesn't exist, triggering rebuild.`
The corresponding condition should be adjusted to only trigger if a package has dependencies at all. x11 doesn't and thus there is no need to create a dub.selections.json, I can't remember now but probably that is also the logic that has changed recently.

**Comment by BBasile** [comment]
Indeed, the lib is rebuild each time. Should it be or is the report invalid ?

**Comment by s-ludwig** [comment]
No, the behavior is incorrect, so definitely valid.
