### ISSUE TITLE
linker flags when using LDC on OSX

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#1095]
I've been getting a problem [linking sqlite3](https://travis-ci.org/SingingBush/ddbc/builds/200528080) when using `--compiler=ldc2` on OSX. I've tried numerous things to resolve this such as putting `"lflags-osx": ["-L/usr/local/opt/sqlite3/lib/"],` into the dub.json (the sqlite3 was installed via homebrew) but no luck in resolving the problem.

Having put in `"buildOptions-osx": ["verbose"]` I can see that sqlite is in the linker options twice, once as `-lsqlite3` then as `-llibsqlite`:

```bash
/usr/bin/gcc .dub/obj/ddbc-tests.o -o .dub/build/test-debug-posix.osx-x86_64-ldc_2071-901939F20AA190DB2353167EAF39DBED/ddbc-tests -L/usr/local/Cellar/ldc/1.1.1_1/lib -L/usr/local/opt/sqlite3/lib/ -lsqlite3 -lphobos2-ldc -ldruntime-ldc -llibsqlite3 -ldl -lpthread -lm -m64 
ld: library not found for -llibsqlite3
```

I'm not sure if this in a problem with dub or ldc but thought best to raise here as I suspected it's possibly dub building up the linker args.

**Comment by SingingBush** [comment]
sqlite is in the dub file as `"libs-posix": ["sqlite3"]` btw.

**Comment by kinke** [comment]
Looks like this was solved with https://github.com/SingingBush/ddbc/commit/5eab6cdf77be132123a46cf9885073b071a44ab2.
