### ISSUE TITLE
dub build doesn't output to cwd except when targetPath is present 

### ISSUE THREAD

**Issue by tofuninja** [dlang/dub#1108]
Running "dub build [package name]" doesn't put the build output in the current working directory but instead puts it in the package directory. This changes if the package has "targetPath" defined, causing the build to output to cwd/targetPath. It's inconsistent, either the cwd should always be ignored or never ignored. I think the correct approach would be to never ignore it. 

dub 1.2.1
windows 10

**Comment by BBasile** [comment]
Well it should never use the cwd actually. No _targetPath_ means "output in package root". _targetPath_ specified means "output in a path relative to the root directory" (if it's relative only ?).

**Comment by tofuninja** [comment]
Well having it respect the cwd is a convenient way to control where the output is placed as there isn't any other way.

**Comment by BBasile** [comment]
The CWD is never guaranteed. IDEs must known at 100% were the binary is produced, e.g to launch them.

**Comment by tofuninja** [comment]
The cwd can always be controlled so I don't see how it's not guaranteed. But either way, there should be a way to control where output gets place, IDEs need that too,

**Comment by BBasile** [comment]
> there should be a way to control where output gets place

Yes, `targetPath` and `targetName`, but `targetPath` should be relative to the `dub.json` location.

**Comment by tofuninja** [comment]
I meant for the IDE/other tools to control it, not for the project designer to control it. TargetPath doesn't help with that.

**Comment by BBasile** [comment]
I see.Wwe clearly disagree but i'm not an official voice anyway. IMO if there's a bug it's that the cwd  is used in some cases. In this cases my IDE will fail for certain commands. I'll follow what happens if changes are made after this report.

**Comment by WebFreak001** [comment]
I tried to reproduce it like this:
```bash
mkdir foo
cd foo
dub init -n
dub build # properly puts it in the package directory
cd ..
dub build --root=foo # properly puts it in the package directory
dub add-local foo/
dub build foo # properly puts it in the package directory
dub remove-local foo/
cd foo
# edit dub.json to have a targetPath set
dub build # properly puts it in foo/targetPath
cd ..
dub build --root=foo # properly puts it in foo/targetPath
dub add-local foo/
dub build foo # properly puts it in foo/targetPath
dub remove-local foo/
```

as well as

```bash
dub fetch dscanner # dscanner is a public package with targetPath set
dub build dscanner # binary is in package folder as expected
```

Seems like behavior is consistent now, if not please reopen with a reproducible test case.

DUB 1.27.0

For building outside the package directory: an extra command line parameter should probably be added for that (something like `--dest=path/to/somewhere`)

**Comment by LunaTheFoxgirl** [comment]
> For building outside the package directory: an extra command line parameter should probably be added for that (something like `--dest=path/to/somewhere`)

This feature is added with https://github.com/dlang/dub/pull/3059
