### ISSUE TITLE
dub ignores DYLD_LIBRARY_PATH environment variables

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#111]
I'm on OSX.
cd vibe.d/examples/http_server
dub
Checking dependencies in 'vibe.d/examples/http_server'
Building configuration "application", build type debug
Running dmd (compile)...
Linking...
ld: library not found for -levent

ls /usr/local/homebrew/lib/libevent.dylib #found
export DYLD_LIBRARY_PATH=/usr/local/homebrew/lib/
dub

... same error

**Comment by MartinNowak** [comment]
Mmh, ld uses `LIBRARY_PATH` during link time to lookup libraries, at least on linux.

**Comment by WebFreak001** [comment]
I think this can be closed as this is rather a configuration issue with the D compiler / with your D distribution. Use dmd.conf or ldc2.conf to configure global linker flags.
