### ISSUE TITLE
dub -v build -b ddox returns exit code -11

### ISSUE THREAD

**Issue by Amaranthos** [dlang/dub#1115]
When building my vibe app with travis using `dub -v build -b ddox` the build returns -11 after parsing the docs but before generating any html.

Can't reproduce running locally (Windows 10), it builds no problem.

DMD version: v2.071.1
DUB version: 1.2.1

Not sure if I should be raising it here or with ddox?

Build log available [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/222232501/log.txt)

**Comment by ohdatboi** [comment]
Not a dub's issue. Dub prints `Program exited with code -11` when program it runs (ddox in this case) receives SEGFAULT.

**Comment by s-ludwig** [comment]
Definitely looks like a DDOX issue and two null pointer access bugs have been fixed in the meantime. If it still occurs, please re-open a ticket at https://github.com/rejectedsoftware/ddox/issues - I'll then take a look at it ASAP.

**Comment by Amaranthos** [comment]
Seems to have resolved the issue
https://travis-ci.org/Amaranthos/blogd-spaces/jobs/224317828

Thanks
