### ISSUE TITLE
Better support for own registries

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1119]
In big companies they do not like to use the official dub registry (code.dlang.org) but have their own registry running due to security issues. They clone also the git repositories to their own git server and do code checks.

With the command parameters --skip-registry and registry dub already support this scenario but it isn't possible to set this values in the dub.json. Every developer and for every usage in CI tools (Jenkins) you have to set this parameters while calling dub. 
It would be great if you can set these parameters in dub.json. The luxury version would be if you could set these parameters system wide...

**Comment by andre2007** [comment]
Solved with #1173

**Comment by s-ludwig** [comment]
For completeness, it's also possible to put a field `"registryUrls": ["http://internalregistry"]` into `~/.dub/settings.json`. Just `--skip-regsitry` only works from the command line ATM.
