### ISSUE TITLE
Can't depend on executable targets

### ISSUE THREAD

**Issue by marrub--** [dlang/dub#1127]
```json
{
   "name": "myproject",
   "targetType": "executable",
   "targetPath": "bin",
   "sourcePaths": ["mysource"],
   "buildRequirements": ["allowWarnings"],
   "dependencies": {
      "myproject:prog1": "*"
   },
   "subPackages": [
      {
         "name": "prog1",
         "targetName": "Prog1",
         "targetType": "executable",
         "sourcePaths": ["myprog1source"],
         "dependencies": {
            "myproject:lib2": "*",
            "someexternalthing": "0.0.4"
         }
      }
   ]
}
```
When running `dub generate visuald`, this only generates a project for `myproject` and nothing for `prog1`. The issue being `myproject` might rely on `prog1` to do something for it at runtime, or (in my case) you just want the solution to include `prog1` as well.

**Comment by MartinNowak** [comment]
That's not supported since dependency means linking, not too positive whether we want to add your use-case.
As a workaround you can simply run `dub fetch pkg && dub build pkg` in a prebuild step.
Might be worth adding to the cookbook in the wiki.

**Comment by timotheecour** [comment]
> That's not supported since dependency means linking

why does it have to mean linking. dependency should just mean dependency in the sense of makefile dependency. See also https://github.com/marler8997/har/issues/14 which is blocked by this
