### ISSUE TITLE
~/.dub/packages getting fairly big compared to other build tools

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#1129]
over time the local dub repo in my home directory get's fairly large. Compared to other similar tools I use (maven, gradle, npm, cargo) dub dependencies take up a lot of space. I usually delete old versions of dependencies to try any preserve space but ideally it would be good if dub did more to reduce wasted disk space.

I've noticed is that dub creates builds of packages for each build type / compiler combination, so over time as I've updated compiler versions (with brew upgrade on mac) the `~/.dub/packages` folder grows significantly. For example in `~/.dub/packages/consoled-1.0.4/consoled/.dub/build/` I have 21 separate builds:

library-debug-posix.osx-x86_64-dmd_2071-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2071-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2071-SOMEHASH
library-unittest-posix.osx-x86_64-dmd_2071-SOMEHASH
library-unittest-posix.osx-x86_64-dmd_2071-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2072-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2072-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2072-SOMEHASH
library-unittest-posix.osx-x86_64-dmd_2072-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2073-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2073-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2073-SOMEHASH
library-debug-posix.osx-x86_64-dmd_2073-SOMEHASH
... etc, you get the idea.

and that's just one version of one dependency.

I now have dmd 2.074 so these are all pointless. It would be really good if dub had a command that would tell it to get rid of any dependency builds in `~/.dub/packages` that are for an older compiler version. Or perhaps just to clean all the dependency builds.

Perhaps these builds shouldn't be under `~/.dub/packages` at all but in the `.dub` directory within my project.

**Comment by MartinNowak** [comment]
Yes, we should limit the amout of builds in a most recently used cache manner. Adding a clean command for old builds should be trivial. Just deleting ~/.dub/packages is a workaround for now.
Those builds are in HOME/~.dub folder so the build cache for libraries can be reused by multiple projects.

**Comment by MartinNowak** [comment]
You can use `dub clean --all-packages` to remove the cached builds.

**Comment by SingingBush** [comment]
great thanks. running `du ~/.dub/packages/` showed I had 2.9 gig worth of packages, after running `dub clean --all-packages` that was down to 2.5 gig. So that's certainly helpful.

**Comment by dhasenan** [comment]
It would be *very* handy for dub to run this automatically once every, say, 500 builds. `~/.dub` grew to 250GB for me.

**Comment by ZombineDev** [comment]
@dhasenan let's continue the discussion in https://github.com/dlang/dub/issues/1561.
