### ISSUE TITLE
 The directory name is invalid.

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1130]
specifying sub packages and single file execution does not work together.
Dub tries to create a directory with the name vibe-d:http.
As colons are invalid in file system, this will fail:

```
/+ dub.sdl:

name "app"
dependency "vibe-d:http" version=">=0.0.1"
+/

void main(){}
```

dub app.d
....dub\build\vibe-d:utils-0.7.31: The directory name is invalid.

**Comment by MartinNowak** [comment]
Looks like on Windows, right?

**Comment by andre2007** [comment]
Actually the issue is caused by the temporary folder argument and the bug is located here:
https://github.com/dlang/dub/blob/master/source/dub/generators/build.d#L162

If the temporary folder argument is set, the folder path is build by the pack.name.
To solve the issue just replace bad characters (:) with other characters.

it is a windows only bug if ":" is allowed on linux paths
