### ISSUE TITLE
dub dustmite --no-redirect

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1133]
if you use dub dustmite and there is an initial error, there will be a hint from dustmite, that you can use the argument --no-redirect to get more information what went wrong.

Unfortunatelly the dustmite implementation within dub does not know the --no-redirect argument and will complain if you use it.

I give it a try and hacked into into dub, somewhere here:
https://github.com/dlang/dub/blob/master/source/dub/commandline.d#L1779
but although it was no passed to dustmite, no additional information was print.

**Comment by MartinNowak** [comment]
Maybe a redirect issue (stdout/stderr) of the subprocess?

**Comment by ohdatboi** [comment]
Error (enhancement) description is not clear, please provide some steps to reproduce an issue you are facing *but* in a new issue.

Also, dustmite is now included with dmd.
