### ISSUE TITLE
user flags in dub.json cannot overide the default

### ISSUE THREAD

**Issue by jackspring2046** [dlang/dub#1135]
[Suggested by Johan Engelen](https://forum.dlang.org/post/pmjilzakdlptofdvlwna@forum.dlang.org)
>I try to disable inlining in "dub.json" like
>`"dflags":[
                 "-disable-inlining"
         ],`
>  but it doesn't work, because then dub calls ldc2 like this:
> 'ldc2   -disable-inlining  -release  -enable-inlining -Hkeep-all-bodies -O3 -w -oq' and inlining in ldc2 will still be enabled.

there are two flags about inlining in ldc2 above, and the uers flag ' -disable-inlining' is placed right after 'ldc2', then it's is overrided by '-enable-inlining' the default one.

perhapes, let user flags override the default is better

Thanks.

**Comment by s-ludwig** [comment]
There is a compiler agnostic way to specify this: `"buildRequirements": ["disallowInlining"]`

Since the inline flags are added additively depending on the selected build type (e.g. "release"), the only other way to remove a flag is be to customize the build type:
```
"buildTypes": {
    "release": {
        "buildOptions": ["releaseMode", "optimize"]
    }
}
```

**Comment by jackspring2046** [comment]
Thanks. 
I'll try these.
