### ISSUE TITLE
temp build: shared libraries copied to wrong folder

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1136]
Create a file app.d with this content

```
/+ dub.sdl:

name "app"
dependency "vibe-d" version=">=0.8.0-beta.5"
+/
void main(){}
```

Execute the file with comand: dub run --temp-build --single app.d

The shared libraries are copied to the directory of app.d. That seems wrong, as the executable is created in a temp folder

**Comment by aravindavk** [comment]
It is working as expected in my setup. Any patch merged to fix the issue?

In my machine, nothing new created in the directory of app.d, but temp dir `/tmp/.dub/build/app-~master/application-debug-linux.posix-x86_64-dmd_2075-E9EC992511DA0F36653085343EE0277B/` contains `app` and `app.o` file

    $dub --version
    DUB version 1.4.0, built on Jul 19 2017

    $dmd --version
    DMD64 D Compiler v2.075.0
    Copyright (c) 1999-2017 by Digital Mars written by Walter Bright

**Comment by andre2007** [comment]
vibe.d has platform specific settings for copying files. On Windows the openssl dlls needs to be copied, That isn't the case on linux. Therefore you do not face this issue although it isn't a platform specific issue:

https://github.com/rejectedsoftware/vibe.d/blob/master/tls/dub.sdl#L12

**Comment by andre2007** [comment]
Fixed with pr https://github.com/dlang/dub/pull/1590
