### ISSUE TITLE
Retry failed package downloads once or twice

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#1167]
Sometimes either the dub registry or github.com fails to deliver the zip file for a package. For normal builds this is acceptable, because dependencies are usually downloaded much less frequently than a build is invoked and restarting the build is trivial. But for CI builds this can be annoying. Usually these failures are of very temporary nature, so retrying once or maybe twice should eliminate most cases.

**Comment by andre2007** [comment]
Retry was implemented long time ago. The new pr https://github.com/dlang/dub/pull/1566 refactors the retry logic as it was duplicated to maven supplier.

This issue can be closed?
