### ISSUE TITLE
Detect the use of incompatible licenses in the dependency tree

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#117]
It would be nice to get a warning whenever source code uses an illegal license structure (e.g. BSD licensed code using GPL code) to enforce a correct use of licenses in the ecosystem and to warn users early on of potential issues in complex dependency structures.

**Comment by WebFreak001** [comment]
Closing this as non-implementing, as this is a feature that's not really possible to do automated effectively.

For discussion moving to #2403, as there are SPDX tools that kind of attempt this kind of thing for very basic license incompatibilities.
