### ISSUE TITLE
Return code of dmd

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1187]
It would be quite interesting to get the return code of dmd after a dub run.
In my example, I run dub in a cloud environment with limited resources (1024 MB RAM). For some packages dub (dmd) will fail to compile with build mode separate due to the memory constraints.
In this case dmd will fail with return code 137.

My shell script which runs in the cloud environment could, if it would know the return code of dmd , just call dub again with build mode singleFile. 

The return code of the compiler (dmd) could be provided as environment variable

**Comment by grogancolin** [comment]
An environment variable likely won't work here - as the child process won't be able to modify it's parents environment.

It could be written to a file though.

**Comment by ohdatboi** [comment]
Dub now prints exit code on errors.
