### ISSUE TITLE
Binary distributed dub fails to load curl

### ISSUE THREAD

**Issue by yazd** [dlang/dub#120]
Using Fedora 19 x64, when running dub, I get:

```
dub: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```

The previous binary v0.9.16 works without problems.

**Comment by MyLittleRobo** [comment]
Having the same issue on Fedora 20 with dmd 2.0.69 and dub 0.9.24. 

Workaround with symlink to libcurl still helps.

**Comment by SingingBush** [comment]
I'm having this problem on Fedora 23 with dmd _v2.069.2_ and _dub-0.9.24_ 64 bit. After doing the symlink I can at least run dub, but it complains about the following:

```
$ dub --version
dub: /lib64/libcurl-gnutls.so.4: no version information available (required by dub)
DUB version 0.9.24, built on Aug 19 2015
```

**Comment by s-ludwig** [comment]
I just noticed that I forgot to upload an RPM package for the 0.9.24 release. The Linux binary is built on Ubuntu, which isn't binary compatible with Fedora.

**Comment by s-ludwig** [comment]
Done now: http://code.dlang.org/files/dub-0.9.24-1.x86_64.rpm
