### ISSUE TITLE
Using ldmd2 causes a warning about possible "build errors" to be spit out

### ISSUE THREAD

**Issue by joakim-noah** [dlang/dub#1206]
If I use ldmd2 with dub, it always spits out the following warning, despite not having any actual problems:
```
The determined compiler type "ldc" doesn't match the expected type "dmd". This will probably result in build errors.
```
What is the point of this warning?  Looking at the code, it appears that it sets [the `Compiler` to dmd here](https://github.com/dlang/dub/blob/master/source/dub/compilers/compiler.d#L39), since ldmd2 has dmd in its name and must be passed dmd-style flags.  However, [the `BuildPlatform.compiler` is set using the inbuilt version flag to ldc2](https://github.com/dlang/dub/blob/master/source/dub/platform.d#L134), so [that warning is always generated for ldmd2](https://github.com/dlang/dub/blob/master/source/dub/compilers/compiler.d#L134).  I imagine the same is true for gdmd, though I haven't tried it.

The warning seems useless, maybe we can get rid of it or refine it.

**Comment by joakim-noah** [comment]
Hmm, it turns out the [`BuildPlatform.compiler` is actually set here to ldc, not ldc2](https://github.com/dlang/dub/blob/master/source/dub/compilers/utils.d#L348), as you can see in my warning message above.  I wonder why the unused stuff in `dub.platform` is even around.

**Comment by timotheecour** [comment]
just ran into this as well
dub --version
DUB version 1.6.0, built on Nov 26 2017
