### ISSUE TITLE
code.dlang.org - Unexpected ''' when converting from type string to type ulong

### ISSUE THREAD

**Issue by Yousha** [dlang/dub#1215]
### How to reproduce?
https://code.dlang.org/?sort=updated&category=&skip=460&limit=%27

### Logs
400 - Bad Request

Error handling field limit: Unexpected ''' when converting from type string to type ulong

Internal error information:
std.conv.ConvException@/home/soenke/.dvm/compilers/dmd-2.074.1/linux/bin/../../src/phobos/std/conv.d(2111): Unexpected ''' when converting from type string to type ulong
----------------
/home/soenke/.dvm/compilers/dmd-2.074.1/linux/bin/../../src/phobos/std/conv.d:81 pure @safe ulong std.conv.parse!(ulong, immutable(char)[]).parse(ref immutable(char)[]) [0xfd11cd]
/home/soenke/.dvm/compilers/dmd-2.074.1/linux/bin/../../src/phobos/std/conv.d:1755 pure @safe ulong std.conv.toImpl!(ulong, immutable(char)[]).toImpl(immutable(char)[]) [0xfd1298]
/home/soenke/.dvm/compilers/dmd-2.074.1/linux/bin/../../src/phobos/std/conv.d:194 pure @safe ulong std.conv.to!(ulong).to!(immutable(char)[]).to(immutable(char)[]) [0xfd103f]
../../.dub/packages/vibe-d-0.8.0/vibe-d/web/vibe/web/common.d:741 nothrow bool vibe.web.common.webConvTo!(ulong).webConvTo(immutable(char)[], ref ulong, ref vibe.web.common.ParamError) [0xfd0f77]
../../.dub/packages/vibe-d-0.8.0/vibe-d/web/vibe/web/common.d:710 nothrow vibe.web.common.ParamResult vibe.web.common.readFormParamRec!(ulong).readFormParamRec(scope vibe.http.server.HTTPServerRequest, ref ulong, immutable(char)[], bool, vibe.web.common.NestedNameStyle, ref vibe.web.common.ParamError) [0xfd0ed4]
../../.dub/packages/vibe-d-0.8.0/vibe-d/web/vibe/web/web.d:744 void vibe.web.web.handleRequest!("getHome", void dubregistry.web.DubRegistryWebFrontend.getHome(immutable(char)[], immutable(char)[], ulong, ulong), dubregistry.web.DubRegistryFullWebFrontend).handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse, dubregistry.web.DubRegistryFullWebFrontend, vibe.web.web.WebInterfaceSettings) [0xfd0b11]
../../.dub/packages/vibe-d-0.8.0/vibe-d/web/vibe/web/web.d:186 @trusted void vibe.web.web.__T20registerWebInterfaceHTC11dubregistry3web26DubRegistryFullWebFrontendVE4vibe3web6common11MethodStylei5Z.registerWebInterface(vibe.http.router.URLRouter, dubregistry.web.DubRegistryFullWebFrontend, vibe.web.web.WebInterfaceSettings).__lambda42(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0xf97d54]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/router.d:212 _D4vibe4http6router9URLRouter13handleRequestMFNfC4vibe4http6server17HTTPServerRequestC4vibe4http6server18HTTPServerResponseZ21__T9__lambda4TmTAAyaZ9__lambda4MFNfmMAAyaZb [0x125e3a7]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/router.d:620 const(@safe bool function(immutable(char)[], scope @safe bool delegate(ulong, scope immutable(char)[][]))) vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch [0x125f1ce]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/router.d:553 @safe bool vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope @safe bool delegate(ulong, scope immutable(char)[][])) [0x125ea0b]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/router.d:205 @safe void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse) [0x125e059]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/server.d:2043 @safe bool vibe.http.server.handleRequest(vibe.core.stream.Stream, vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo, ref vibe.http.server.HTTPServerSettings, ref bool, scope std.experimental.allocator.IAllocator) [0x128c8c7]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/server.d:1791 @trusted void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo).__lambda4() [0x128af70]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/server.d:1783 @safe void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo) [0x128add1]
../../.dub/packages/vibe-d-0.8.0/vibe-d/http/vibe/http/server.d:1657 nothrow @safe void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings, vibe.http.server.HTTPServerContext).doListen(vibe.http.server.HTTPListenInfo, vibe.http.server.HTTPServerContext, bool, bool).__lambda6(vibe.core.net.TCPConnection) [0x128a5e4]
../../.dub/packages/vibe-d-0.8.0/vibe-d/core/vibe/core/drivers/libevent2_tcp.d:618 void vibe.core.drivers.libevent2_tcp.ClientTask.execute() [0x135f074]
../../.dub/packages/vibe-d-0.8.0/vibe-d/core/vibe/core/core.d:620 void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*) [0xee4ac7]
../../.dub/packages/vibe-d-0.8.0/vibe-d/core/vibe/core/core.d:1269 void vibe.core.core.CoreTask.run() [0x12faf56]
??:? void core.thread.Fiber.run() [0x13e907b]
??:? fiber_entryPoint [0x13e8f5a]
??:? [0xffffffff]

**Comment by WebFreak001** [comment]
Did you type in that `'` character (%27) or where do you have that URL from? It is clearly a malformed request. Also something which you would report on dlang/dub-registry. Just remove the &limit=%27 at the end

**Comment by Yousha** [comment]
Remove it? lol
Dude that means its vulnerable...

**Comment by WebFreak001** [comment]
it sends a 400 bad request because it can't parse the number, I think thats a reasonable thing to do. Though if it isn't an API it should probably show that in a UI that is more obvious for the user

**Comment by s-ludwig** [comment]
Can't see a vulnerability there either. Investing in a better UX also doesn't really seem to be worth it, as that URL is never encountered during normal use.

**Comment by WebFreak001** [comment]
well one can find out about the server architecture & version running there I guess, which you probably wouldn't want in case someone finds a critical bug

**Comment by s-ludwig** [comment]
The version is easier to find out by looking at the "Server" header ;) But yeah, having function addresses exposed isn't ideal from a security perspective (although very helpful for debugging), but also not really a vulnerability. There are many other ways to trigger an error page with a stack trace, so if that's the issue then we should rename the issue to something like "Stack traces on error pages increase the attack surface".

It would definitely be nice to have error stack traces be logged internally instead of presenting them to the user.

**Comment by WebFreak001** [comment]
I run vibe.d but I setup nginx so it removes the Server header and only shows nginx, removing the stacktraces would be a great way to secure it even more

**Comment by s-ludwig** [comment]
Hiding the server version in the end is nothing more than security by obscurity - on top of that, everyone can look up dub.selections.json in the dub-registry repository.

**Comment by WebFreak001** [comment]
hiding the server version makes me a less likely target for random attacks though

**Comment by s-ludwig** [comment]
That's probably true in certain cases, but even there, most random attacks just directly test a certain attack vector without inspecting the target first. But for dub-registry in particular it simply doesn't provide any meaningful advantage at all. Stack traces are a different thing though, and is makes sense to hide them - or at least the addresses - even with `@safe` and DIP1000 on the horizon.

@Yousha: Is the stack trace what you meant when you said vulnerability?

**Comment by s-ludwig** [comment]
Displaying the stack trace is inhibited by https://github.com/rejectedsoftware/vibe.d/commit/19befb4f31d8bd34e9a01eebab2fbaba3dcd19e7

Closing since there is no other conceivable security concern here.
