### ISSUE TITLE
Linker files are passed to the compiler command line when building static lib 

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#1235]
When building a static library, no linker files should be passed to the compiler, as those will instead be passed to the executable/dynamic library that is built in the last step. Currently, linker files specified as `"sourceFiles"`, however, will end up on the command line.

**Comment by John-Colvin** [comment]
Why? If I specify something as a `sourceFile` I'm expecting it to be used in the compilation step.

**Comment by s-ludwig** [comment]
Because it should be passed to the linker. It will typically cause duplicate symbol errors otherwise in complex dependency hierarchies. Also, in my particular case, both, LDC and DMD, were simply crashing with a segmentation fault.

Note that the code was always intended to behave like this and already does for libraries added using `libs`, `lflags` or implicitly as a dependency.
