### ISSUE TITLE
Linker file ending detection should be compiler dependent

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#1249]
Currently `dub.compilers.utils.isLinkerFile` decides purely based on the host operating system (Windows or not Windows) whether a file should go to the linker or to the compiler. This assumption is not true when using something other than Optlink or the MSVC linker.

The decision instead needs to be made in the `Compiler` class that drives the compiler and linker, so `isLinkerFile` should be deprecated at its current place and moved as a method to the compiler classes.

See also #1236.

**Comment by andre2007** [comment]
See pr https://github.com/dlang/dub/pull/1755
