### ISSUE TITLE
ddoc files in dependencies are generated into the current directory

### ISSUE THREAD

**Issue by dhasenan** [dlang/dub#1253]
### System information
- **dub version** 1.5.0
- **OS Platform and distribution** Ubuntu 16.04 x86_64
- **compiler version** dmd-2.076.0

### Bug Description
Dub builds ddoc files from projects in the current project's dependency set into html into the current directory.

This was discovered with package `thrift-d` (version 0.1.0). The temporary fix was to add the ddoc file to `excludedSourceFiles`. Fortunately, the ddoc file was low value, so it isn't important that the file doesn't build even when building the library on its own.

### How to reproduce?
Create a dub package containing a file, `source/docs.d`, containing:

```
Ddoc
<h1>Look, I'm documentation!</h1>
```

Create another dub package that depends on the first.

Build the second dub package.

You now have a file in the second dub package's source directory named `docs.html`. It is an HTML file whose body is `<h1>Look, I'm documentation!</h1>`

### Expected Behavior
The html file should not appear in my current directory. It should either not appear, or only appear in the dependency's build directory in `~/.dub/packages`, or something like that.

This can probably be fixed by making the output directory and running dmd from that directory.

**Comment by MartinNowak** [comment]
Changing directories during builds is quite a tricky approach and easily introduces other bugs.

As a simple workaround I'd recommend you to use `.dd` as suffix for ddoc files, as is done by most other D projects. Then dub won't think those are source files and not pass them to the compiler.

It's actually fairly bad of dmd to produce an html file in `-c` compilation mode (without any `-D`).

**Comment by dhasenan** [comment]
Since it's not dub's problem, I'm closing this.
