### ISSUE TITLE
Please add support for GitLab

### ISSUE THREAD

**Issue by testing-in-chrome** [dlang/dub#1260]
[GitLab](www.gitlab.com) offers a huge set of features, and it would be great if we can publish repos hosted on GitLab on DuB.

**Comment by s-ludwig** [comment]
The package registry (<https://code.dlang.org/>) supports registering GitLab hosted packages, there is a drop-down menu on the "Register package" page that lets you choose between GitHub, Bitbucket and GitLab. It's also possible to use a private registry instance together with a private GitLab repository by writing a settings.json file.

**Comment by testing-in-chrome** [comment]
Oh, thanks! Then the documentation [here](https://code.dlang.org/publish) is outdated. Can we make sure that it mentions that Gitlab is supported and possibly provide some of the info you gave above?

**Comment by MartinNowak** [comment]
Here is the source for that page @testing-in-chrome, feel free to add that info.
https://github.com/dlang/dub-registry/blob/b24dedb562295355fda91bc9ae7e08c481a32300/views/publish.dt

**Comment by s-ludwig** [comment]
I've opened a PR against dub-registry.

**Comment by testing-in-chrome** [comment]
For some reason, I still can't see those changes on this page: https://code.dlang.org/publish

Are they not pushed yet?
