### ISSUE TITLE
Cross Compilation

### ISSUE THREAD

**Issue by ghost91-** [dlang/dub#1264]
#1259 states that cross compilation works, and it is true, it "somehow" works. However the method suggested in that issue depends on manually setting specific compiler flags for ldc in the package description file. This is probelematic if your application has dependencies, because you need to manually patch the package description files of those dependencies in order for this method to work.

To solve this problem, I'd suggest to instead use the already existing `--arch` flag or introduce other flags to achieve cross compilation.

**Comment by MartinNowak** [comment]
Think that's indeed what arch is for. In fact -m32/-m64 is already cross-compiling.
`--target` would've been a better name though

let's not split the discussion and continue on #1259
