### ISSUE TITLE
Process for dlang static linking

### ISSUE THREAD

**Issue by svnpenn2** [dlang/dub#1268]
Using this file:

    void main() {
      import std.net.curl;
      download("http://example.com", "index.htm");
    }

I can compile with D:

    dmd z.d

However this creates a shared build relying on external curl library. How can I
create static build?

**Comment by svnpenn2** [comment]
https://github.com/dlang/phobos/pull/3009

**Comment by cup** [comment]
https://stackoverflow.com/questions/46635748/process-for-dlang-static-linking

**Comment by ohdatboi** [comment]
Question has been answered on the StackOwerflow and doesn't have anything to do with dub.
