### ISSUE TITLE
Undefined reference to symbol while building on fedora 19 using ldc

### ISSUE THREAD

**Issue by rushidesai** [dlang/dub#127]
$ ./build.sh
Generating version file...
Running ldmd2...
bin/dub.o:(.rodata._D123TypeInfo_S3std8typecons86__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z10RefCounted6__initZ[_D123TypeInfo_S3std8typecons86__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z10RefCounted6__initZ]+0x60): undefined reference to `_D3std8typecons86__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z10RefCounted10__postblitMFZv'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1

**Comment by JohanEngelen** [comment]
Can be closed?

**Comment by s-ludwig** [comment]
Tested and working (through Travis-CI).
