### ISSUE TITLE
subConfiguration(s) not taken into account when subpackage is not explicitly provided

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#1274]
### System information
- DUB version 1.5.0, built on Sep 10 2017
- ArchLinux
- Any (but tested with DMD 2.076.1)

### Bug Description
When a package description with `subConfiguration "vibe-d:tls" "botan"` (for example) is provided, but dependency only includes `"vibe-d"` (not `"vibe-d:tls"`), the `subConfiguration` field is ignored.

### How to reproduce?
```json
{
    "name": "test",
    "dependencies": {
        "vibe-d": "~>0.8.1"
    },
    "subConfigurations": {
        "vibe-d:tls": "botan"
    }
}
```

Result in the following build log:
```
Performing "debug" build using dmd for x86_64.
vibe-d:utils 0.8.1: building configuration "library"...
vibe-d:data 0.8.1: building configuration "library"...
vibe-d:core 0.8.1: building configuration "libevent"...
vibe-d:crypto 0.8.1: building configuration "library"...
diet-ng 1.4.3: building configuration "library"...
vibe-d:stream 0.8.1: building configuration "library"...
vibe-d:textfilter 0.8.1: building configuration "library"...
vibe-d:inet 0.8.1: building configuration "library"...
vibe-d:tls 0.8.1: building configuration "openssl"... // <== HERE
vibe-d:http 0.8.1: building configuration "library"...
vibe-d:mail 0.8.1: building configuration "library"...
vibe-d:mongodb 0.8.1: building configuration "library"...
vibe-d:redis 0.8.1: building configuration "library"...
vibe-d:web 0.8.1: building configuration "library"...
vibe-d 0.8.1: building configuration "libevent"...
test ~master: building configuration "application"...
Linking...
dub build  15.52s user 2.00s system 81% cpu 21.479 total
```

### Expected Behavior
Having `subConfiguration` taken into account when the parent package is provided.

**Comment by s-ludwig** [comment]
Having sub configurations work for indirect dependencies would complicate the resolution process somewhat and the predictability as well, because a different configuration somewhere can change whether an indirect dependency is chosen or not. We can analyze the implications further, but an immediate solution is implemented with #1194 by at least telling the user what happens (or doesn't happen).

**Comment by andre2007** [comment]
@Geod24 as there is now a warning shown, is the problem solved for you?

**Comment by Geod24** [comment]
Yep
