### ISSUE TITLE
Missing dub.json causes infinite loop in dub

### ISSUE THREAD

**Issue by kbogert** [dlang/dub#1277]
### System information
- **dub version**  dub 1.4.0
- **OS Platform and distribution**  Linux Ubuntu 16.04
- **compiler version** dmd-2.076.1

### Bug Description

I have a subproject that, due to a bad commit, had its dub.json deleted.  I use the --root parameter to build this subproject in a CI script, and found that the dub build never finished. Running dub with --vverbose shows the output below.

### How to reproduce?

(accept all defaults during dub init)

dub init debug
cd debug
dub init test
rm test/dub.json
dub build --root=test --vverbose

### Expected Behavior

Should throw an error that dub.sdl or dub.json is not found and stop.

### Logs

Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/kbogert/.dub/packages/local-packages.json
iterating dir /home/kbogert/.dub/packages/ 
iterating dir /home/kbogert/.dub/packages/ entry emsi_containers-0.5.3
iterating dir /home/kbogert/.dub/packages/ entry dsfml-2.1.1
iterating dir /home/kbogert/.dub/packages/ entry dsymbol-0.2.9
iterating dir /home/kbogert/.dub/packages/ entry derelict-util-2.0.6
iterating dir /home/kbogert/.dub/packages/ entry dlangide-0.8.8
iterating dir /home/kbogert/.dub/packages/ entry derelict-sdl2-2.0.2
iterating dir /home/kbogert/.dub/packages/ entry x11-1.0.19
iterating dir /home/kbogert/.dub/packages/ entry tested-0.9.4
iterating dir /home/kbogert/.dub/packages/ entry libdparse-0.7.1
iterating dir /home/kbogert/.dub/packages/ entry msgpack-d-1.0.0-beta.6
iterating dir /home/kbogert/.dub/packages/ entry dlangui-0.9.167
iterating dir /home/kbogert/.dub/packages/ entry derelict-gl3-1.0.23
iterating dir /home/kbogert/.dub/packages/ entry derelict-ft-1.1.3
iterating dir /home/kbogert/.dub/packages/ entry dcd-0.9.1
No package found in current working directory.
There was no package description found for the application in '/home/kbogert/Documents/debug/test'.
Note: Failed to determine version of package  at .. Assuming ~master.
Warning: The package in /home/kbogert/Documents/debug/test/ has no name.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/kbogert/.dub/packages/local-packages.json
iterating dir /home/kbogert/.dub/packages/
iterating dir /home/kbogert/.dub/packages/ entry emsi_containers-0.5.3
iterating dir /home/kbogert/.dub/packages/ entry dsfml-2.1.1
iterating dir /home/kbogert/.dub/packages/ entry dsymbol-0.2.9
iterating dir /home/kbogert/.dub/packages/ entry derelict-util-2.0.6
iterating dir /home/kbogert/.dub/packages/ entry dlangide-0.8.8
iterating dir /home/kbogert/.dub/packages/ entry derelict-sdl2-2.0.2
iterating dir /home/kbogert/.dub/packages/ entry x11-1.0.19
iterating dir /home/kbogert/.dub/packages/ entry tested-0.9.4
iterating dir /home/kbogert/.dub/packages/ entry libdparse-0.7.1
iterating dir /home/kbogert/.dub/packages/ entry msgpack-d-1.0.0-beta.6
iterating dir /home/kbogert/.dub/packages/ entry dlangui-0.9.167
iterating dir /home/kbogert/.dub/packages/ entry derelict-gl3-1.0.23
iterating dir /home/kbogert/.dub/packages/ entry derelict-ft-1.1.3
iterating dir /home/kbogert/.dub/packages/ entry dcd-0.9.1
Collecting dependencies for
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/kbogert/.dub/packages/local-packages.json
iterating dir /home/kbogert/.dub/packages/
iterating dir /home/kbogert/.dub/packages/ entry emsi_containers-0.5.3
iterating dir /home/kbogert/.dub/packages/ entry dsfml-2.1.1
iterating dir /home/kbogert/.dub/packages/ entry dsymbol-0.2.9
iterating dir /home/kbogert/.dub/packages/ entry derelict-util-2.0.6
iterating dir /home/kbogert/.dub/packages/ entry dlangide-0.8.8
iterating dir /home/kbogert/.dub/packages/ entry derelict-sdl2-2.0.2
iterating dir /home/kbogert/.dub/packages/ entry x11-1.0.19
iterating dir /home/kbogert/.dub/packages/ entry tested-0.9.4
iterating dir /home/kbogert/.dub/packages/ entry libdparse-0.7.1
iterating dir /home/kbogert/.dub/packages/ entry msgpack-d-1.0.0-beta.6
iterating dir /home/kbogert/.dub/packages/ entry dlangui-0.9.167
iterating dir /home/kbogert/.dub/packages/ entry derelict-gl3-1.0.23
iterating dir /home/kbogert/.dub/packages/ entry derelict-ft-1.1.3
iterating dir /home/kbogert/.dub/packages/ entry dcd-0.9.1
Collecting dependencies for
Checking for upgrades.
Using cached upgrade results...
Add config  application
Add config  library
NON-PRIMARY:  library
Eliminating config library for
NON-PRIMARY:
Eliminating config  for
NON-PRIMARY:
Eliminating config  for
NON-PRIMARY:
Eliminating config  for
NON-PRIMARY:
Eliminating config  for
NON-PRIMARY:
Eliminating config  for
NON-PRIMARY:

continues on forever .....

**Comment by ohdatboi** [comment]
This is still a thing with dub 1.10.0 and dmd 2.081.2

**Comment by Geod24** [comment]
Still a thing. It also does a double-`dub init` for some reason.

**Comment by Geod24** [comment]
Fix: https://github.com/dlang/dub/pull/1845
