### ISSUE TITLE
Add dub version command

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1288]
For my XMake D plugin I was asked to make the "version" attribute of dub.json writable.

NPM has this feature: 
```
npm version 1.4.1
```
This will set the version in the package.json file to 1.4.1

For now I have to manually edit dub.json / dub.sdl. But it would be quite nice if 
I just could execute
```
dub version 1.4.1
```

**Comment by ZombineDev** [comment]
The version comes from git tag, not from dub.json.

**Comment by andre2007** [comment]
You can set the version attribute in dub.json. if you do not set it has the value ~master.

**Comment by ZombineDev** [comment]
That's because your dub project is either not in a repository or you haven't got any tags in semver format.
As far as I remember, dub-registry fetches the tags from GitHub/GitLab/BitBucket for each package and when the user downloads a particular version of a package dub-registry fills the `version` field in dub.json the git tag.
So the `version` field used to override the package version (or specify it if you're not in a git repo), but idiomatic dub usage relies only on git tags.

**Comment by andre2007** [comment]
Either way, where the version value is filled from, I got the requirement that this value has to be persistent in the dub.json with an additional postfix. Within the build infrastructure there is an input field. The value of this input field should be added to the version as postfix. This is the behaviour of other XMake plugins which I has to fulfill.

**Comment by MartinNowak** [comment]
The version field in the package file is deprecated, versions come from the underlying VC.
It is also not (no longer?) mentioned in the docs http://code.dlang.org/package-format?lang=json#version-specs.
At the moment dub ignores unknown fields in dub.json/sdl (though I could imagine those to become warnings). This allows you to add metadata to your dub.json/sdl, e.g. using a command along the lines of:
```sh
# use jq and sponge to add version
jq '. + {version: "1.0.0"}' dub.json | sponge dub.json
# newer versions of jq support --in-place
jq --in-place '. + {version: "1.0.0"}' dub.json
# use sed to insert version before description
sed '/.*"version":.*/d; s/\s*"description"/  "version": "v1.1.0",\n&/' dub.json
# same for dub.sdl
sed -i '/^version.*/d; s/^description/version "1.0.0"\n&/' dub.sdl
```

**Comment by andre2007** [comment]
Thanks for the information. That is quite bad news. I will create a new issue to revive the version attribute in the package file because in some use cases extracting the version from VC is not possible.
