### ISSUE TITLE
Empty project doesn't compile

### ISSUE THREAD

**Issue by sigod** [dlang/dub#13]
```
import std.stdio;

void main()
{ 
    writeln("Edit source/app.d to start your project.");
}
```

`dub build` produces following error:

```
.dub\packages\vibe-d\source\vibe\appmain.d(36): Error: only one main/WinMain/DllMain allowed
Error: Build command failed with exit code 1
```

May be better to replace this code with `Hello World` example?

**Comment by bubnenkoff** [comment]
I am getting such error on next project: http://dlang.ru/gdal-d-binding.zip
I can't understand why, because it have only one main.
