### ISSUE TITLE
Add environment variable VERSION

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1302]
Could you add the environment variable VERSION which contains the version determined by dub?

This environment variable would ease the creation of a version_.d file (like https://github.com/dlang/dub/blob/master/source/dub/version_.d).

With an environment variable VERSION a preBuildCommand "echo $VERSION > ./source/version_.d" could be directly specified in dub.json. This would make the build.sh / build.cmd superflous.

**Comment by Timoses** [comment]
That would be very handy.

See linked issue for an example: https://github.com/jacob-carlborg/dstep/issues/185

I'd suggest a name like `PACKAGE_VERSION` which should be available even when the package is fetched with `dub fetch`.

**Comment by andre2007** [comment]
Pull request is merged.
