### ISSUE TITLE
'dub describe' does not respect overrides nor path-based dependencies

### ISSUE THREAD

**Issue by llucenic** [dlang/dub#1303]
### System information

- **dub version**: 1.6.0
- **OS Platform and distribution**: debian 9.2
- **compiler version** dmd-2.077.0

### Bug Description
When overriding local package path using `dub add-override <package> <version> <path>` then `dub describe` on \<path> does not return the package's version specified in the override. The similar applies for building submodules using _path-based dependency_ specification, where dub assumes `~master` version instead of one retrieved commonly via `git describe`.

### How to reproduce?
Assuming two folders for package `arinas`:
- /data/arinas (local package folder)
- /data/project/ext/arinas (another local version to override local package folder)

`dub add-local /data/arinas` // package: arinas, version: 0.4.13
`dub add-override arinas 0.4.13 /data/project/ext/arinas`
`dub describe --root=/data/project/ext/arinas` // returns "~master" !!

### Expected Behavior
`dub describe --root=/data/project/ext/arinas` should return "0.4.13"

**Comment by Geod24** [comment]
Overrides are deprecated now, as of https://github.com/dlang/dub/pull/2461
And regarding path-based dependency, I just checked, we return the path every time (and `~master`).
