### ISSUE TITLE
Replace the usage of gethostbyname() with getaddrinfo() which is ipv6 compliant

### ISSUE THREAD

**Issue by curantes** [dlang/dub#1325]
### System information

- **dub version**: 1.6.0
- **OS Platform and distribution**: openSUSE Tumbleweed
- **compiler version**: dmd-2.077.1

### Bug Description

When making a rpm package of dub on openSUSE I get below warning from rpmlint:

```
dub.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/dub
The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```
The gethostbyname*() and gethostbyaddr*() functions are deprecated as among other things they are not IPv6 ready. Applications should use getaddrinfo(3) and getnameinfo(3) instead.

### How to reproduce?
can make a test build on OBS (https://build.opensuse.org)
### Expected Behavior
rpmlint should not show these warnings/errors
### Logs
https://build.opensuse.org/package/live_build_log/devel:languages:D/dub/openSUSE_Tumbleweed/x86_64

**Comment by Geod24** [comment]
@curantes : Is this still an issue ? Looking at the logs, doesn't look like it, and I couldn't find any reference in dub.

**Comment by WebFreak001** [comment]
ditto on geod's comment, so just gonna close this.
