### ISSUE TITLE
Cannot pass argument --DRT-covopt to dub test

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1329]
With the new dmd release 2.078 it is possible to control the coverage behavior.
But it seems not possible to pass argument --DRT-covopt to dub test

```
dub test --coverage -- --DRT-covopt "dstpath:./cov"
Running .\cov-sample.exe dstpath:./cov
```

As you can see in the output, --DRT-covopt is lost

**Comment by mathias-lang-sociomantic** [comment]
This is a duplicate of https://github.com/dlang/dub/issues/1280

**Comment by andre2007** [comment]
Thanks for the info. I am closing this issue.
