### ISSUE TITLE
"dub clean" method to remove files generated by build process

### ISSUE THREAD

**Issue by WebDrake** [dlang/dub#134]
dub should implement a `clean` method to remove files generated in the build process.  This should help to avoid the need for risky behaviour such as manually deleting generated files, or using `git clean-tree` or `git reset`.

The essential behaviour should be similar to `make clean`, i.e. remove all compiled libraries/executables, all generated object files, etc.

**Comment by HuskyNator** [comment]
docs folders remain untouched, though I don't know if this is intentional
