### ISSUE TITLE
Why dub describe "architecture" is type array?

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1353]
In my XMake build plugin I need to find out the architecture (x86 or x86_64). Therefore I want to call dub describe to get this information. I just stumbled over the fact, architecture is of type array:
```
"architecture": [
                "x86"
        ],
```
In which case, architecture contains more than 1 entry? Or does it always contain 1 entry?

**Comment by MartinNowak** [comment]
Check determineArchitecture et.al.
https://github.com/dlang/dub/blob/350a0315c38fab9d3d0c4c9d30ff6bb90efb54d6/source/dub/platform.d#L48-L89
