### ISSUE TITLE
Need support about an error in dependency version

### ISSUE THREAD

**Issue by BBasile** [dlang/dub#1360]
[See this dlang-community PR](https://github.com/dlang-community/D-Scanner/pull/553#pullrequestreview-92173042). I define a libdparse version that exists but DUB says it cannot be satisfied.

**Comment by BBasile** [comment]
looks like i finally found the origin of the problem. Does DUB want all the dependencies to use the same version of another dependency, meaning thus following is not accepted

```
project -> depA -> depX v1.0.0
        -> depB -> depX v1.2.0
```

?

**Comment by skl131313** [comment]
Looks like nothings changed over the course of a year (in a few days). :birthday:

https://github.com/dlang/dub/issues/1065

**Comment by BBasile** [comment]
Yesh this is that. Actually when using a DUB script the message was better see: https://github.com/dlang-community/libddoc/pull/35
