### ISSUE TITLE
dub build -c library does not seem to add generated files to the library (on the first run)

### ISSUE THREAD

**Issue by gizmomogwai** [dlang/dub#1370]
### System information
- **dub version**: DUB version 1.7.2, built on Feb  7 2018
- **OS Platform and distribution**: OSX
- **compiler version** DMD64 D Compiler v2.078.2

### Bug Description
I have a small library that uses preBuildCommands to generate a source in out/generated/packageversion/...
This path is also put to import and sourcePaths
````
sourcePaths "source" "out/generated/packageversion"
importPaths "source" "out/generated/packageversion"
preBuildCommands "dub run packageversion -- --packageName=asciitable"
````
### How to reproduce?
when i run dub build -c library the first time
ar -t on my library does not show the generated module (packageversion.o) in the archive.
when i run dub build -c library the second time its included.

### Expected Behavior
should be there from the first place.

### Logs
logs also show, that the out/geernated/packageversion folders (that do not exist in the beginning) cause a warning of dub, because the are not existend

### Workaround.
I tried to replace the import/sourcepath thing with 
`sourceFiles "out/generated/packageversion/asciitable/packageversion.d"´ which interestingly produces the correct output from the start.

**Comment by MartinNowak** [comment]
You need to use preGenerateCommands for that to work. That one is run before searching source pathes, the other is run afterwards.
Note though that preGenerateCommands is always run, even if a target doesn't have to be rebuild.
So indeed you might want to go with explicity adding your generated files in sourceFiles.
