### ISSUE TITLE
Build should stop early

### ISSUE THREAD

**Issue by gizmomogwai** [dlang/dub#1371]
I added by mistake something like
0.0.15F as version of a dependency.
This is not a proper semver which was complained about by dub.
```
Error adding local package: Invalid SemVer format: 0.0.15F
```

but dub still tried to compile the project, which failed for sure miserable, but later.
It should just bail early with proper location information, because obviously something is wrong in the setup, and dub cannot know if it still can do meaningful work.

**Comment by Geod24** [comment]
Dub should now bail early with proper location information, as we switched to a much stricter parser. If it's not the case, please re-open with a `dub.json` example (or `dub.sdl`).

**Comment by gizmomogwai** [comment]
It bails out very fast now, the error message could be better, e.g. mentioning the filename, linenumber and quoting the line ... atm (tested with dub version 1.34.0 that is bundled with ldc-1.35.0) the output is like: `Error Invalid SemVer format: 1.3.0F`.

**Comment by Geod24** [comment]
Are you using dub.sdl or dub.json ?
dub.json will give better error messages.

**Comment by gizmomogwai** [comment]
ah i see .. i used dub.sdl.

**Comment by gizmomogwai** [comment]
With json it looks like this 
```
     Warning Your `dub.json` file use non-conventional features that are deprecated
     Warning Please adjust your `dub.json` file as those warnings will turn into errors in dub v1.40.0
     Warning Error was: 
.../blub/dub.json(6:14): dependencies[argparse]: Invalid SemVer format: 1.3.0F
     Warning Your `dub.json` file use non-conventional features that are deprecated
     Warning Please adjust your `dub.json` file as those warnings will turn into errors in dub v1.40.0
     Warning Error was: 
...blub/dub.json(6:14): dependencies[argparse]: Invalid SemVer format: 1.3.0F
Error Invalid SemVer format: 1.3.0F
```
Like the warnings do not seem to be very meaningful, as as soon as I replace the wrong semver they disappear.

**Comment by gizmomogwai** [comment]
sounds good!
thanks a lot!
