### ISSUE TITLE
Dub doesn't ignore non-empty hidden files

### ISSUE THREAD

**Issue by alexrotaru** [dlang/dub#1372]
### System information
- **dub version**:DUB version 1.6.0, built on Jan 23 2018
- **OS Platform and distribution**: arm v7 (raspberry pi 3)
- **compiler version**
LDC - the LLVM D compiler (1.7.0):
  based on DMD v2.077.1 and LLVM 5.0.1
  built with LDC - the LLVM D compiler (1.6.0)
  Default target: arm-unknown-linux-gnueabihf
  Host CPU: cortex-a53
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    arm     - ARM
    armeb   - ARM (big endian)
    thumb   - Thumb
    thumbeb - Thumb (big endian)

### When mounting a drive from OS X using afp, OS X automatically creates .AppleDouble folders within each mounted folder. The .AppleDouble folders contain files with the same names as the ones existing in the original folder. For example:
```
pi@raspberrypi:~/ $ ls -al source/
drwxr-xr-x  4 pi pi 4096 Feb 11 16:58 .
drwxr-xr-x 10 pi pi 4096 Feb 11 16:58 ..
-rw-r--r--  1 pi pi 1889 Feb 11 14:06 app.d
drwxr-xr-x  2 pi pi 4096 Feb 11 16:58 .AppleDouble
-rw-r--r--  1 pi pi 6148 Feb 11 14:17 .DS_Store

pi@raspberrypi:~/ $ ls -al source/.AppleDouble/
drwxr-xr-x 2 pi pi 4096 Feb 11 16:58 .
drwxr-xr-x 4 pi pi 4096 Feb 11 16:58 ..
-rw-rw-rw- 1 pi pi  741 Feb 11 16:58 app.d
-rw-rw-rw- 1 pi pi  741 Feb 11 16:58 .DS_Store
-rw-rw-rw- 1 pi pi  741 Feb 11 16:58 .Parent
```

when running "dub build", I get the following error for one of the project submodules:
`crate/source/crate/.AppleDouble/base.d: Error: module base odd length of UTF-16 char source 741`

If I create an empty hidden file that ends in .d, everything is fine, but once I have some data in that file, a compiler error is thrown.

### How to reproduce?

1. create a non empty hidden file in your project
2. run dub build
### Expected Behavior

- Hidden files and folders should be ignored by dub even if they are not empty. 

Or

- One should be able to exclude folders using wildcards. Going back to the OSX example, I'd like to be able to exclude "\*AppleDouble/\*.d" (I tried to set this in _dub.json_ using _excludedSourceFiles_ and it had no effect. maybe I don't know they right format...)

**Comment by Samathy** [comment]
Confirmed still an issue with dub 1.15.

Looks like paths containing source files are resolved and added to the list of files to compile regardless of if they're in hidden sub-directories or not.
https://github.com/dlang/dub/blob/master/source/dub/recipe/packagerecipe.d#L249

I'll be taking this on.

**Comment by thewilsonator** [comment]
Thanks!
