### ISSUE TITLE
`dub test` does not run global preBuildCommands of a project

### ISSUE THREAD

**Issue by gizmomogwai** [dlang/dub#1374]
In a hello world project this works, but in https://github.com/gizmomogwai/androidlogger4d
dub test does not generate the needed file.

**Comment by andre2007** [comment]
I cannot reproduce the issue with dub version 1.9.0.
Can this issue be closed?

```
PS C:\Users\pc\Desktop\t4> dub test
Running custom 'unittest' configuration.
Performing "unittest" build using C:\D\dmd2\windows\bin\dmd.exe for x86.
t4 ~master: building configuration "unittest"...
Running pre-build commands...
123
```

same for pre-generate commands

**Comment by gizmomogwai** [comment]
I cannot reproduce this anymore.

**Comment by bcsgh** [comment]
I'm seeing this:

```
$ dub --version
DUB version 1.23.0, built on Oct 18 2020
$ dub test
Generating test runner configuration 'some-library' for 'library' (library).
/repo/source/proto/proto.d: No such file or directory
$ dub build
Performing "debug" build using /usr/bin/dmd for x86_64.
protobuf 0.6.2: target for configuration "protobuf" is up to date.
something ~HEAD: building configuration "application"...
Running pre-build commands...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
```

The `dub.json` (stripped of proprietary stuff)

```
{
	"authors": [ "someone" ],
	"dependencies": { "protobuf": "==0.6.2" },
	"description": "Thing",
	"lflags": [ "-fuse-ld=gold" ],
	"license": "proprietary",
	"name": "thing",
	"preBuildCommands": [
		"protoc -I$${DUB_PACKAGE_DIR}proto $${DUB_PACKAGE_DIR}proto/proto.proto --d_out=$${DUB_PACKAGE_DIR}source/proto --plugin=$${HOME}/.dub/packages/protobuf-0.6.2/protobuf/build/protoc-gen-d"
	],
	"sourceFiles": [ "source/proto/proto.d" ],
	"versions": [ ]
}
```

**Comment by gizmomogwai** [comment]
@bcsgh you are right ... i also can reproduce it with dmd 2.094.2 and dub 1.23.0 using the attached project
[sample-dub-project.tar.gz](https://github.com/dlang/dub/files/5593187/sample-dub-project.tar.gz)

steps to reproduce: make sure source/lib.d is deleted. the run dub build -> works.
then delete source/lib.d again and run dub test.

**Comment by gizmomogwai** [comment]
also using preGenerateCommands as mentioned in #1725 does not help.

**Comment by Geod24** [comment]
> also using preGenerateCommands as mentioned in #1725 does not help.

There has been a fix to `preGenerateCommands` recently, it should start working as expected from the next release.

**Comment by gizmomogwai** [comment]
looking forward to that!
