### ISSUE TITLE
Extra flag for x86_mscoff builds on windows in libs directive

### ISSUE THREAD

**Issue by atilaneves** [dlang/dub#1393]
### System information
- **dub version**: 1.6.0
- **OS Platform and distribution**: Windows 10 64-bit
- **compiler version** dmd 2.077.1

### Bug Description

The dmd linker command is wrong for x86_mscoff builds.

### How to reproduce?

dub.sdl:
```
name "foo"
libs "the32" platform="windows-x86"
libs "the32mscoff" platform="windows-x86_mscoff"
libs "the64" platform="windows-x86_64"
```

`% dub build --arch=x86_mscoff`

### Expected Behavior

For `--arch=x86` and `--arch-x86_64` dub does the right thing, adding `the32.lib` and `the64.lib` to the linker command respectively. For `--arch=x86_mscoff` however, it adds _both_ `the32.lib` and `the32mscoff`.lib, which is wrong.

**Comment by Geod24** [comment]
x86 now means MSCOFF, so I think we can consider this "fixed" ?
