### ISSUE TITLE
dub-1.7.2/dub/source/dub/compilers/buildsettings.d(170,56): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1399]
dub 1.7.2: building configuration "library-nonet"...
../../../../.dub/packages/dub-1.7.2/dub/source/dub/compilers/buildsettings.d(170,56): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/compilers/buildsettings.d(172,40): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/dub.d(572,51): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/dub.d(579,49): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/dub.d(1107,38): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/generators/visuald.d(222,80): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/init.d(54,34): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/init.d(146,37): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
/Users/timothee/homebrew/opt/dmd/include/dlang/dmd/std/format.d(3493,28): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/vibe-d-0.8.3-beta.1/vibe-d/inet/vibe/inet/urltransfer.d(113,6): Deprecation: alias vibe.core.path.Path is deprecated - Use NativePath or one the specific path types instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/internal/utils.d(498,29): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/packagemanager.d(371,33): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/packagemanager.d(680,84): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/packagemanager.d(682,69): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/packagemanager.d(685,61): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/packagesupplier.d(105,31): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.
../../../../.dub/packages/dub-1.7.2/dub/source/dub/project.d(240,47): Deprecation: function vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.Segment.toString is deprecated - Use .name instead.

**Comment by Geod24** [comment]
Fixed by #1825
