### ISSUE TITLE
Generated manual pages have errors

### ISSUE THREAD

**Issue by ximion** [dlang/dub#1424]
Hi!
When making the Debian/Ubuntu package use the new manual pages provided by Dub directly, our QA system found out that the generated pages have errors.
That doesn't prevent us from shipping them, but it's an issue that should be addressed.

```
dub: manpage-has-errors-from-man usr/share/man/man1/dub-build.1.gz 13: warning: numeric expression expected (got `f')
dub: manpage-has-errors-from-man usr/share/man/man1/dub-convert.1.gz 15: warning: numeric expression expected (got `f')
dub: manpage-has-errors-from-man usr/share/man/man1/dub-describe.1.gz 39: warning: numeric expression expected (got `b')
```

Offending lines are for example `.IP -f, --force`, so I guess just fixing the generator to properly escape hyphens will do the trick.

**Comment by Geod24** [comment]
CC @WebFreak001

**Comment by WebFreak001** [comment]
hyphens are escaped now since #2365, only warning generated in all pages by man now for a 80-character width test is basically that the online documentation URL is too long. But the syntax there is correct and in the actual man reader it doesn't seem to provide any issues (on arch at least)
