### ISSUE TITLE
building served-d failed for dependency resolution procerss

### ISSUE THREAD

**Issue by dangbinghoo** [dlang/dub#1434]
### System information
- DUB version 1.8.0, built on Mar  2 2018 (from dmd deb package 2.0.79.0).
- Deepin 15.5  (based on Debain 8 jessie).
- build failed when resolving dependency. so not related to D compiler.

### Bug Description
```
Return for isfreedesktop: [0.1.1, 0.1.0, ~master]
Search for versions of eventsystem (1 package suppliers)
Return for eventsystem: [1.2.0, 1.1.0, 1.0.1, 1.0.0, ~master]

The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.
```

### How to reproduce?
git clone the `https://github.com/Pure-D/serve-d.git` and just type `dub build`.

### Expected Behavior
expected to build, but stuck for dependency.
### Logs
the log is the tail part of `dub --vverbose build`, I tried to give the full log, but the txt file has size of 1GB, it's not possible to upload.
[dub-1-8-0-build-serve-d-log.txt](https://github.com/dlang/dub/files/1874473/dub-1-8-0-build-serve-d-log.txt)

**Comment by dangbinghoo** [comment]
hmm, I think the issue is may related to deepin linux. On archlinux, I use the same dub version and all things just goes well.

**Comment by WebFreak001** [comment]
it is very likely due to dub not pulling the latest commit from the master dependency. Try deleting ~/.dub/packages/workspace-d-master

**Comment by dangbinghoo** [comment]
@WebFreak001 yes, you're right, I deleted ~/.dub/packages/workspace-d-master and dub build serve-d is working now with dub 1.8.0 on deepin linux. Thanks!
