### ISSUE TITLE
"Bad Gateway" when adding package to code.dlang.org.

### ISSUE THREAD

**Issue by JonathanILevi** [dlang/dub#1441]
When adding a package to the dub registry, after clicking "Register package" a "502 Bad Gateway" page is shown and the package is not added.

I am not sure how to specifically reproduce.  I know it is doing it for me on both Firefox Developer Edition and Chrome.  It is also doing it when I try over a different wifi network.

**Comment by WebFreak001** [comment]
can you tell us on which package this happens?

**Comment by LupusOssorum** [comment]
https://github.com/JonathanILevi/LList
I also tried it on a package that is already in the registry just to see what would happen (https://github.com/JonathanILevi/queue) and it gave me the same "Bad Gateway".

**Comment by JonathanILevi** [comment]
https://github.com/JonathanILevi/LList
I also tried it on a package that is already in the registry just to see what would happen (https://github.com/JonathanILevi/queue) and it gave me the same "Bad Gateway".
