### ISSUE TITLE
Document settings.json

### ISSUE THREAD

**Issue by rtbo** [dlang/dub#1463]
I'm not sure this repo is the most appropriate for such issue as I don't know exactly where are the web pages for `code.dlang.org`.

Although the command line and package format is very well documented, I can't find any documentation about the `settings.json` file. The information I could find is in the github issues and in the source code. Without reading the code, we don't know what options are supported.

**Comment by WebFreak001** [comment]
a PR documenting it should be made to https://github.com/dlang/dub-registry, but I think this issue actually fits here because dub is the thing using it. I have never actually really heard about settings.json being used or what it is used for lol

**Comment by rtbo** [comment]
Ah, I thought `dub-registry` was only the app serving and caching the packages.

Yeah, there's nothing in there you cannot do with CLI. It helps to save keystrokes however.
E.g. to set a default compiler that is not `/usr/bin/dmd`.
Today, on windows each of my invocations looks like `dub --compiler=xx --arch=yy`. 
(on windows arch defaults to `x86` also on 64bits systems)

**Comment by WebFreak001** [comment]
yeah dub-registry is the server on `code.dlang.org`, it is everything there (including serving packages over http)

**Comment by SingingBush** [comment]
seems like settings.json only supports a `defaultCompiler` option. Found it in the [CHANGELOG.md](https://github.com/dlang/dub/blob/master/CHANGELOG.md)

**Comment by andre2007** [comment]
Regarding settings.json on windows a question as it fits here. Is it correct that settings.json is still effective in folder "AppData\Roaming\dub" while the dub packages moved to folder "AppData\Local\dub"?

**Comment by andre2007** [comment]
Pull request https://github.com/dlang/dub-docs/pull/11

**Comment by andre2007** [comment]
https://dub.pm/settings.html
