### ISSUE TITLE
Path-based dependencies and moving packages

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#1467]
If a package `A` depends on `B` and `B` has path-based dependency on `C`, `A` will have a relative path-based dependency in its `dub.selections.json`, which means it then cannot be independently moved (because the relative path would then point in the wrong place). Obviously calling `dub upgrade` will fix the path, but it can also change versions of other packages.

If absolute paths were always used in `dub.selections.json` that would fix the case where `A` is moved independently, but break the case where `A`, `B` and `C` are all moved together.

**Comment by ohdatboi** [comment]
I can't see a problem here. Just call `dub upgrade` and use `git diff` to look what it did or use local packages with `dub add-local`.

**Comment by Geod24** [comment]
> If absolute paths were always used in `dub.selections.json`

My understanding is that `dub.selections.json` is also something that could be committed to the repository. Using absolute path would break this.

**Comment by Geod24** [comment]
As said in my previous message, `dub.selections.json` can be committed to a git repository to make the build reproducible. Absolute path would break this, so we'd just be swapping a bug for another one.
