### ISSUE TITLE
allow defaults in ~/.dub/config

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#1468]
in #995 I suggested allowing users to configure useful defaults in a `~/.dub/config` file. Being able to set a timeout for code.dlang.org or being able to set values for parameters such as `--registry` or `--skip-registry` could be useful for some users.

**Comment by andre2007** [comment]
registryUrls is already implemented. Actually skipRegistry is missing. I am not 100% sure but I think there is already an open issue for skipRegistry.In the issue you mentioned there is also the question about a JFrog mirror functionality . This is implemented in dub master. Dub now supports accessing maven registries.

**Comment by SingingBush** [comment]
ah, that's in the `settings.json` relative to the dub binary, ok cheers. I still think `~/.dub/` would be a better place for such things. Will close this issue anyway.

As per #1463 this info needs to be easier to find.

**Comment by s-ludwig** [comment]
Settings can currently be in /etc/dub/settings.json, ~/.dub/settings.json or [dubbin]/../etc/dub/settings.json.
