### ISSUE TITLE
`--arch=` and `--compiler=` together with single file packages?

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#1470]
Does dub support using `--arch=` and `--compiler=` in conjunction with single file packages?

Ie:
`dub --arch=x86_64 --compiler=dmd foo.d`

I'm hitting an odd problem, and if this is NOT supported, that would explain the results I'm getting.

If it's not supported, if there a known workaround?

**Comment by s-ludwig** [comment]
Just putting the file name currently only works for the shortcut syntax used for shebang lines, so once dub arguments are to be added, `--single` needs to be specified explicitly: `dub --arch=x86_64 --compiler=dmd --single foo.d`

**Comment by Abscissa** [comment]
Ah, right. Must've forgotten that. Thanks.
