### ISSUE TITLE
Does not read settings from /etc/dub/settings.json

### ISSUE THREAD

**Issue by ximion** [dlang/dub#1472]
Hi!
I tried to use the recent addition of system-wide dub packages (#838) by adding `customCachePaths` to `/etc/dub/settings.json`. Unfortunately, it looks like dub never reads this file and only considers the local settings in `~/.dub/settings.json`.
Please make dub read the file in /etc, as the docs say, or alternatively a file in /usr/lib/dub/, so distributors can set a system location for dub packages.
Cheers,
    Matthias

**Comment by andre2007** [comment]
Actually  it is not ```/etc/...``` but ```<dub executable folder>/../etc/dub/settings.json```

I currently create a pull request which adds s new site to dub documentation to describe the settings and the available paths.
https://github.com/dlang/dub-docs/pull/11

The path you wrote were mentioned in a change log.

**Comment by andre2007** [comment]
@wilzbach 
My assumption is, current logic will find for ```/usr/bin/dub``` the settings file ```/usr/etc/dub/settings.json``` and not ```/etc/dub/settings.json```. 
I validated my assumption on a linux system which has ```/usr/bin/dub``` by creating file ```/usr/etc/dub/settings.json``` with invalid JSON format. This file is always found by dub.

NativePath(thisExePath).parentPath will find path ```/usr/bin```
../etc/dub/settings.json will go 1 hierarchy up and the into folder /etc/dub

**Comment by ximion** [comment]
Dub is of course in `/usr/bin/dub`, where it belongs as a binary installed by the system.
Creating anything in `/usr/etc` is not an option for a Debian package at least, because all system configuration has to go to `/etc`.
What I have seen a lot of times by other software is to get the current directory the executable is in and check if it starts with `/usr`. If that is the case, the settings file is searched for in `/etc`, in any other case arbitrary rules to obtain a configuration file are applied. In more rare cases, the check is extended for `/usr/local` to handle that path well as well.
