### ISSUE TITLE
Dependency graph is likely hitting a pathlogical case building dlangide

### ISSUE THREAD

**Issue by kbogert** [dlang/dub#1476]
### System information

- **dub version**: 1.9.0
- **OS Platform and distribution**: Ubuntu 16.04
- **compiler version** v2.080.0

### Bug Description

Trying to build the dlangide package version 0.8.12

Running:
     dub run --build=release dlangide --vverbose

I get the following:

     Dependency dcd -> dsymbol ~>0.3.7 mismatches with selected version 0.2.9 (ci=2)
     Dependency dsymbol -> emsi_containers ~>0.5.3 mismatches with selected version 0.5.1 (ci=3)
     Dependency dcd -> msgpack-d >=1.0.0-beta.3 <1.1.0-0 mismatches with selected version 0.9.3 (ci=6)
     Dependency derelict-sdl2 -> derelict-util ~>2.0.4 mismatches with selected version 2.1.0 (ci=9)
     Interation (ci=9) dcd 0.9.7, stdx-allocator 2.77.2, dsymbol 0.2.9, emsi_containers 0.5.1, experimental_allocator 2.70.0-b1, libdparse 0.7.2-alpha.4, msgpack-d 0.9.3, dlangui 0.9.177, derelict-sdl2 2.0.2, derelict-util 2.1.0 (C), derelict-gl3 1.0.24 (C), derelict-ft 1.1.2 (C), x11 1.0.20 (C), dsfml 2.1.1 (C)

in an infinite loop until timeout.

By editing dlangide's dub.json to change the dcd dependency to, for example:

        "dependencies": {
                "dcd": "==0.9.7",
                "dlangui": "0.9.178",
                "dsymbol": "~>0.2.9"
        },

dub will instead stop with a dependency error message such as:

     Package dcd contains invalid dependency dsymbol (no version candidates) (ci=0)
     Dependency derelict-sdl2 -> derelict-util ~>2.0.4 mismatches with selected version 2.1.0 (ci=8)
     Dependency derelict-ft -> derelict-util ~>2.0.6 mismatches with selected version 2.1.0 (ci=10)
     Root package dlangide reference dsymbol ~>0.2.9 cannot be satisfied.
     Packages causing the conflict:
	     dcd depends on ~>0.3.7
	     dlangide depends on ~>0.2.9
     Full exception: object.Exception@source/dub/dependencyresolver.d(180): Root package dlangide reference dsymbol ~>0.2.9 cannot be satisfied.
     Packages causing the conflict:
	     dcd depends on ~>0.3.7
	     dlangide depends on ~>0.2.9

**Comment by SamuelLongchamps** [comment]
Can repro for the same package (dlangide 0.8.12):
* macOS 10.13.4
* DUB version 1.9.0
* DMD64 D Compiler v2.080.1

**Comment by MartinNowak** [comment]
Well, fix the dependency conflict in the upstream packages then.
