### ISSUE TITLE
debugMode: Call DUB with --build=debug

### ISSUE THREAD

**Issue by jacob-carlborg** [dlang/dub#1482]
I have a project where I would like to split up the tests in three parts: unit tests, library tests and end to end tests. I tried to do that using configurations. When I do that and specify any of the build options: `unittests`, `debugMode` or `debugInfo` I get the following warnings when running Dub:

```
## Warning for package foo, configuration bar ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

debugMode: Call DUB with --build=debug
debugInfo: Call DUB with --build=debug
unittests: Call DUB with --build=unittest
```

Here's a sample of a a Dub file:

```json
{
    "name": "foo",
    "configurations": [
        {
            "name": "bar",
            "sourceFiles": ["source/foo.d"],
            "buildOptions": ["unittests", "debugMode", "debugInfo"]
        }
    ]
}
```

And then running Dub with: `dub build --config=bar`.

Am I doing something wrong? Are configurations not supposed to be used like this? Is there a better way to accomplish what I'm trying to do?

For the full example/use case, see DStep [1].

Dub version: `DUB version 1.9.0, built on May  1 2018`.

[1] https://github.com/jacob-carlborg/dstep/blob/8df56976fe489f7f66390f1d3c63cb8df1e787bb/dub.json#L44-L91

**Comment by ohdatboi** [comment]
```json
"buildOptions": ["unittests", "debugMode", "debugInfo"]
```

Is redundant because it's exactly what `unittest` build type [does](http://code.dlang.org/package-format?lang=json#build-types).

Just remove these lines and run dub like so:
```
$ dub build --config=bar --build=uniittest
```
