### ISSUE TITLE
Endless loop with conflicting packages - "The dependency graph blah blah blah"

### ISSUE THREAD

**Issue by SenorCMasMas** [dlang/dub#1484]
### System information
**Windows 10**
    * DUB version 1.8.0, built on Mar  3 2018
    * DMD32 D Compiler v2.080.0
**Ubuntu 16.04**
    * DUB version 1.8.0, built on Mar  3 2018
    * DMD64 D Compiler v2.079.1
**Debian9**
    * DUB version 1.7.1, built on Jan 21 2018
    * DMD64 D Compiler v2.079.1

### Bug Description
Dub goes into an endless loop when I specify two specific packages and attempt to build.
I have tested against the three platforms specified above.

I was able to cache the sdlang package locally and hack the unit-threaded version to get around this.

### How to reproduce?
dub init
+dependency "sdlang-d" version="~ >0.10.2" //<- note no space after tilde
+dependency "mysql-native" version="~ >2.2.2" //<- note no space after tilde
dub build

Note: tilde greaterthan (above) caused strike-through so I added a space.

### Expected Behavior
Download packages or fail with something other than "The dependency graph is likely hitting a pathological case"

### Logs
I can provide more log information if required.
*** From the middle of the process ***
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)
Package mysql-native contains invalid dependency unit-threaded (no version candidates) (ci=0)
Package sdlang-d contains invalid dependency unit-threaded (no version candidates) (ci=13)

**Comment by andre2007** [comment]
I cannot reproduce this issue with dub version 1.9.0
Can you check whether the issue still exists for you and close this issue if not?

**Comment by SenorCMasMas** [comment]
Sorry.. I was so happy that I forgot to close this!
Thank you SO MUCH for fixing it.
