### ISSUE TITLE
v1.8.0 vs 1.8.0

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#1485]
I just noted that we have dub-1.8.0 and dub-v1.8.0 too:

![image](https://user-images.githubusercontent.com/4370550/40774252-6d1e1e42-64c5-11e8-8042-57b5a66985e7.png)

https://github.com/dlang/dub/releases/tag/v1.8.0

I guess this is due to the installer script uploading dub-v1.8.0 binaries. Should I change the install script to omit the "v"?
We probably want all links to be simple and more or less equal and changing a few binaries is probably a lot less work than changing all from the past.

**Comment by Geod24** [comment]
> Should I change the install script to omit the "v"?

I would say no, let's keep the "v".
Although at that point there have been 10 releases, so I doubt anyone still uses this. Closing this.
If you think it still matters, feel free to re-open.
