### ISSUE TITLE
dub private repo authentication

### ISSUE THREAD

**Issue by rracariu** [dlang/dub#1499]
Currently there is no way to setup authentication on a private dub repository.

This feature is very useful for companies having dub repositories on some cloud infrastructure and wanting to keep the repository contents private.

The straightforward way to secure a repository is to put it behind a SSL server and configure client certificate authentication for it (https://arcweb.co/securing-websites-nginx-and-client-side-certificate-authentication-linux/).

`dub` should allow specifying this as an option and be instructed to use a client certificate when working with a private repository.

**Comment by andre2007** [comment]
Maybe not the exact answer you wanted but companies can run their own dub registries inhouse for various reasons. The scenario you describe is one possible use case. 

With recent dub version it is also possible to access maven repositories in addition to dub registries.
If a company already has an internal maven repository (Artifactory/Nexus/...) this repository can be used to host dub packages.

**Comment by rracariu** [comment]
I currently run a `dub-registry` in-house. The problem is that at some point you want to move it on the cloud or make it more visible on the network, and  at that point you really need authentication on the repo (even if you run it inside your company) to prevent un-authorized access.

Does dub know how to deal with authentication on maven repositories?

**Comment by andre2007** [comment]
The current maven implementation works the same way like the dub registry implementation. No authentication is implemented.

For the moment I can only propose some workarounds like a private cloud which is only available from the internal company network. 

Or if you have a maven repository with authentication, you could write a middleware (proxy) to which dub connects and the request is enhanced with credential data and forwarded to the public secured maven repository.

Maven access from dub are just http get requests..., same for dub registry requests

**Comment by rracariu** [comment]
Unfortunately neither are acceptable.

I will take a look at dub and see if I can implement my original proposal with client certificate authentication. My take is that it should not be hard to hook it up in the HTTP client part. Or maybe somebody that has more knowledge of dub internals will beat me to it.

**Comment by andre2007** [comment]
That 's great if you can contribute to Dub 👍

**Comment by Geod24** [comment]
It's possible to do this with a token. For example:
```json
{
    "registryUrls": [
        "https://dub.mycompa.ny/token/ThisIsQuiteSecret"
    ]
}
```
