### ISSUE TITLE
The `init` command is not interactive when DUB is not executed in a console

### ISSUE THREAD

**Issue by BBasile** [dlang/dub#1500]
I expected to be able to pass the string for the name, the author etc in the input stream, one by one but actually when piped dub doesn't read anything and it outputs directly the JSON to a file.

**Comment by ohdatboi** [comment]
It works fine:
```
$ echo "json\ntest\nMy test package\nMe\nPublic Domain\nCopyright 2018, Me" | dub init test
Package recipe format (sdl/json) [json]: Name [test]: Description [A minimal D application.]: Author name [gentleman]: License [proprietary]: Copyright string [Copyright © 2018, Me]: Add dependency (leave empty to skip) []: Successfully created an empty project in '/tmp/tmp.Yz4n5PaNdw/test'.
Package successfully created in test
$ cat test/dub.json 
{
	"name": "test",
	"authors": [
		"Me"
	],
	"description": "My test package",
	"copyright": "Copyright 2018, Me",
	"license": "Public Domain"
}
```

**Comment by BBasile** [comment]
I meant when DUB is not launched in a console

**Comment by ohdatboi** [comment]
It works fine this way too:
```D
import std.process;

void main() {
	auto pipe = pipeProcess(["dub", "init", "test"]);

	pipe.stdin.writeln("json");
	pipe.stdin.writeln("test");
	pipe.stdin.writeln("my test package");
	pipe.stdin.writeln("Me");
	pipe.stdin.writeln("Public domain");
	pipe.stdin.writeln("Copyright 2018, me");
}
```

**Comment by BBasile** [comment]
i can generate the json myself. i just opened this because i was a bit surprised right after trying.

**Comment by ZombineDev** [comment]
@BBasile From a quick look it seems that `dub init` should always work in interactive mode, unless the `-n|--non-interactive` flag is set:
https://github.com/dlang/dub/blob/0d8cc74d2c6653fb4dcceb571d46fc6b3c13662e/source/dub/commandline.d#L497

Can you provide more details on how to reproduce the issue?

**Comment by BBasile** [comment]
Given this line of code this issue was indeed very valid.
