### ISSUE TITLE
Single file package does not work for dynamic libraries

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1505]
Executing ```dub build --single app.d``` for this source code will fail

```d
/+ dub.sdl:
    name "hello"
    targetType "dynamicLibrary"
+/

import core.sys.windows.dll;

mixin SimpleDllMain;
```

DMD compiler shows its documentation. Issue is caused by the way dmd is called. In case of
a full dub package "app.d" is passed to dmd. 

C:\D\dmd2\windows\bin\dmd.exe -c -of.dub\build\library-debug-windows-x86-dmd_2081-311AEBA8C8A533519C96B488ED98CBCB\hello.obj -debug -g -w -version=Have_hello **-Isource source\app.d** -vcolumns

This is missing for the single file package.

C:\D\dmd2\windows\bin\dmd.exe -c -of.dub\build\library-debug-windows-x86-dmd_2081-311AEBA8C8A533519C96B488ED98CBCB\hello.obj -debug -g -w -version=Have_hello -vcolumns

**Comment by andre2007** [comment]
Just found this statement on code.dlang.org:
```Single-file packages cannot be used to create library packages```

**Comment by ZombineDev** [comment]
> Just found this statement on code.dlang.org [..]

That doesn't mean that it's a bad idea to change the behavior. Currently single file packages are only scripts (i.e. you can only `dub run` them). I'm not sure if someone has yet tries to make `dub build --single` work properly for libraries.
