### ISSUE TITLE
Endless loop while retrieving dependencies in multi registries scenario

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1519]
In addition to the standard registry, 2 additional registries are configured. These registries do not have the same packages like code.dlang.org but only a sub set. E.g. the package vibe-d is missing.

In a test application I specify vibe-d as dependency and execute dub build.
In an endless loop the first registry (my own, without vibe-d) is asked for vibe-d.
DUB version 1.10.0, built on Jul  6 2018

Checking for missing dependencies.
Search for versions of vibe-d (3 package suppliers)
Downloading maven metadata for vibe-d
Getting from http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/vibe-d/maven-metadata.xml
Getting http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/vibe-d/maven-metadata.xml...
Maven metadata vibe-d not found at maven repository at http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/ (404): HTTP request returned status code 404 (Not Found)
No versions for vibe-d for maven repository at http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/
Downloading maven metadata for vibe-d
Getting from http://localhost.com:8081/nexus/content/groups/build.snapshots/dubpackages/vibe-d/maven-metadata.xml
Getting http://localhost.com:8081/nexus/content/groups/build.snapshots/dubpackages/vibe-d/maven-metadata.xml...
Maven metadata vibe-d not found at maven repository at http://localhost.com:8081/nexus/content/groups/build.snapshots/dubpackages/ (404): HTTP request returned status code 404 (Not Found)
No versions for vibe-d for maven repository at http://localhost.com:8081/nexus/content/groups/build.snapshots/dubpackages/
Downloading metadata for vibe-d
Getting from https://code.dlang.org/packages/vibe-d.json
Getting https://code.dlang.org/packages/vibe-d.json...
Downloading maven metadata for vibe-d
Getting from http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/vibe-d/maven-metadata.xml
Getting http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/vibe-d/maven-metadata.xml...
Maven metadata vibe-d not found at maven repository at http://localhost.com:8081/nexus/content/groups/build.snapshots/com/localhost/dlang/ (404): HTTP request returned status code 404 (Not Found)
Downloading maven metadata for vibe-d
....endless...until....stopped

**Comment by andre2007** [comment]
This issue isn't reproducible with PR #1513. Therefore I close this issue.

**Comment by MartinNowak** [comment]
@andre2007 
There is a difference between fallback registries (mirrors of code.dlang.org) and other custom registries.
Retry should only kick in for server failures (5xx or connection failures) but obviously not for succesful but negative responses (e.g. 404).
Your log looks a bit like retry with the new maven metadata might not correctly implement this. Also it's unclear why maven metadata is downloaded when the normal metadata is correctly fetched already.

**Comment by andre2007** [comment]
I saw multiple times some buggy behaviour which might be related to this. In case you have an additional registry which has not the packages from code.dlang.org and you try to retrieve a package stored at code.dlang.org then then following will happen: for every package version available on code.dlang.org, there will be an http request to the additional registry which of cause will fail. I haven't found a way to reproduce this behaviour every time. I need to make deeper investigation on this issue. My gut feeling is, this bug is unrelated to the type of registry as far as different packages are available. But in any case I will recheck the maven registry code. Thank you.
