### ISSUE TITLE
DUB should not automatically fall-back to non-HTTPs repository

### ISSUE THREAD

**Issue by mbierlee** [dlang/dub#1522]
In module `dub.dub`, DUB's registry resolution is instructed to fall-back to a non-HTTPS alternative in case something is wrong with the HTTPs default. A man in the middle can invalidate the HTTPs certificate and make DUB fall back to the non-HTTPs version, after which they can inject their own code in your projects.

I suggest to only allow fall-back to a non-HTTPs alternative when the user explicitly indicated they allow this (through a command-line flag, dub config, etc.).

**Comment by andre2007** [comment]
Was fixed.
