### ISSUE TITLE
Server crash with build search

### ISSUE THREAD

**Issue by SrMordred** [dlang/dub#1533]
https://code.dlang.org/search?q=build

500 - Internal Server Error

Internal Server Error

Internal error information:
vibe.db.mongo.connection.MongoDriverException@../../.dub/packages/vibe-d-0.8.4/vibe-d/mongodb/vibe/db/mongo/cursor.d(304): Query failed. Does the database exist?
----------------
??:? [0xa7d1ee]
??:? [0xa9dd0a]
??:? [0xa88ad2]
exception.d:421 [0x50ea03]
exception.d:388 [0x5050dd]
cursor.d:304 [0x51ba4c]
dbcontroller.d:393 [0x51c5b3]
dbcontroller.d:253 [0x51c349]
dbcontroller.d:367 [0x539cb4]
cursor.d:233 [0x51b538]
cursor.d:60 [0x47fdd9]
iteration.d:587 [0x64c415]
array.d:134 [0x47a42e]
dbcontroller.d:325 [0x44b3e3]
registry.d:103 [0x418162]
web.d:474 [0x4180a1]
web.d:1024 [0x5c116a]
web.d:194 [0x5c0d5b]
router.d:218 [0x91635e]
router.d:674 [0x91906e]
router.d:607 [0x91602a]
router.d:211 [0x915d94]
server.d:2247 [0x91ed67]
server.d:241 [0x91d396]
server.d:233 [0x91cfd7]
server.d:2006 [0x926653]
libevent2_tcp.d:612 [0x9fd22c]
core.d:632 [0x49afcd]
core.d:1241 [0x9e3f7f]
??:? [0xa80c81]

**Comment by ohdatboi** [comment]
This is a problem with the dub registry. See dlang/dub-registry#341.
Dub searches for packages without any problems.
