### ISSUE TITLE
Overrides don't prevent downloads

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#1534]
E.g. given package containing `dependency "pyd" version="*"`
``` zsh
% dub add-override pyd '*' ~/pyd/
% dub build
Fetching pyd 0.9.9 (getting selected version)...
```

the build goes ahead with the local pyd, but for some reason a version is also downloaded from the registry.

**Comment by Geod24** [comment]
Overrides are deprecated as of https://github.com/dlang/dub/pull/2461
