### ISSUE TITLE
x86_mscoff matches x86 platform specs

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#1535]
Which means that you can't have do e.g. link to one file for optlink and one for ms linker

**Comment by s-ludwig** [comment]
Although x86_mscoff is really just a hack and we still need proper selection mechanics based on the object format (#228), the semantics are consistent with the DMD pre-defined versions. We could add another hack on top and introduce x86_omf as an intermediate solution, but it's also currently possible to use configurations to work around the issue:

```
configuration "coff" {
  platforms "windows-x86_mscoff"
  libs "mycofflib"
}
configuration "default" {
  libs "myomflib" platform="windows-x86"
}
```

This can still cause a link failure when building with "dub -a x86_mscoff -c omf" manually, but by default it will do the right thing.

**Comment by shoo** [comment]
I've seen a lot of solutions to this problem with the addition of configuration.
However, this has made configuration extremely complex and created a lot of confusion. And the confusion is compounded by multiplication if the project has libraries that it depends on.
The addition of x86_omf will alleviate some of the confusion.

**Comment by Geod24** [comment]
Upstream has removed OMF support so this is now working as expected.
