### ISSUE TITLE
Version not printed in cmd binaries out of date

### ISSUE THREAD

**Issue by Aphexus** [dlang/dub#1553]
dub --version
DUB version unknown, built on Sep  4 2018

I just built master.

Also, the binaries are out of sync, should it not be automated.  Web site says latest is 1.11 but the binaries are only 1.9.

**Comment by Geod24** [comment]
https://github.com/dlang/dub/pull/1550 will fix the version issue.
As for the binaries, I assume you mean on Windows right ? https://github.com/dlang/dub/releases

**Comment by Geod24** [comment]
Version shows correctly now, and the dub registry redirects to Github release.
