### ISSUE TITLE
Automatically add dependencies to dub,json file

### ISSUE THREAD

**Issue by aberba** [dlang/dub#1555]
Seems like the ability to install and automatically add a package to the dub.json file is missing. Similar to the NodeJS's `npm install` command. I only found `dub fetch` which does not add it to my dub.json file automatically.

**Comment by ohdatboi** [comment]
See #790 for discussion.

**Comment by ZombineDev** [comment]
`dub fetch --save <package>` is the way to go, so let's continue the discussion in #790.
