### ISSUE TITLE
dub fetch packageName:subPackageName

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1567]
Currently dub fetch only allows to specify the main package.

Therefore
```
dub fetch arsd:cgi
```
fails. Should dub fetch support packageName:subPackageName?
In this case, dub fetch could use just the packageName.

I stumbled over this issue because IntelliJ has some functionality which calls
```
dub fetch arsd:cgi
```
in the background. This of course fails.

**Comment by ohdatboi** [comment]
Sure, ignoring everything after `:` would work. It could also query registry to check if specified package has specified sub package.

**Comment by ZombineDev** [comment]
I think that dub should support fetching packages like this:
```
dub fech [user/]?package[:subpackage]?[@version]? [--from=registry-url]?
```

**Comment by andre2007** [comment]
Fixed https://github.com/dlang/dub/pull/1756
