### ISSUE TITLE
Command line argument --root and relative paths (e.g. preGenerateCommands)

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1596]
I have a small application with this dub.json
```
{
    "name": "t3",
    "preGenerateCommands": ["test.cmd"]
}
```

If I execute ```dub describe --root "t3"``` there is a warning thrown about the missing "test.cmd". Dub tries to execute ```test.cmd``` with current work dir instead of the path of --root.

Is this the expected behavior of --root or a bug?

**Comment by andre2007** [comment]
Quote from @ZombineDev 
Just like `git -C some_dir [cmd]`, `dub [cmd] --root some_dir`, should make dub behave as it has effectively done `cd some_dir`, before proceeding with the rest of its work.

**Comment by Geod24** [comment]
Tested on Linux with `test.sh`. Example didn't work because `test.sh` and `./test.sh` are two different things. Assuming `./test.sh` was meant, this is a duplicate of #1775 and is fixed in master.
