### ISSUE TITLE
Offer a standard way to query dub.json

### ISSUE THREAD

**Issue by mcandre** [dlang/dub#1603]
The jq examples on the wiki are a good start, helping users automate many tasks around dub. However, it would be better if dub offered a built-in way to obtain this information, to reduce the need for installing more external tools.

**Comment by ZombineDev** [comment]
It looks like [`dub describe`](http://code.dlang.org/docs/commandline#describe) would be a better fit for what you're trying to achieve.

**Comment by andre2007** [comment]
@mcandre dub provides a way to get specific values using parameter --data.

http://code.dlang.org/docs/commandline#describe

Please feel free to reopen this issue if there is a specific value you are missing.
