### ISSUE TITLE
Error running when compiling on Debian 32/64-bit with dmd v2.064.2

### ISSUE THREAD

**Issue by jordisayol** [dlang/dub#163]
When compiling against shared "libphobos2.so", On both 32 and 64-bit system, I got this run-time error:

```
Fatal Error while loading '/usr/lib/i386-linux-gnu/libphobos2.so.0.64':
    The module 'std.regex' is already defined in './dub'.
Segmentation fault
```

No problem if statically link.

EDIT: test with dub 0.9.19

**Comment by dhasenan** [comment]
DMD bug that was fixed three years ago. Close?
