### ISSUE TITLE
why do the new version of dub not show up on the dub download 

### ISSUE THREAD

**Issue by sxkladi** [dlang/dub#1633]
### System information

- **dub version**: (e.g. dub 1.3.0)
- **OS Platform and distribution**: (e.g. Windows 10, Linux Ubuntu 16.04)
- **compiler version** (e.g. dmd-2.074.1)

**Comment by sxkladi** [comment]
at dlang.org click on Pasckages.not you are the DUB page.
click downloads and it is at 1.11.0 , but I have not seen 1.12 . I saw it went to "release"?????. I can get 1.12
by dub fetch dub
-- and it pulls 1.12.

**Comment by Flying-Toast** [comment]
The latest version of dub should be installed automatically with dmd when you use the windows installer or the debian package.
What operating system are you using?

**Comment by wilzbach** [comment]
I think @sxkladi is confused because the downloads at code.dlang.org are no longer updated as we more or less have moved to GitHub releases (but not fully for Windows binaries yet).
See also: https://github.com/dlang/dub-registry/pull/401

**Comment by Geod24** [comment]
So should we close this ?
