### ISSUE TITLE
https://code.dlang.org/ issues

### ISSUE THREAD

**Issue by sxkladi** [dlang/dub#1634]
### System information

- **dub version**: (e.g. dub 1.3.0)
- **OS Platform and distribution**: (e.g. Windows 10, Linux Ubuntu 16.04)
- **compiler version** (e.g. dmd-2.074.1)

**Comment by sxkladi** [comment]
on the webpage --> https://code.dlang.org/
put dub in the search box and click on the search icon
and you get -->

500 - Internal Server Error

Internal Server Error

Internal error information:
vibe.db.mongo.connection.MongoDriverException@../../.dub/packages/vibe-d-0.8.4/vibe-d/mongodb/vibe/db/mongo/cursor.d(304): Query failed. Does the database exist?
----------------
??:? [0xa7d1ee]
??:? [0xa9dd0a]
??:? [0xa88ad2]
exception.d:421 [0x50ea03]
exception.d:388 [0x5050dd]
cursor.d:304 [0x51ba4c]
dbcontroller.d:393 [0x51c5b3]
dbcontroller.d:253 [0x51c349]
dbcontroller.d:367 [0x539cb4]
cursor.d:233 [0x51b538]
cursor.d:60 [0x47fdd9]
iteration.d:587 [0x64c415]
array.d:134 [0x47a42e]
dbcontroller.d:325 [0x44b3e3]
registry.d:103 [0x418162]
web.d:474 [0x4180a1]
web.d:1024 [0x5c116a]
web.d:194 [0x5c0d5b]
router.d:218 [0x91635e]
router.d:674 [0x91906e]
router.d:607 [0x91602a]
router.d:211 [0x915d94]
server.d:2247 [0x91ed67]
server.d:241 [0x91d396]
server.d:233 [0x91cfd7]
server.d:2006 [0x926653]
libevent2_tcp.d:612 [0x9fd22c]
core.d:632 [0x49afcd]
core.d:1241 [0x9e3f7f]
??:? [0xa80c81]

**Comment by Geod24** [comment]
Sounds like https://github.com/dlang/dub-registry/issues/341
The issue was fixed 7 days ago but IDK if it was deployed?

**Comment by wilzbach** [comment]
Yes it has been deployed.

https://github.com/dlang/dub-registry/pull/397

**Comment by s-ludwig** [comment]
I actually had to do a quick revert yesterday, because there was an issue due to the build machine differing with the server. I'll re-deploy later today.

**Comment by s-ludwig** [comment]
Deployed again and appears to run stable now. BTW, searching with an empty search string was not covered by the fix, but nonetheless it works for me. @sxkladi, do you still get an error now?

**Comment by s-ludwig** [comment]
Closing for now. Please reopen if this occurs again.
