### ISSUE TITLE
Add Darwin / iOS / tvOS / watchOS macros for version?

### ISSUE THREAD

**Issue by zoujiaqing** [dlang/dub#1639]
### System information

- **dub version**:  1.13.0
- **OS Platform and distribution**:  macOS
- **compiler version** : dmd-2.084.0

### Bug Description

Can't get iOS macros:

```D
version(iOS):
    // TODO
```

**Comment by andre2007** [comment]
With the example from the github issue it is now clear for me, sorry it is not related to dub but indeed a dmd enhancement request. You want a new predefined version (https://dlang.org/spec/version.html#predefined-versions).

Please file the enhancement request here https://issues.dlang.org

Kind regards
Andre
