### ISSUE TITLE
Missing passing -version to the compiler

### ISSUE THREAD

**Issue by vporton** [dlang/dub#1640]
### System information
- **dub version**: 1.8.0

### Bug Description

It is missing in DUB command line a mean to pass `-version` flag to the (DMD, for example) compiler.

**Comment by wilzbach** [comment]
It's `--version`, DMD also supports that FWIW. For traditional reasons, DMD used `-version`.

I'm closing this as invalid. If you had troubles finding `--version`, that's an issue for https://github.com/dlang/dub-docs.

**Comment by ZombineDev** [comment]
@vporton the way to specify predefined versions from Dub to any D compiler is with the `versions` build setting:

dub.json:
```json
{
    "name": "myproject",
    "versions": ["PrintfDebugging"],
    "versions-x86_64": ["UseAmd64Impl"]
}
```

dub.sdl:

```
name "myproject"

// used on all platforms
versions "PrintfDebugging"

// only used when building for X86-64
versions "UseAmd64Impl" platform="x86_64"
```

Does this answer your question?

**Comment by vporton** [comment]
In my opinion, this should be also doable with command line switches. However I am not sure.

**Comment by ZombineDev** [comment]
Doing this from the command-line is not supported, as the intention is that all build settings should be defined in `dub.sdl` / `dub.json` so the build can be reproducible. Otherwise, if a project may require a version to defined, you won't able to build it without reading the source code.

Usually, if you want to have different kinds of builds that enable disable `version`-ed blocks of code is to define different dub configurations - see https://dub.pm/package-format-sdl.html#configurations

**Comment by ZombineDev** [comment]
> Doing this from the command-line is not supported

I'm not saying that a feature request would not be accepted, but before that we need to be sure that this can't be accomplished with existing features and that it can't be worked around in a reasonable way.

**Comment by s-ludwig** [comment]
I think at some point we should complement "configurations" with additive "features" that operate like versions, but on the package level (see also https://github.com/dlang/dub/issues/128#issuecomment-25602418). Optional dependencies can work as a replacement up to a certain degree.

**Comment by ZombineDev** [comment]
@s-ludwig if I understand you correctly, I think the way to go is with nested configurations, e.g.

```
configuration "windows-native" {
    platforms "windows"
    targetType "executable"
    configuration "uwp-app" {
        versions "UWPApp"
        libs "d3d11"
    }
    configuration "desktop-app" {
        versions "Win32App"
        libs "d3d9"
    }
}
configuration "glut-app" {
	// works on any platform
	targetType "executable"
	versions "GlutApp"
}
```

```
dub build --config="windows-native.uwp-app"
```

This way the issue with multiple competing `excludedSourceFiles` definitions having effect would be solved in a natural way.

**Comment by ZombineDev** [comment]
Though, I'm sure if such a feature would be relevant to @vporton. So let's continue the discussion in #128.
