### ISSUE TITLE
How to work use --parallel for build?

### ISSUE THREAD

**Issue by hanfengfg** [dlang/dub#1642]
for --parallel:
```sh

hanfengyang@debian:~/passport$ time dub build -v -f --parallel

...

real	0m55.981s
user	0m50.916s
sys	0m5.008s

```

no --parallel:
```sh

hanfengyang@debian:~/passport$ time dub build -v -f

...

real	0m55.081s
user	0m50.616s
sys	0m5.008s

```

OS： debian 9
CPU: i9-9900K 16Core
DISK: SUMSANG 970 PRO
RAM: DDR4-3000 16G

**Comment by Basile-z** [comment]
`--parallel` only has an effect with incremental compilation.

try 

```bash
time dub build -f --build-mode=singleFile
time dub build -f --build-mode=singleFile --parallel
```

to see the difference. Each module is compiled to an object so that the compiler can executed several times on different cores.

As this issue seemed to be a question, don't forget to close if the answer is satisfying.

**Comment by WebFreak001** [comment]
I think there isn't a lot else to say.

See also docs:
```
--parallel        Runs multiple compiler instances in parallel, if possible.
```

and src, which only works in singleFile mode as mentioned: (only usage of parallel)
https://github.com/dlang/dub/blob/c707c032591d4506d7087bc160819bd8f7ee0bb9/source/dub/generators/build.d#L467-L469
