### ISSUE TITLE
Unable to set targetPath for documentation

### ISSUE THREAD

**Issue by uranuz** [dlang/dub#1644]
When I create documentation using dub via:
dub --build=docs
I am unable to change output folder for documentation, because it is hardcoded there (for DMD compiler):
dub/source/dub/compilers/dmd.d:52
Attemp to set this option manualy via `dflags` gives nothing, because in this case dub puts two `-Dd` options in the command line. I had a look at this using `-v` option for dub, so it is not just my guess. First 
`-Dd` option is my custom option taken from `dlags` and other is hardcoded option `-Dd`, that is inserted by dub. And I think that second option takes precendence by `dmd` compiler, because it goes last.

Could you consider to make able to set documentation output folder via `dflags` or `targetPath` option (or maybe even both options).
Maybe I could even make PR myself, but I think that it will take "5 minutes" for person who knows the "dub" internals.

**Comment by uranuz** [comment]
I have already read dud documentation. And I failed to find appropriate
option to set docs path. So I just added command to post build option that
replaces docs in the folder I need.

2 февр. 2019 г. 22:27 пользователь "andre2007" <notifications@github.com>
написал:

If I am not completely wrong, the coding you mentioned just says what the
default value for build type docs should be.
In your dub.json / dub.sdl file you are able to customize the default
values for the build types.
See an example at the very end of this page
https://dub.pm/package-format-json

Please give feedback when this solves your issue:)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dlang/dub/issues/1644#issuecomment-459992195>, or mute
the thread

**Comment by andre2007** [comment]
Currently I cannot try out, but s.th. like this should work

```
"buildTypes": {
		"docs": {
			"buildOptions": ["syntaxOnly"],
                        "dflags": ["-c", "-Ddmyfolder"]
		}
  }
```

**Comment by andre2007** [comment]
I close this issue because it should work with buildTypes. Please reopen if you still have an issue.

**Comment by uranuz** [comment]
Okay. Thanks for response

пт, 8 февр. 2019 г., 20:31 andre2007 notifications@github.com:
