### ISSUE TITLE
the DFLAGS env variable is not handled when `--build` is passed

### ISSUE THREAD

**Issue by ghost** [dlang/dub#1645]
### System information

- **dub version**:  1.13.0
- **OS Platform and distribution**: Linux Fedora 28, x86_64
- **compiler version**  dmd-2.084.0

### Bug Description

The environment variables like DFLAGS are not passed to the compiler when `--build` is passed to dub

### How to reproduce?

Let's use a simple d program for that:

```d
void main(string[] args)
{
    string[string] env;
    env["DFLAGS"] = "-StopCompilingBecauseThisSwitchIsInvalidAndSomwhatLooooongish";
    execute(["git", "clone", "https://github.com/Basile-z/styx.git"]);
    // this one return 0...
    writeln(execute(["dub", "build", "--config=library", "--build=debug"], env, Config.none, size_t.max, "./styx"));
    // this one return 2...
    writeln(execute(["dub", "build", "--config=library", ], env, Config.none, size_t.max, "./styx"));
}  
```

### Expected Behavior

The first `execute` should return 2.

**Comment by vporton** [comment]
It looks like for me that the fix is very simple:

```diff
diff --git a/source/dub/package_.d b/source/dub/package_.d
index 1c1858e..8128ceb 100644
--- a/source/dub/package_.d
+++ b/source/dub/package_.d
@@ -401,12 +401,9 @@ class Package {
        */
        void addBuildTypeSettings(ref BuildSettings settings, in BuildPlatform platform, string build_type)
        const {
-               if (build_type == "$DFLAGS") {
-                       import std.process;
-                       string dflags = environment.get("DFLAGS");
-                       settings.addDFlags(dflags.split());
-                       return;
-               }
+               import std.process;
+               string dflags = environment.get("DFLAGS", "");
+               settings.addDFlags(dflags.split());

                if (auto pbt = build_type in m_info.buildTypes) {
                        logDiagnostic("Using custom build type '%s'.", build_type);
```

I've successfully compiled the patched version, but didn't test it.

**Comment by Basile-z** [comment]
You have to propose this to the dub repository. I'm not implied in the project.

**Comment by WebFreak001** [comment]
when the DFLAGS environment variable is specified it switches to a special build mode called "DFLAGS", which is only used when not overriden

According to the docs the DFLAGS should be stronger though:

> --build=<value> | Specifies the type of build to perform. Note that setting the DFLAGS environment variable will override the build type with custom flags. Possible names:     debug (default), plain, release, release-debug, release-nobounds, unittest, profile, profile-gc, docs, ddox, cov, unittest-cov, syntax and custom types

https://github.com/dlang/dub/blob/706123cd20e7a232a9fa99c80544802a9808ada4/source/dub/commandline.d#L666-L669

I think this was probably added to avoid conflicts in DFLAGS when there is an environment variable but it's overriden with the argument.

Changing it _might_ break stuff expecting DFLAGS to be overriden. Not sure what the best solution would be here

**Comment by Geod24** [comment]
https://github.com/dlang/dub/pull/1648
