### ISSUE TITLE
Infinite recursion when invoking dub

### ISSUE THREAD

**Issue by vporton** [dlang/dub#1647]
### System information

- **dub version**: dub 1.13.0+commit.21.g927c5e6
- **OS Platform and distribution**: Linux Ubuntu 18.10
- **compiler version** dmd-v2.080.1

### Bug Description

When invoking `dub` in DUB source directory, it stucks in infinite recursion:

```
Running ./bin/dub 
Performing "debug" build using dmd for x86_64.
dub 1.13.0+commit.21.g927c5e6: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./bin/dub 
Performing "debug" build using dmd for x86_64.
dub 1.13.0+commit.21.g927c5e6: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./bin/dub 
```

There should be invented some way to eliminate this silly behaviour. Maybe by setting env var `DUB_DEVELOPMENT`.

**Comment by wilzbach** [comment]
You can use `dub build` or `./build.sh` for all practical purposes.

**Comment by WebFreak001** [comment]
not a bug imo, `dub` runs `dub` which in turn runs `dub` which of course makes this infinite cycle happen, however adding an edge case for this seems unneccessary.

Dub finished with the build and is running dub after it finished compiling, so I think it's fine how it is.

**Comment by Geod24** [comment]
Agree, it's not a dub bug, and the addition of the edge case is just not worth it

**Comment by bachmeil** [comment]
This issue has been inactive for five months. The feedback provided has been against treating this as a bug. Looks to me like it should be closed.
