### ISSUE TITLE
 Error: static assert:  isValidVersion("unknown") is false

### ISSUE THREAD

**Issue by Aphexus** [dlang/dub#1657]
downloaded dub, ran build:

Generating version file...
fatal: not a git repository (or any of the parent directories): .git
Executing dmd...
Serializing composite type BuildRequirements which has no serializable fields
Serializing composite type BuildOptions which has no serializable fields
source\dub\package_.d(653): Error: static assert:  isValidVersion("unknown") is false

dmd 2.084. 

If I do

bool isValidVersion(string ver)
pure @nogc {
	return true;

then

Generating version file...
fatal: not a git repository (or any of the parent directories): .git
Executing dmd...
source\dub\semver.d(32): Warning: statement is not reachable
source\dub\semver.d(35): Warning: statement is not reachable
source\dub\semver.d(36): Warning: statement is not reachable
source\dub\semver.d(37): Warning: statement is not reachable
source\dub\semver.d(38): Warning: statement is not reachable
source\dub\semver.d(41): Warning: statement is not reachable
source\dub\semver.d(42): Warning: statement is not reachable
source\dub\semver.d(43): Warning: statement is not reachable
source\dub\semver.d(44): Warning: statement is not reachable
source\dub\semver.d(47): Warning: statement is not reachable
source\dub\semver.d(48): Warning: statement is not reachable
source\dub\semver.d(49): Warning: statement is not reachable
source\dub\semver.d(50): Warning: statement is not reachable
source\dub\semver.d(53): Warning: statement is not reachable
source\dub\semver.d(62): Warning: statement is not reachable
source\dub\semver.d(68): Warning: statement is not reachable
source\dub\semver.d(69): Warning: statement is not reachable
Serializing composite type BuildRequirements which has no serializable fields
Serializing composite type BuildOptions which has no serializable fields

but no exe is generated.

**Comment by Aphexus** [comment]
Trying to build latest since it doesn't seem to exist anywhere.

**Comment by severinstojanovic** [comment]
Try by actually cloning the git repo rather than just directly downloading the source from the releases page:

1) git clone https://github.com/dlang/dub/
2) cd dub
3) build

**Comment by Geod24** [comment]
This happens because you downloaded the source.
There are multiple ways to work around this:
- `git clone` the repository
- Provide `GITVER` explicitly, e.g. `GITVER=1.18.0-dirty ./build.sh`

There is a PR for a new build script that will be more verbose about this error: https://github.com/dlang/dub/pull/1821
