### ISSUE TITLE
The dependency resolution process is taking too long.

### ISSUE THREAD

**Issue by aaronstanek** [dlang/dub#1672]
# Trying to compile a DUB project

## Received the following error message:

The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.

## The contents of dub.json:

{
	"name": "vibe_test",
	"authors": [
		"Aaron"
	],
	"dependencies": {
		"vibe-d": "~>0.8.2"
	},
	"description": "A simple vibe.d server application.",
	"copyright": "Copyright © 2019, Aaron",
	"license": "proprietary"
}

## Debugging Info:

DUB version 1.8.0-2
Ubuntu 18
Compiling the DUB project with LDC2
I am compiling the default application which is created with a new vibe.d project. This project compiled correctly one this machine about a month ago, using the same setup and parameters.

**Comment by andre2007** [comment]
It seems you are using a quite old dub version. In the meantime there  were quite some changes in this area. Could you retry with a more recent version of dub  (ldc)?

**Comment by wilzbach** [comment]
For reference, you can go to https://dlang.org/install for instructions on how to use the install the latest stable release of DMD or LDC. The latest stable release of dub is 1.14

**Comment by aaronstanek** [comment]
Updating DUB solved the problem.
Thank you.
