### ISSUE TITLE
Create .dub directory in `dub generate visuald` if not exists

### ISSUE THREAD

**Issue by enjoysmath** [dlang/dub#1673]
c:\Users\FruitfulApproach\Desktop\dlang\myproject>dub generate visuald
Cannot open file `.dub\myproject.visualdproj' in mode `wb' (No such file or directory)

After doing 'dub init myproject' in parent dir.

So how can we get this to work?  No .dub folder is generated.

**Comment by p0nce** [comment]
(work-around) Perhaps try to type `dub build` before `dub generate visuald`

**Comment by WebFreak001** [comment]
this doesn't seem to happen on every project (I couldn't make it break with a vibe.d project after deleting .dub) but when it's run in a freshly created project it's easily reproducible

**Comment by Imperatorn** [comment]
dub needs some love

**Comment by Geod24** [comment]
Fixed
