### ISSUE TITLE
Regression: Range violation

### ISSUE THREAD

**Issue by jacob-carlborg** [dlang/dub#1681]
### System information

- Dub version: 1.15.0-beta.1+2-g3936dbf
- Platform: macOS
- DMD version: 2.085.1

### Bug Description

When executing Dub in a certain way using `spawnProcess` I get a Range violation error.

### How to reproduce?

1. Create a Dub project with the following content:

dub.json:

```json
{
    "name": "foo",
    "targetType": "executable",

    "configurations": [
        {
            "name": "unittest",
            "mainSourceFile": "test.d"
        },
    ],
}
```

test.d:

```d
void main()
{
    import std.process : spawnProcess, wait;
    spawnProcess(["/full/path/to/dub", "build", "--vverbose", ""]).wait();
}
```

2. Execute `dub test`

Replace `/full/path/to/dub` with the full path to the Dub executable. The issue here is the third empty argument. This is what's causing the range violation. I assume when Dub is normally executed from the shell no trailing empty argument will be passed through, even if trailing whitespace is added when executing the Dub command.

### Logs

Verbose output of Dub executed through `spawnProcess`:

```
Range violation
Full exception: core.exception.RangeError@source/dub/commandline.d(2225): Range violation
----------------
??:? _d_arrayboundsp [0x533717d]
~/.dvm/compilers/dmd-2.085.1/osx/bin/../../src/druntime/import/object.d:342 pure nothrow @safe dub.commandline.splitPackageName(immutable(char)[]).PackageAndVersion dub.commandline.splitPackageName(immutable(char)[]) [0x512bdf6]
~/.dvm/compilers/dmd-2.085.1/osx/bin/../../src/druntime/import/object.d:342 int dub.commandline.BuildCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) [0x5123e1f]
~/.dvm/compilers/dmd-2.085.1/osx/bin/../../src/druntime/import/object.d:342 int dub.commandline.runDubCommandLine(immutable(char)[][]) [0x511fba2]
source/app.d:14 _Dmain [0x5113b6f]
```

**Comment by John-Colvin** [comment]
Just running `dub build ""` from bash is enough to trigger this for me.

**Comment by John-Colvin** [comment]
For people looking for a workaround in their bash scripts with optional arguments to dub, use the `${var:+"$var"}` syntax to truly expand to nothing if `var` is not defined.

**Comment by jacob-carlborg** [comment]
> Just running `dub build ""` from bash is enough to trigger this for me.

Yeah, I can reproduce it like that as well.

**Comment by MartinNowak** [comment]
See https://github.com/dlang/dub/pull/1684
