### ISSUE TITLE
dub init hangs on Windows on Git Bash

### ISSUE THREAD

**Issue by carun** [dlang/dub#1682]
### System information
- **dub version**: dub 1.11.0
- **OS Platform and distribution**: Windows 10
- **compiler version** dmd-2.085.1

### Bug Description
`dub init` hangs when run from Git bash, but works fine when run from `cmd.exe`

### How to reproduce?
1. Create a new directory and navigate to it.
2. Right click, Git Bash here.
3. Run `dub init`, it will not print anything on the screen and you will be waiting forever for it to complete. It is waiting there for the user input.
4. Alternatively, if you press enter key 7 times, all the defaults will be accepted and the project will be created.

### Expected Behavior
It should print something on the screen and should accept user input via git bash.
![dub-init-git-bash](https://user-images.githubusercontent.com/471374/56531805-7e532500-6509-11e9-8856-f91166ed5d2b.gif)

**Comment by Flying-Toast** [comment]
Thanks for reporting this.
I will look into it later today.

**Comment by Geod24** [comment]
Any chance you could test this with master ? I believe https://github.com/dlang/dub/pull/1841 might have solved it.

```console
$ git clone https://github.com/dlang/dub.git
$ cd dub
$ dub build
$ ./bin/dub init issue1682
```

**Comment by Geod24** [comment]
The fix is now part of a release (dub 1.20.0), which might make it easier for you to test it @carun

**Comment by carun** [comment]
While I tried to download latest dub to test, I noticed that https://code.dlang.org/download points to a very old version of dub. Not sure who will update this page with the latest dub details, albeit the latest dub can be fetched with dmd and ldc2.

**Comment by Geod24** [comment]
Thanks! Opened https://github.com/dlang/dub-docs/issues/24
In the meantime you can find the latest version packaged with DMD / LDC or download it from https://github.com/dlang/dub/releases/tag/v1.20.0

**Comment by carun** [comment]
@Geod24 thanks for the link. I confirm that it's been fixed.

![image](https://user-images.githubusercontent.com/471374/77966062-313e0e00-7297-11ea-9c1e-cb52e7b8ca8d.png)
