### ISSUE TITLE
Generating Hunt Framework Project via: dub init 

### ISSUE THREAD

**Issue by BoQsc** [dlang/dub#1698]
### System information

- **dub version**: DUB version 1.15.0, built on May  4 2019
- **OS Platform and distribution**: Windows 10
- **compiler version** DMD32 D Compiler v2.086.0

### Bug Description
I tried to create a new project based on Hunt Framework
```
C:\Users\Juozas\Desktop\Naujas aplankas>dub init helloworld2 --type=hunt
hunt is not present, getting and storing it user wide
Fetching hunt 1.2.0...
Sub package "hunt:init-exec" doesn't exist.
```
And dub couldn't create it, Hunt Framework author said he has no idea how Dub works.
https://github.com/huntlabs/hunt-framework/issues/130

### How to reproduce?

- Simply install DMD and use command `dub init helloworld2 --type=hunt`
- See that `Sub package "hunt:init-exec" doesn't exist.` and only these two files are generated:
  - dub.json
  - .gitignore

### Expected Behavior
Successful generation of basic Hunt Framework project.

**Comment by Geod24** [comment]
The error message is: `Sub package "hunt:init-exec" doesn't exist.`
This is because, in order in init a certain package "type", said package have to provide an `init-exec` sub-package, which hunt does not.

**Comment by andre2007** [comment]
Exactly, Hunt developers needs to add this sub package of type executable. This executable has the task to create the skeleton files like app.d. The executable is executed while you execute dub init....

Example can be found here
https://github.com/dlang/dub/blob/master/test/issue1651-custom-dub-init-type/custom-dub-init-dubpackage-1.0.1.zip
