### ISSUE TITLE
Profiling disabled for LDC2?

### ISSUE THREAD

**Issue by denizzzka** [dlang/dub#1701]
### System information

- **dub version**: DUB version 1.15.0, built on May  4 2019
- **OS Platform and distribution**: Linux Debian
- **compiler version**: latest ldc2

### Bug Description
dub build -profile is not emits cli command for ldc2 to generate profiling code

### How to reproduce?
```
dub run --compiler=/home/denizzz/ldc2-1.16.0-beta1-linux-x86_64/bin/ldc2 --build=profile
```

### Expected Behavior
Some profiling data files generated after dub run exit

**Comment by kinke** [comment]
Resolved by #1755.
