### ISSUE TITLE
dub 1.15.0 behavior change (error) for '$?' in build commands

### ISSUE THREAD

**Issue by jondegenhardt** [dlang/dub#1709]
### System information
- **dub version**: Behavior change 1.14.0 -> 1.15.0
- **OS Platform and distribution**: MacOS, Ubuntu
- **compiler version**: Behavior change, dub w/ dmd|ldc 2.085 -> 2.086

### Bug Description

Using `$?` in build commands to check command exit status works in `dub-1.14.0`, but fails in `dub-1.15.0`. In `dub-1.15.0` it needs to be written as `$$?`. This form fails in `dub-1.14.0`.

The new behavior in `dub-1.15.0` is probably more correct, but makes it difficult to check command exit status in a way that is portable across `dub` versions. In addition, the error message was not very informative (see below). This problem was encountered in small performance test app, see the `dub.json` in this repo: [dcat-perf](https://github.com/jondegenhardt/dcat-perf).

The behavior change is likely from PR #1641.

### How to reproduce?

A reduced `dub.json` file that works `dub-1.14.0`:
```
{
    "name"         : "simple",
    "description"  : "Simple.",
    "authors"      : ["NA"],
    "copyright"    : "NA",
    "license"      : "BSL-1.0",
    "buildTypes" : {
        "custom-test" : {
            "postBuildCommands" : [
                "echo Hello; if [ $? -eq 0 ]; then echo Pass; else echo Fail; fi"
            ]
        }
    }
}
```

This fails if run with `dub-1.15.0`:
```
$ dub --version
DUB version 1.15.0, built on May  9 2019

$ dub build --build=custom-test
uncaught exception
object.Exception@source/dub/project.d(1361): Invalid variable:
----------------
project.d:1361 immutable(char)[] dub.project.getVariable!(dub.project.Project, dub.package_.Package).getVariable(immutable(char)[], const(dub.project.Project), const(dub.package_.Package), const(dub.generators.generator.GeneratorSettings)) [0x101a053bb]
```

Changing the `$?` to `$$?` works in `dub-1.15.0`, but fails in `dub-1.14.0`:
```
$ ./dub-1.14.0 --version
DUB version 1.14.0, built on Mar  1 2019

$ ./dub-1.14.0 build --build=custom-test
Performing "custom-test" build using /XYZ/dmd2-2.085.0/osx/bin/dmd for x86_64.
simple ~master: building configuration "application"...
Linking...
Running post-build commands...
Hello
/bin/sh: line 0: [: 50602?: integer expression expected
Fail
```

**Comment by WebFreak001** [comment]
fixing this by allowing `$?` should also allow `$!` and `$$` IMO, but `$$` is already used to escape the `$` so that wouldn't really work

**Comment by Geod24** [comment]
Sorry for this @jondegenhardt 

One way I could see working around this is to use an external script.
There's also the `rdmd --eval` road that [`vibe-d:tls` took](https://github.com/vibe-d/vibe.d/blob/3d0558e286ef89232e277c24332d12c30de02af0/tls/dub.sdl#L29-L66) if you want to use D instead of bash.

I don't really see an actionable item to fix though. Restoring the previous behavior would restore the bug, and there's no easy way to make the transition on `dub` side. Having it reported here ensure anyone else hitting this can find the solution to make it portable.

**Comment by Geod24** [comment]
Ping @jondegenhardt : Are you fine with closing this ?

**Comment by jondegenhardt** [comment]
Sure, feel free to close. I can work around it.
