### ISSUE TITLE
The dependency resolution process is taking too long.

### ISSUE THREAD

**Issue by freddiehonohan** [dlang/dub#1712]
> The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.

Just filing this report regarding: 	"selenium-d": "~>0.1.0"

Thanks!

**Comment by wilzbach** [comment]
What version of dub are you using?

**Comment by freddiehonohan** [comment]
DUB version 1.8.0-2, built on Mar 27 2018

However, I re-tried and it went through, I forgot I was running an intensive grep in the background (although it may not have been that).

Thanks, maybe I should upgrade anyway
