### ISSUE TITLE
buildtypes: If none is matched issue an error and don't build

### ISSUE THREAD

**Issue by Robert-M-Muench** [dlang/dub#1717]
I faced "unresolved external" linker errors and was wondering what's up. After messing around for quite some time, I found out that I had a typo in the buildtype to use.

To avoid this, dub should terminate with an error message: "given buildtype <buildtype> unknown".

**Comment by WebFreak001** [comment]
buildType none and sourceLibrary are unbuildable, please share a reproduction test case if you found a case where they are.
