### ISSUE TITLE
There should be a way to create several executables/libraries

### ISSUE THREAD

**Issue by vporton** [dlang/dub#1726]
There should be a way to create several executables/libraries from a single DUB config file.

Yes, it can be done with several `DUB` files and a shell/make script, but:

1. It is not compatible with existing D IDEs like Dexed to use a shell script.
2. It requires to set such things as compilation flags individually for each project, duplicate description of sources, libraries, dependencies, etc.
3. It requires to reconfigure every project separately.
4. It multiplies the number of compilation configurations which are shown in a IDE.
5. It requires to do something like a Makefile manually to specify dependencies between these libs.

These these items together are a quite serious problem.

**Comment by Geod24** [comment]
You can have subpackages, which each build an executable and a dependency on all of them at the top to build them all at once.
My common use case is having tools in a library and I usually end up with [this](https://github.com/bpfkorea/keytools/blob/ed4fbfd1e3b68ad25cc75b2fe3cd6670449f1273/dub.json#L6-L31)

**Comment by andre2007** [comment]
@vporton does the solution proposed by @Geod24 solve your problem?

**Comment by vporton** [comment]
@andre2007 Yes. Well, almost: It does not work in Dexed IDE yet.

**Comment by andre2007** [comment]
@vporton is my understanding correct and this is feature request for Dexed IDE? Then we close this issue.

**Comment by vporton** [comment]
@andre2007 Initially I thought this feature is missing in DUB at all. Now I know DUB does support it, but Dexed doesn't. I'm closing.

**Comment by andre2007** [comment]
I just wanted to have a look at Dexed IDE and it seems the repository was deleted.

**Comment by vporton** [comment]
Weird, not idea why `Basile-z` GitHub user was deleted.
