### ISSUE TITLE
dub run (repository search) does not work with sub packages

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1734]
Recently the automatic search within the repositories was added when package is not available locally for command ```dub run package```.

If a sub package is specified, the repository search is not working.
Example:
```dub run dls:bootstrap```
(Installing D Language server https://github.com/d-language-server/dls)

**Comment by BoQsc** [comment]
https://github.com/buggins/dlangui/issues/594

```
```

**Comment by wilzbach** [comment]
Fixed by https://github.com/dlang/dub/issues/1756
