### ISSUE TITLE
dub settings file in project directory

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1739]
For CI scenarios I want to be able to have the [dub settings file](https://dub.pm/settings.html) within the project folder. The project will be moved to various build servers which either directly access the dub project or compile it within Docker containers. 
Here I need to specify e.g. the dub code registry (which is in not case code.dlang.org). Beeing able to define these properties in dub.settings file which is shipped together with the projects would be highly beneficial.

Pip e.g. allow this with the ```pip.conf``` file within the project folder.

The name is tricky, as dub.json is already in use by the project descriptor.
Should we just name it ```settings.json``` also within the project folder?

**Comment by WebFreak001** [comment]
how would this work with dependencies? Like a dependency specifying it compiles with ldc

**Comment by andre2007** [comment]
Only the dub.settings.json of the actual project to be build is respected.

In dub.settings.json you can specify e.g. the default compiler. In dub.json you can define that it can only be build with a specific compiler/version. If it doesn't fit, an error is thrown. 

Also please see the pr https://github.com/dlang/dub/pull/1740

**Comment by andre2007** [comment]
Merged.
