### ISSUE TITLE
Logotype Design

### ISSUE THREAD

**Issue by zuurw** [dlang/dub#1747]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by wilzbach** [comment]
Hi thanks a lot for your interest!

We already have a more or less well-established icon, but if you're interested to engage with the community about potential replacements, the best way to go about this would be to start a discussion on general at forum.dlang.org as this affects the wider community.

Thanks a lot again for trying to make dub better (:
