### ISSUE TITLE
dub run picks an outdated package version

### ISSUE THREAD

**Issue by rtbo** [dlang/dub#1751]
It should be possible to specify a package version when running `dub run <package>`.
I use this in random directories (not in a dub project dir) to run executables from `~/.dub/packages`, but dub tends to pick old package version.
It would be nice to pick a specific version, and to default to the latest one.

**Comment by andre2007** [comment]
@rtbo for reproducing the issue. For which package, dub is using an old version? Which old version do you have and which recent version do you have?

**Comment by wilzbach** [comment]
You can do so with `dub run myapp@1.2.3` or `dub run myapp=1.2.3`

**Comment by rtbo** [comment]
@andre2007 `wayland:scanner-0.1.3` vs `wayland:scanner-0.2.0`
@wilzbach good to know! This solves the main issue.

**Comment by wilzbach** [comment]
Well, regarding outdated version, dub used to check the dub registry once a day in the past, but people complained heavily about this as it slowed down their build. So any strategy would need to be a bit more sophisticated and never ever block the main thread.
Also, you don't want to arbitrary download new versions without asking the user as they could potentially have bugs, breaking changes or even security problems. So I don't think we can do here more than an outdated warning.

**Comment by rtbo** [comment]
here dub picked the old one, even though a newer one was already in `~./dub/packages`

**Comment by rtbo** [comment]
> You can do so with dub run myapp@1.2.3 or dub run myapp=1.2.3

doesn't seem to work with subpackages:
```
$ dub run wayland:scanner@0.1.3 -- -h
Package wayland:scanner not found for registry at https://code.dlang.org/ (fallbacks registry at https://code-mirror.dlang.io/, registry at https://dub-registry.herokuapp.com/): (1): Error: Got .wayland:scanner of type undefined, expected object.
No package wayland:scanner was found matching the dependency 0.1.3
```

**Comment by wilzbach** [comment]
Do you have both versions installed?

**Comment by rtbo** [comment]
```
$ ls ~/.dub/packages
... wayland-0.1.3 wayland-0.2.0 ...
$ dub run wayland:scanner -- -h
Building package wayland:scanner in /home/remi/.dub/packages/wayland-0.1.3/wayland/scanner/
...
```
Even more weird:
```
$ dub run wayland@0.2.0
Fetching wayland 0.2.0...
Building package wayland in /home/remi/.dub/packages/wayland-0.1.3/wayland/
Package with target type "none" must have dependencies to build.
```
(fetching the new one but building the old one)

**Comment by rtbo** [comment]
BTW
```
$ dub --version
DUB version 1.16.0, built on Jul 02 2019
```

**Comment by shoo** [comment]
I also took this bug, too.
Although it may be misguided, I think it is caused by the following points.

https://github.com/dlang/dub/blob/f54b85305ff0f44f5cb115acdada2395f9606edc/source/dub/commandline.d#L713

It seems that the result, the package version indicated by the first path on the file system is picked.

**Comment by Geod24** [comment]
This is an issue for `unit-threaded`.

The README of `unit-threaded` [recommends](https://github.com/atilaneves/unit-threaded#quick-start-with-dub) to call `dub run`, but it might not run the same version that the user has as a dependency on.

**Comment by Geod24** [comment]
This has been fixed.
