### ISSUE TITLE
dub interprets module statements in ddoc as real module statements

### ISSUE THREAD

**Issue by joseph-wakeling-frequenz** [dlang/dub#1761]
### System information

- **dub version**: 1.16.0
- **OS Platform and distribution**: Ubuntu 18.04
- **compiler version**: irrelevant, but DMD 2.087.1

### Bug Description

The issue seems to arise in the following circumstances:

* a module contains a ddoc block with a code example that includes a `module` statement
* that ddoc block comes before the real `module` declaration

In this case DUB seems to interpret the code-example `module` statement as an actual `module` declaration.  If such a ddoc block occurs _after_ the real module declaration, DUB has no problems.

This was observed in the wild in sociomantic/dunnhumby's `ocean` library, and is a blocker to using that project with DUB: https://github.com/sociomantic-tsunami/ocean/issues/716

### How to reproduce?

The following minimal example exposes the bug:

```D
/*******************************************************************************

    The `module` statement in this code example is interpreted by DUB
    as a real module declaration

    ---------------
    module sometest;

    void main ()
    {
        assert(2.add(2) == 4);
    }
    ---------------

*******************************************************************************/

module fakemath;

int add (int a, int b)
{
    return a + b;
}

unittest
{
    assert(2.add(2) == 4);
}
```

Simply `dub test` on a project including this module, and there should be an error:

```
Error: module `sometest` is in file 'sometest.d' which cannot be read
```

If we instead place the ddoc block _after_ the real `module` statement, unittests run fine:

```D
module fakemath;

/*******************************************************************************

    This should be fine because it comes after the real `module` statement

    ---------------
    module sometest;

    void main ()
    {
        assert(2.add(2) == 4);
    }
    ---------------

*******************************************************************************/

int add (int a, int b)
{
    return a + b;
}

unittest
{
    assert(2.add(2) == 4);
}
```

### Expected Behavior

DUB should ignore comments and ddoc blocks when trying to identify `module` statements.

**Comment by John-Colvin** [comment]
What is the file layout and the dub.sdl in the minimal example you have
created?

Regards,
John Colvin

**Comment by andre2007** [comment]
Is the issue maybe related to the regex in this function?
https://github.com/dlang/dub/blob/bb84252948a2184f32458b993c1c7da32475511f/source/dub/internal/utils.d#L705

**Comment by joseph-wakeling-frequenz** [comment]
> What is the file layout and the dub.sdl in the minimal example you have created?

`dub.json`:

```json
{
    "name": "dub-module-bug",
    "targetType": "sourceLibrary"
}
```

... and the `fakemath.d` file is placed in `source`.  Nothing else.

**Comment by joseph-wakeling-frequenz** [comment]
> Is the issue maybe related to the regex in this function?

That confirms what I suspected, which is that the search for module name is just searching for the first `module something` statement in the file, ignoring the context.

That's clearly a problematic way to do it.  DUB can't rely on a pure text search here, it needs to understand clearly what is a `module` _statement_ (in the same sense that the D frontend would understand) and what is not.

**Comment by andre2007** [comment]
Bug fix implemented.
