### ISSUE TITLE
dub fetch: Where are the downloaded packages placed?

### ISSUE THREAD

**Issue by BoQsc** [dlang/dub#1771]
This applies to both Linux and Windows 10.

I would like to know the directories where is the package placed after it is downloaded/fetched via the command: ` dub run dlangui:example1`

**Comment by BoQsc** [comment]
**For Linux systems** `dlangui:example1` is placed here:
`/home/yourusername/.dub/packages/dlangui-0.9.182/dlangui/examples/example1`

**Comment by Geod24** [comment]
Windows: `%APPDATA%/dub` IIRC.
If not, check the path mentioned here: https://dub.pm/settings.html

**Comment by BoQsc** [comment]
**For Windows 7 8 10 systems** `dlangui:example1` is placed here:

The default dub fetch directory:
<code>C:\Users<b>\username</b>\AppData\Local\dub\packages\dlangui-0.9.182\dlangui\examples\example1</code>

**username** - a user 's username on Windows 7 8 10 machine. You need to change it to the one that is available on your Windows 7 8 10 machine.
