### ISSUE TITLE
Add command dub lint

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1773]
Similiar to dustmite, D-Scanner command could be added to dub. Something like

```dub lint```

- If D-Scanner package is not available it will be fetched and built
- dub upgrade is executed to fetch  all dependencies
- DRuntime and Phobos include paths are detected and added as include argument
- importPaths of all dependent packages are added as include argument
- Execute D-Scanner with project folder as base path for all source files

**Comment by andre2007** [comment]
PR https://github.com/dlang/dub/pull/1774

**Comment by belka-ew** [comment]
Fixed?

**Comment by andre2007** [comment]
Yes, thanks.
