### ISSUE TITLE
Wrong Windows binaries in GitHub releases

### ISSUE THREAD

**Issue by GoaLitiuM** [dlang/dub#1795]
All the x86 and x86_64 releases for Windows dating all the way back to 1.14.0 do not run on Windows machines because they are actually Linux binaries.

**Comment by Geod24** [comment]
Confirmed with v1.18.0:
```console
file ~/Downloads/dub.exe
/Users/geod24/Downloads/dub.exe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=c08f0a5898d0c533ce27c85d7fefafbded071b6c, with debug_info, not stripped
```

**Comment by saaadel** [comment]
same for newer versions:
dub-v1.18.0-windows-x86 
dub-v1.18.0-windows-x86_64 
dub-v1.19.0-beta.1-windows-x86 
dub-v1.19.0-beta.1-windows-x86_64

**Comment by ZHANITEST** [comment]
Can't use `dub`-#1795 and can't build `DUB`-#1657 on Windows now.
Only `v1.15` work now what come with on dmd installer for Windows.

I hope it will be resolved soon 😢

**Comment by wilzbach** [comment]
@ZHANITEST you should be able to use the dub binary bundled/installed with either your DMD or LDC release. This issue only affects the manual installation of dub for Windows.

**Comment by Geod24** [comment]
https://github.com/dlang/dub/releases/tag/v1.20.0

Problem fixed.
