### ISSUE TITLE
Unnecessary rebuild of single file dub packages

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1809]
In case of single file dub packages, there are 2 bugs in isUpToDate:

This will add the string "." to allfiles 
https://github.com/dlang/dub/blob/f54b85305ff0f44f5cb115acdada2395f9606edc/source/dub/generators/build.d#L396-L397

This will add "dub.selections.json" to allfiles
https://github.com/dlang/dub/blob/f54b85305ff0f44f5cb115acdada2395f9606edc/source/dub/generators/build.d#L399-L400

Both will cause a rebuild as timestamp of "." is always new and "dub.selections.json" never exists for single file dub packages.

**Comment by jacob-carlborg** [comment]
Might be related https://github.com/dlang/dub/pull/1687.

**Comment by andre2007** [comment]
PR https://github.com/dlang/dub/pull/1811

**Comment by andre2007** [comment]
Fixed in master
