### ISSUE TITLE
certificate errors causing dub builds to fail

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#1815]
numerous travis-ci builds fail due to:

```
Package derelict-pq not found in registry at https://code.dlang.org/ (fallbacks registry at https://code-mirror.dlang.io/, registry at https://dub-registry.herokuapp.com/): Failed to download https://code.dlang.org/api/packages/infos?packages=%5B%22derelict-pq%22%5D&include_dependencies=true&minimize=true

Failed to find any versions for package derelict-pq, referenced by ddbc 0.5.1
```

So I pasted the URL into Firefox to see if it returned anything at all and found:

> Web sites prove their identity via certificates. Firefox Developer Edition does not trust this site because it uses a certificate that is not valid for code.dlang.org. The certificate is only valid for mx.rejectedsoftware.com.
>  
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

So it looks like things are not configured correctly on code.dlang.org

**Comment by WebFreak001** [comment]
certificate was updated now
