### ISSUE TITLE
Released DUB binaries should be built with the latest compiler

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#1822]
I was playing with `install.sh` and realized that the binaries we distribute are different from the one packaged with DMD, which is obviously problematic for reporting bug.

Additionally, since the compiler used is < 2.087.1, the binaries are simply broken on OSX:

```console
$ ~/dlang/dub-1.18.0/dub --version
dyld: lazy symbol binding failed: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/geod24/dlang/dub-1.18.0/dub
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/geod24/dlang/dub-1.18.0/dub
  Expected in: /usr/lib/libSystem.B.dylib

[3]    44459 abort      ~/dlang/dub-1.18.0/dub --version
$ ~/dlang/dmd-2.089.1/osx/bin/dub --version
DUB version 1.18.0, built on Dec 14 2019
```

**Comment by Panke** [comment]
What's the state of this?

**Comment by Geod24** [comment]
Fixed. We'll need to do things like https://github.com/dlang/dub/pull/1879 from time to time but at least it works on OSX now...
