### ISSUE TITLE
Command 'dub add pkg:subpkg' fails

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#1846]
```console
$ dub add vibe-d:crypto
Failed to get versions for package vibe-d:crypto on provider registry at https://code.dlang.org/ (fallbacks registry at https://code-mirror.dlang.io/, registry at https://dub-registry.herokuapp.com/): (1): Error: Got .vibe-d:crypto of type undefined, expected object.
Could not find package 'vibe-d:crypto'.
```

Given we are forced to add sub packages to be able to configure packages, it's pretty annoying that you can't do it through dub itself. Even if we don't want it as a feature, the syntax should be recognized and error gracefully.

**Comment by andre2007** [comment]
Matbe related to this, support for ```dub fetch package:subPackage``` was added with pr https://github.com/dlang/dub/pull/1756

**Comment by Geod24** [comment]
This now works with the latest release.
