### ISSUE TITLE
dub takes too long to resolve dependency on dub projects

### ISSUE THREAD

**Issue by 98982872** [dlang/dub#1855]
### System information
- DUB version 1.8.0-2, built on Mar 27 2018
- Ubuntu 18.04
- `ldc2 --v`
>binary    /usr/bin/ldc2
>version   1.8.0 (DMD v2.078.3, LLVM 5.0.1)
>config    /etc/ldc2.conf (x86_64-pc-linux-gnu)
OVERVIEW: LDC - the LLVM D compiler
### Bug Description
dub takes too long to resolve a vibe-d project.
### How to reproduce?
` dub init hello --type=vibe.d`
`dub --compiler ldc2` (note that I don't have dmd in my system)
### Expected Behavior
Should build a vibe-d hello-world project
### Logs
<details>
  <summary>Click to expand</summary>
  <p>u9898287@pop-os:~/Proj/hello$ dub -v --compiler ldc2
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/u9898287/.dub/packages/local-packages.json
Note: Failed to determine version of package hello at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/u9898287/.dub/packages/local-packages.json
  Version selection for dependency vibe-d (vibe-d) of hello is missing.
  Missing dependency vibe-d ~>0.8.2 of hello
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/u9898287/.dub/packages/local-packages.json
  Version selection for dependency vibe-d (vibe-d) of hello is missing.
  Missing dependency vibe-d ~>0.8.2 of hello
Checking for missing dependencies.
Search for versions of vibe-d (1 package suppliers)
Return for vibe-d: [0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.33, 0.7.32, 0.7.31, 0.7.30, 0.7.29, 0.7.28, 0.7.27, 0.7.26, 0.9.0-alpha.1, 0.8.6-rc.1, 0.8.6-beta.1, 0.8.6-alpha.2, 0.8.6-alpha.1, 0.8.5-rc.1, 0.8.5-beta.2, 0.8.5-beta.1, 0.8.5-alpha.3, 0.8.5-alpha.2, 0.8.5-alpha.1, 0.8.4-rc.1, 0.8.4-beta.1, 0.8.4-alpha.1, 0.8.3-rc.2, 0.8.3-rc.1, 0.8.3-beta.1, 0.8.3-alpha.4, 0.8.3-alpha.3, 0.8.3-alpha.2, 0.8.3-alpha.1, 0.8.2-rc.2, 0.8.2-rc.1, 0.8.2-alpha.3, 0.8.2-alpha.2, 0.8.2-alpha.1, 0.8.1-rc.4, 0.8.1-rc.3, 0.8.1-rc.2, 0.8.1-rc.1, 0.8.1-beta.2, 0.8.1-beta.1, 0.8.1-alpha.4, 0.8.1-alpha.3, 0.8.1-alpha.2, 0.8.1-alpha.1, 0.8.0-rc.6, 0.8.0-rc.5, 0.8.0-rc.4, 0.8.0-rc.3, 0.8.0-rc.2, 0.8.0-rc.1, 0.8.0-beta.8, 0.8.0-beta.7, 0.8.0-beta.6, 0.8.0-beta.5, 0.8.0-beta.4, 0.8.0-beta.3, 0.8.0-beta.2, 0.8.0-beta.1, 0.8.0-alpha.1, 0.7.33-beta.1, 0.7.32-rc.1, 0.7.32-alpha.1, 0.7.31-rc.3, 0.7.31-rc.2, 0.7.31-rc.1, 0.7.31-beta.2, 0.7.31-beta.1, 0.7.31-alpha.1, 0.7.30-rc.2, 0.7.30-rc.1, 0.7.30-beta.1, 0.7.30-alpha.5, 0.7.30-alpha.4, 0.7.30-alpha.3, 0.7.30-alpha.2, 0.7.30-alpha.1, 0.7.29-rc.1, 0.7.29-beta.2, 0.7.29-beta.1, 0.7.29-alpha.3, 0.7.29-alpha.2, 0.7.29-alpha.1, 0.7.28-alpha.1, 0.7.27-rc.2, 0.7.27-rc.1, 0.7.27-beta.1, 0.7.27-alpha.3, 0.7.27-alpha.2, 0.7.27-alpha.1, 0.7.26-rc.3, 0.7.26-rc.2, 0.7.26-rc.1, 0.7.26-beta.1, ~master, ~nothrow_tasks, ~issue_1994_json_trailing_comma, ~http_speedup, ~http2-botan-cleanup, ~http2-botan, ~0.7.x]
Search for versions of stdx-allocator (1 package suppliers)
Return for stdx-allocator: [3.0.2, 3.0.1, 3.0.0, 2.77.5, 2.77.4, 2.77.3, 2.77.2, 2.77.1, 2.77.0, 3.1.0-beta.2, 3.1.0-beta.1, 2.77.0-1, ~master, ~2.77.z]
Search for versions of mir-core (1 package suppliers)
Return for mir-core: [1.0.2, 1.0.1, 1.0.0, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1, 0.0.0, ~master, ~emplace]
Search for versions of vibe-core (1 package suppliers)
Return for vibe-core: [1.8.1, 1.8.0, 1.7.0, 1.6.2, 1.6.1, 1.6.0, 1.5.0, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0, 1.8.0-alpha.2, 1.8.0-alpha.1, 1.7.0-rc.2, 1.7.0-rc.1, 1.7.0-beta.2, 1.7.0-beta.1, 1.6.3-alpha.2, 1.6.3-alpha.1, 1.4.1-rc.1, 1.4.1-beta.2, 1.4.1-beta.1, 1.4.0-rc.2, 1.4.0-rc.1, 1.4.0-alpha.1, 1.3.0-rc.2, 1.3.0-rc.1, 1.3.0-alpha.2, 1.3.0-alpha.1, 1.2.1-alpha.2, 1.2.1-alpha.1, 1.0.0-rc.4, 1.0.0-rc.3, 1.0.0-rc.2, 1.0.0-rc.1, 1.0.0-beta.8, 1.0.0-beta.7, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.3, 1.0.0-beta.2, 1.0.0-beta.1, 1.0.0-alpha.14, 1.0.0-alpha.13, 1.0.0-alpha.12, 1.0.0-alpha.11, 1.0.0-alpha.10, 1.0.0-alpha.9, 1.0.0-alpha.8, 1.0.0-alpha.7, 1.0.0-alpha.6, 1.0.0-alpha.5, 1.0.0-alpha.4, 1.0.0-alpha.3, 1.0.0-alpha.2, 1.0.0-alpha.1, ~master, ~reproduce_optlink_issue_18, ~dip1000, ~deprecate_throwing_tasks, ~bugfix]
Search for versions of eventcore (1 package suppliers)
Return for eventcore: [0.8.48, 0.8.47, 0.8.46, 0.8.45, 0.8.44, 0.8.43, 0.8.42, 0.8.41, 0.8.40, 0.8.39, 0.8.38, 0.8.37, 0.8.36, 0.8.35, 0.8.34, 0.8.33, 0.8.32, 0.8.31, 0.8.30, 0.8.29, 0.8.28, 0.8.27, 0.8.26, 0.8.25, 0.8.24, 0.8.23, 0.8.22, 0.8.21, 0.8.20, 0.8.19, 0.8.18, 0.8.17, 0.8.16, 0.8.15, 0.8.14, 0.8.13, 0.8.12, 0.8.11, 0.8.10, 0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.0, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.2, 0.1.1, ~master, ~issue_29_duplicate_object_name, ~connect_callback_fix]
Search for versions of taggedalgebraic (1 package suppliers)
Return for taggedalgebraic: [0.11.8, 0.11.7, 0.11.6, 0.11.5, 0.11.4, 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.10.13, 0.10.12, 0.10.11, 0.10.10, 0.10.9, 0.10.8, 0.10.7, 0.10.6, 0.10.5, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, ~master, ~opApply]
Search for versions of libasync (1 package suppliers)
Return for libasync: [0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, ~master, ~remove_mscoff_config, ~patch-1]
Search for versions of memutils (1 package suppliers)
Return for memutils: [0.4.13, 0.4.12, 0.4.11, 0.4.10, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.8, 0.3.7, 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, ~master, ~remove_postblit_qualifiers, ~remove_32mscoff_config]
Search for versions of libevent (1 package suppliers)
Return for libevent: [2.0.2+2.0.16, 2.0.1+2.0.16, 2.0.0+2.0.16, ~master]
Search for versions of openssl (1 package suppliers)
Return for openssl: [2.0.1+1.1.0h, 2.0.0+1.1.0h, 1.1.6+1.0.1g, 1.1.5+1.0.1g, 1.1.4+1.0.1g, 1.1.3+1.0.1g, 1.1.2+1.0.1g, 1.1.1+1.0.1g, 1.1.0+1.0.1g, 1.0.0+1.0.0e, ~master]
Search for versions of botan (1 package suppliers)
Ignoring version specification (>=0.0.0) for path based dependency ../memutils
Return for botan: [1.12.10, 1.12.9, 1.12.8, 1.12.7, 1.12.6, 1.12.5, 1.12.4, 1.12.3, 1.12.2, 1.12.1, 1.12.0, 1.11.14, 1.11.13, 1.11.12, 1.11.11, 1.11.10, ~master, ~merge-new-algos, ~ldc-compat, ~fix-tls]
Search for versions of botan-math (1 package suppliers)
Return for botan-math: [1.0.3, 1.0.2, 1.0.1, 1.0.0, ~master]
Sub package botan:base doesn't exist in botan 1.12.10.
Sub package botan:base doesn't exist in botan 1.12.9.
Sub package botan:base doesn't exist in botan 1.12.0.
Sub package botan:base doesn't exist in botan 1.11.14.
Sub package botan:base doesn't exist in botan 1.11.13.
Sub package botan:base doesn't exist in botan 1.11.12.
Sub package botan:base doesn't exist in botan 1.11.11.
Sub package botan:base doesn't exist in botan 1.11.10.
Sub package botan:base doesn't exist in botan ~master.
Sub package botan:base doesn't exist in botan ~merge-new-algos.
Sub package botan:base doesn't exist in botan ~ldc-compat.
Sub package botan:base doesn't exist in botan ~fix-tls.
Sub package botan:compression doesn't exist in botan 1.12.10.
Sub package botan:compression doesn't exist in botan 1.12.9.
Sub package botan:compression doesn't exist in botan 1.12.0.
Sub package botan:compression doesn't exist in botan 1.11.14.
Sub package botan:compression doesn't exist in botan 1.11.13.
Sub package botan:compression doesn't exist in botan 1.11.12.
Sub package botan:compression doesn't exist in botan 1.11.11.
Sub package botan:compression doesn't exist in botan 1.11.10.
Sub package botan:compression doesn't exist in botan ~master.
Sub package botan:compression doesn't exist in botan ~merge-new-algos.
Sub package botan:compression doesn't exist in botan ~ldc-compat.
Sub package botan:compression doesn't exist in botan ~fix-tls.
Sub package botan:tls doesn't exist in botan 1.12.10.
Sub package botan:tls doesn't exist in botan 1.12.9.
Sub package botan:tls doesn't exist in botan 1.12.0.
Sub package botan:tls doesn't exist in botan 1.11.14.
Sub package botan:tls doesn't exist in botan 1.11.13.
Sub package botan:tls doesn't exist in botan 1.11.12.
Sub package botan:tls doesn't exist in botan 1.11.11.
Sub package botan:tls doesn't exist in botan 1.11.10.
Sub package botan:tls doesn't exist in botan ~master.
Sub package botan:tls doesn't exist in botan ~merge-new-algos.
Sub package botan:tls doesn't exist in botan ~ldc-compat.
Sub package botan:tls doesn't exist in botan ~fix-tls.
Sub package botan:passhash doesn't exist in botan 1.12.10.
Sub package botan:passhash doesn't exist in botan 1.12.9.
Sub package botan:passhash doesn't exist in botan 1.12.0.
Sub package botan:passhash doesn't exist in botan 1.11.14.
Sub package botan:passhash doesn't exist in botan 1.11.13.
Sub package botan:passhash doesn't exist in botan 1.11.12.
Sub package botan:passhash doesn't exist in botan 1.11.11.
Sub package botan:passhash doesn't exist in botan 1.11.10.
Sub package botan:passhash doesn't exist in botan ~master.
Sub package botan:passhash doesn't exist in botan ~merge-new-algos.
Sub package botan:passhash doesn't exist in botan ~ldc-compat.
Sub package botan:passhash doesn't exist in botan ~fix-tls.
Failed to load path based dependency memutils: No package file found in ../memutils/, expected one of dub.json/dub.sdl/package.json
Search for versions of mir-linux-kernel (1 package suppliers)
Return for mir-linux-kernel: [1.0.1, 1.0.0, 1.0.0-alpha2, 1.0.0-alpha1, ~master]
Search for versions of diet-ng (1 package suppliers)
Return for diet-ng: [1.6.0, 1.5.0, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0, 1.0.0-beta.3, 1.0.0-beta.2, 1.0.0-beta.1, 1.0.0-alpha.2, 1.0.0-alpha.1, ~master, ~struct_dom, ~dmd_segfault]
The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.</p>
</details>

**Comment by Geod24** [comment]
Dub 1.8.0 is quite old and this issue have been fixed. Any chance you can update to a more recent version ?

**Comment by 98982872** [comment]
Yes, updating dub fixed it, closing.

**Comment by naturalmechanics** [comment]
I am having the same issue
I tried to update dub with :

$ dub fetch dub
Fetching dub 1.19.0...
Please note that you need to use `dub run <pkgname>` or add it to dependencies of your package to actually use/run it. dub does not do actual installation of packages outside of its own ecosystem.


$ dub run dub
Building package dub in /root/.dub/packages/dub-1.19.0/dub/
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching diet-ng 1.6.0 (getting selected version)...
Fetching taggedalgebraic 0.11.8 (getting selected version)...
Fetching botan 1.12.10 (getting selected version)...
Fetching stdx-allocator 2.77.5 (getting selected version)...
Fetching vibe-d 0.8.6 (getting selected version)...
Fetching mir-linux-kernel 1.0.1 (getting selected version)...
Fetching memutils 0.4.13 (getting selected version)...
Fetching vibe-core 1.8.1 (getting selected version)...
Fetching libasync 0.8.4 (getting selected version)...
Fetching botan-math 1.0.3 (getting selected version)...
Fetching eventcore 0.8.48 (getting selected version)...
The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.

what can I do

**Comment by 98982872** [comment]
> what can I do

Is your dub running on the latest version

**Comment by Geod24** [comment]
For reference, `dub fetch dub` is not the way to upgrade `dub`. Discussion moved to https://github.com/dlang/dub/issues/1871
