### ISSUE TITLE
dub-v1.19.0-windows-{x86,x86_64}.zip contain ELF binaries, not PE

### ISSUE THREAD

**Issue by CyberShadow** [dlang/dub#1859]
https://github.com/dlang/dub/releases/download/v1.19.0/dub-v1.19.0-windows-x86.zip
https://github.com/dlang/dub/releases/download/v1.19.0/dub-v1.19.0-windows-x86_64.zip

These files contain a dub.exe, but it's in the ELF format.

Unless there has been some drastic change on Windows that I missed, I'm pretty sure Windows won't be able to run these.

**Comment by Geod24** [comment]
Yes, the release script was utterly broken. See the reported issue: https://github.com/dlang/dub/issues/1795
The script has been fixed now  (https://github.com/dlang/dub/pull/1849) but the binaries haven't been fixed.
I think we could fix those manually.

**Comment by CyberShadow** [comment]
Thanks!
