### ISSUE TITLE
Add commandline option -lowmem

### ISSUE THREAD

**Issue by shoo** [dlang/dub#1867]
The `-lowmem` option is effective when building in an environment with low memory capacity.
When specifying this using dub, it is necessary to describe it in `dflags` of dub.sdl/.json which is a configuration file now.
However, since this option is not dependent on the project itself, but an option that needs to be switched depending on the building environment, it should not be described in a configuration file that applies regardless of the environment.
To solve this, I propose to allow the `-lowmem` option to be specified in the command line argument of dub itself.

Thanks!

**Comment by rikkimax** [comment]
Alternatively use ``DFLAGS="-lowmem" dub build``.

**Comment by shoo** [comment]
Thanks for suggesting alternatives.
In addition, editing sc.ini / dmd.conf / ldc2.conf has the same effect.

**Comment by Geod24** [comment]
It sounds like something that should be in the [settings file](https://dub.pm/settings).

**Comment by shoo** [comment]
Sounds good. It's a good idea to be able to describe it in the settings file.

**Comment by Geod24** [comment]
Looks like you fixed this, right ?

**Comment by shoo** [comment]
Yes, this has been released with dmd 2.097.0.
