### ISSUE TITLE
Updating dub fails

### ISSUE THREAD

**Issue by naturalmechanics** [dlang/dub#1871]
### System information

- **dub version**: DUB version 1.8.0-2, built on Mar 27 2018
- **OS Platform and distribution**: 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **compiler version** : DMD64 D Compiler v2.090.0

### Bug Description
Updating dub fails.

### How to reproduce?
$ dub fetch dub
Fetching dub 1.19.0...
Please note that you need to use `dub run <pkgname>` or add it to dependencies of your package to actually use/run it. dub does not do actual installation of packages outside of its own ecosystem.

$ dub run dub
Building package dub in /root/.dub/packages/dub-1.19.0/dub/
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching diet-ng 1.6.0 (getting selected version)...
Fetching taggedalgebraic 0.11.8 (getting selected version)...
Fetching botan 1.12.10 (getting selected version)...
Fetching stdx-allocator 2.77.5 (getting selected version)...
Fetching vibe-d 0.8.6 (getting selected version)...
Fetching mir-linux-kernel 1.0.1 (getting selected version)...
Fetching memutils 0.4.13 (getting selected version)...
Fetching vibe-core 1.8.1 (getting selected version)...
Fetching libasync 0.8.4 (getting selected version)...
Fetching botan-math 1.0.3 (getting selected version)...
Fetching eventcore 0.8.48 (getting selected version)...
The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.

**Comment by wilzbach** [comment]
I'm sorry, but you're using a very old version of dub which is why the dependency resolution failed. How did you install it? The latest dub should be shipped with the latest compiler installation.

Anyhow, it's not possible to update dub with dub as there are too many different ways that dub could have been installed. If you are searching for a quick way to update dub, you could try the official install script: https://dlang.org/install

**Comment by naturalmechanics** [comment]
I used sudo apt-get install dub.

using the git with ./build.d hangs everything

**Comment by naturalmechanics** [comment]
also i updated and upgraded my system, but no avail

**Comment by wilzbach** [comment]
Your dub version is about two years old. As mentioned before you can simply use the dub binary bundled with your DMD compiler (not the system installation) or you can add the d-apt: https://dlang.org/download.html

**Comment by naturalmechanics** [comment]
where do i find the other dub? there was no dub, even tho dmd was installed. that is why i took the system install

**Comment by wilzbach** [comment]
How did you install DMD? It is in the same `bin` folder.

**Comment by naturalmechanics** [comment]
also from the official repos.
but i have managed to install dmd and dub thru new ppa-s

now i have: 

# dub build
Running pre-generate commands for vibe-d:tls...
Performing "debug" build using /usr/bin/dmd for x86_64.
taggedalgebraic 0.11.8: target for configuration "library" is up to date.
eventcore 0.8.48: target for configuration "epoll" is up to date.
stdx-allocator 2.77.5: target for configuration "library" is up to date.
vibe-core 1.8.1: target for configuration "epoll" is up to date.
vibe-d:utils 0.8.6: target for configuration "library" is up to date.
vibe-d:data 0.8.6: target for configuration "library" is up to date.
mir-linux-kernel 1.0.1: target for configuration "library" is up to date.
vibe-d:crypto 0.8.6: target for configuration "library" is up to date.
diet-ng 1.6.1: target for configuration "library" is up to date.
vibe-d:stream 0.8.6: target for configuration "library" is up to date.
vibe-d:textfilter 0.8.6: target for configuration "library" is up to date.
vibe-d:inet 0.8.6: target for configuration "library" is up to date.
vibe-d:tls 0.8.6: target for configuration "openssl" is up to date.
vibe-d:http 0.8.6: building configuration "library"...
/root/.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d(949,24): Deprecation: function std.typecons.Nullable!(CookieValueMap).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/root/.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d(962,38): Deprecation: function std.typecons.Nullable!(DictionaryList!(string, true, 16LU, false)).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/root/.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/server.d(1041,18): Deprecation: function std.typecons.Nullable!(DictionaryList!(string, true, 16LU, false)).Nullable.get_ is deprecated - Implicit conversion with alias Nullable.get this will be removed after 2.096. Please use .get explicitly.
/usr/include/dmd/phobos/std/range/primitives.d(174,38): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/usr/include/dmd/phobos/std/range/primitives.d(176,27): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/usr/include/dmd/phobos/std/range/primitives.d(174,38): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
/usr/include/dmd/phobos/std/range/primitives.d(176,27): Deprecation: alias byKeyValue this is deprecated - Iterate over .byKeyValue instead.
Error: out of memory
/usr/bin/dmd failed with exit code 1.

? it takes 1 few seconds to get to this.

**Comment by Geod24** [comment]
How much RAM do you have ?

As @wilzbach pointed out, `dub` is not responsible for its own upgrading.
Since you're on Ubuntu, `dub` is provided by APT. However Ubuntu systems tend to stick to a specific minor release, and in your case it is 1.8.0, so I'm guessing you are on 18.04 LTS ?

 I haven't used Ubuntu for a while, but when I did, https://d-apt.sourceforge.io/ was the way to get up-to-date dub via APT.

**Comment by 98982872** [comment]
> I used sudo apt-get install dub.
> 
> using the git with ./build.d hangs everything

I am using an ubuntu based distribution as well. I got around it by using the snap packages of dmd, dub and ldc.

**Comment by Geod24** [comment]
Closing as this is not a dub issue we can act on, but a packaging one.
