### ISSUE TITLE
Do not exclude `package.d` with newer compilers

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1874]
As the related issue [11847](https://issues.dlang.org/show_bug.cgi?id=11847) is fixed, could we include package.d again for newer compiler versions?

>dub test -b syntax
Generating test runner configuration 'arsd-official-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "syntax" build using C:\Develop\D\dmd2\windows\bin\dmd.exe for x86_64.

**Comment by Geod24** [comment]
Modified the title to be a bit more descriptive of the action to take.
Note that the fix for this is in `stable`, but didn't make it to 2.090.1 AFAICS (https://github.com/dlang/dmd/commit/fffe6be43e295ea489afc1de0291bf99af0956e8)

**Comment by WebFreak001** [comment]
it made it in with 2.091.0

Also this issue was before only applying to single level packages, so we can add exceptions for those for any version.

Even simpler: you can use `import p0 = some.mod` as workaround for the bug, so we don't have to write compiler version-specific code at all

**Comment by rikkimax** [comment]
Assuming this has been deployed, can we please close this issue?

**Comment by WebFreak001** [comment]
See #424
