### ISSUE TITLE
Why is "git branch" support depreciated?

### ISSUE THREAD

**Issue by Robert-M-Muench** [dlang/dub#1878]
IMO this is a very valuable feature... how else can I try a different version of a lib with dub?

The use case for this feature is:
* I use a 3rd party lib
* I find some problem
* Author fixes it and provides a new branch to test

**Comment by Geod24** [comment]
The main reason is that branches are not fixed target, which makes their behavior either extremely inefficient or non-intuitive.
An example of this is that, whenever you `dub build`, some people expect their version to be checked against the recipe file, which would mean a network rountrip.
Nowadays you can use `repository` in your dependencies to point to a specific commit.
