### ISSUE TITLE
Package descriptor attribute commandsEnvVariables

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1885]
By adding a new attribute `commandsEnvVariables` it will be possible to set environment variables for the pre/post *commands.

```
{
"commandsEnvVariables":{
    "env1":"value"
    }
}
```

The commandsEnvVariables should be inherited also into the pre/post *commands of the dependencies of the main dub package.

**Comment by andre2007** [comment]
Unfortunately, the scenario I wanted to achieve is not working.

**Comment by WebFreak001** [comment]
fixed with #2121
