### ISSUE TITLE
Automatically locate and use MS environment variable when building using LDC2

### ISSUE THREAD

**Issue by RUSshy** [dlang/dub#1897]
### System information
dub: 1.20
ldc2: 1.20.1
os: windows 10 x64

### Bug Description
when building with dub, i get the following error:
`` lld-link: error: could not open 'LIBCMT.lib': no such file or directory``

### How to reproduce?

run:
`` dub run --arch=x86_64  --compiler=ldc2`` 

### Expected Behavior

project should compile and run

### Fix

I was able to fix that by running the command using the x64  native tool command line

But that should be handled automatically by dub

In other languages such as rust(cargo) it is not an issue

**Comment by Geod24** [comment]
Can you provide the project ? Or perhaps at least the `dub.json`. Does it happen when you compile with `ldc2` directly ?

**Comment by RUSshy** [comment]
root
```json
{
	"name": "kingdom",
	"authors": [
		"rus"
	],
	"description": "kingdom",
	"copyright": "Copyright © 2019, rus",
	"license": "proprietary",
	"targetType": "none",
	
	"lflags":[
		"-subsystem:windows",
		"-entry:mainCRTStartup"
	],

	"subPackages": [
		"../arc_d/arc",
		"common",
		"client"
	]
}
```

client
```json
{
	"authors": [
		"rus"
	],
	"copyright": "Copyright © 2019, rus",
	"dependencies": {
		"arc_d:arc": {"path":"../../arc_d/", "version": "~master"},
		"kingdom:common": { "path": "../common/", "version": "~master"},
		"bindbc-glfw": "~>0.8.1",
		"bindbc-openal": "~>0.3.0",
		"bindbc-opengl": "~>0.9.0",
		"stb": "~>1.7.5"
	},
	"versions": [
		"GL_33",
		"GLFW_32"
	],
	"license": "proprietary",
	"name": "client",
	"targetName": "client",
	"targetPath": "../bin",
	"targetType": "executable",
	"workingDirectory": "../bin"
}
```

common
```json
{
	"name": "common",
	"authors": [
		"rus"
	],
	"description": "game framework",
	"copyright": "Copyright © 2019, rus",
	"targetName": "common",
	"targetType": "sourceLibrary",
	"targetPath": "../bin",
	"workingDirectory": "../bin",
	
	"dependenciess": {
		"arc_d:arc": {"path":"../../arc_d/", "version": "~master"}
	},
	"versions": [
	]
}
```

**Comment by RUSshy** [comment]
exact command:

``dub run :client -b release --arch=x86_64 --compiler=ldc2``

**Comment by RUSshy** [comment]
the way i installed ldc2:

i downloaded the archive, and i extracted it to: ``c:/D``

then i added the ``c:/D/ldc2/bin`` to my PATH

**Comment by Geod24** [comment]
Thanks!
I'm no LDC expert but from a quick look it looks like your linker is complaining about not finding an MSVC library. According to [this](https://github.com/ldc-developers/ldc/blob/bdb613d0ad81c40a13ece387709b91d8d6deb1e2/packaging/README.txt#L20-L37), which you can also find under `c:/D/ldc2/README.txt`, the default is to link with mingw.

> I was able to fix that by running the command using the x64 native tool command line

That seems coherent with the explanation in the README.

@kinke : Is that something that could / should be expected of `dub` ?

**Comment by kinke** [comment]
IMO, a clear no, it shouldn't.

**Comment by s-ludwig** [comment]
The problem with this is that the easy way - running the "vcvarsall.cmd" (or however it is called) script - is really slow, so the whole logic would have to be duplicated in DUB (which is what LDC basically used to do AFAIK).

**Comment by kinke** [comment]
The OP's problem is almost certainly some C[++] stuff compiled without `/Zl`, so they embed `libcmt.lib`, and that's not provided by the MinGW-based libs. So recompiling that stuff or possibly adding `/NODEFAULTLIB:libcmt` as (LDC) linker flag should fix this with the MinGW-based libs. Alternatively, the MS toolchain can be enforced via the LDC_VSDIR env variable.

**Comment by kinke** [comment]
LDC v1.22+ will auto-detect a Visual C++ installation.
