### ISSUE TITLE
Remove the dependency on std.xml

### ISSUE THREAD

**Issue by shoo** [dlang/dub#1939]
In D 2.092.0, std.xml is marked as deprecated.
Since the dub uses std.xml, we need to remove this dependency.

There is only one place that depends on std.xml, which is as follows:
https://github.com/dlang/dub/blob/c1ee3786d49a93dc1e7df5782b08b6c713d93f75/source/dub/packagesuppliers/maven.d#L82

**Comment by rikkimax** [comment]
```d
deprecated("Will be removed from Phobos in 2.101.0. If you still need it, go to https://github.com/DigitalMars/undeaD")
```

**Comment by andre2007** [comment]
What would be a good solution? My first idea would be to copy the code of std.xml undead to source/dub/internal folder.

**Comment by rikkimax** [comment]
> What would be a good solution? My first idea would be to copy the code of std.xml undead to source/dub/internal folder.

Add it as a dependency until somebody bothers with a rewrite. That is the simplest answer.

**Comment by andre2007** [comment]
The xml parsing is replaced with std.regex:
https://github.com/dlang/dub/pull/1977
