### ISSUE TITLE
dub lint fails when --config argument is used for both dub and dscanner

### ISSUE THREAD

**Issue by dgellow** [dlang/dub#1940]
### System information
- **dub version**: `DUB version 1.20.1, built on Apr 17 2020`
- **OS Platform and distribution**: Tried on Windows 10 and Ubuntu
- **compiler version**: Not relevant

### Bug Description

When using `dub lint --config <path to dub config file> -- --config <path to dscanner config file>`,  `dscanner` is called with both dub config and dscanner config arguments, and results in `dscanner` usage/help message being displayed (i.e: equivalent to `dscanner --help`).

Could that be caused by the fact that both argument have the same name `--config`?

### How to reproduce?

First create a dub project and a `dscanner.ini` file, just to be sure.
```
$ dub init
$ touch dscanner.ini
```

Then run `dub lint` with config arguments used twice, once for `dub` and once for `dscanner`.
```powershell
$ dub lint --config .\dub.sdl -- --config .\dscanner.ini
Running pre-generate commands for dscanner...
# ...more logs...
Running ..\..\..\..\AppData\Local\dub\packages\dscanner-0.9.0\dscanner\bin\dscanner.exe --config .\dub.sdl --config .\dscanner.ini C:\Users\Sam\Development\D\action-dscanner\testdata\

    Usage: ..\..\..\..\AppData\Local\dub\packages\dscanner-0.9.0\dscanner\bin\dscanner.exe <options>

Options:
    --help, -h
        Prints this help message
# ...rest of the usage/help message...
Program exited with code 1
```

Notice how `dscanner.exe` is called with arguments `--config .\dub.sdl --config .\dscanner.ini`.

### Expected Behavior

I would instead expect `dub.exe` to be called with the argument `--config .\dub.sdl` and `dscanner.exe` to be called with the argument `--config .\dscanner.ini`.

**Comment by andre2007** [comment]
Thanks for a very good bug report.

I just noticed, https://dub.pm/commandline.html#lint lists some arguments which actually makes no sense for lint command, architecture, compiler, build, ...

The `config` argument is listed even twice 
The `config` argument for dub configuration does not make sense here.

Lint command only starts DScanner, therefore these arguments do not make sense. Dub will not build your project.

I need to check why these arguments are listed.

**Comment by dgellow** [comment]
> Lint command only starts DScanner, therefore these arguments do not make sense. Dub will not build your project.

Thanks for clarifying, that makes sense now that I think about it.
