### ISSUE TITLE
Selected package doesn't exist

### ISSUE THREAD

**Issue by muv1** [dlang/dub#1957]
I am trying to use this package:

<https://github.com/huntlabs/hunt/releases/tag/v1.4.16>

However if I edit `dub.selections.json`, I get this:

~~~
$ dub build
Selected package hunt 1.4.16 doesn't exist. Using latest matching version
instead. Performing "debug" build using
C:\ldc2-1.22.0-beta1-windows-x64\bin\ldc2.exe for x86_64.
hunt 1.6.0: building configuration "library"...
~~~

It looks like the updated version hasnt been pushed here yet:

<https://code.dlang.org/packages/hunt>

So how do I use the new version?

**Comment by Geod24** [comment]
Yet, it's a current issue: https://github.com/dlang/dub-registry/issues/462
