### ISSUE TITLE
PDB file not copied to targetPath alongside executable on Windows

### ISSUE THREAD

**Issue by chrisoldwood** [dlang/dub#1962]
### System information
- **dub version**: `DUB version 1.20.1, built on Apr 17 2020`
- **OS Platform and distribution**: `Microsoft Windows [Version 10.0.18363.535]` -- (1909), 64-bit
- **compiler version**: `dmd-2.091.1`

### Bug Description
When building an executable the `.exe` is copied to the `targetPath` however the `.pdb` file with the debugging information is not.

### How to reproduce?
```
> type source\app.d
void main() {}

> type dub.sdl
name "foo"
targetName "foo-bin"
targetType "executable"
targetPath "bin\\64"

> dub build
...

> dir /b bin\64
foo-bin.exe
```

### Expected Behavior
```
> dir /b bin\64
foo-bin.exe
foo-bin.pdb
```

### Use Case
On Windows it's common for in-house software to ship the `.pdb` files along with the `.exe` to make live debugging easier. Alternatively the `.pdb` files are published to a [Symbol Server](https://en.wikipedia.org/wiki/Microsoft_Symbol_Server) where they can be downloaded on-the-fly when debugging. In both scenarios we need easy access to the `.pdb` file rather than spelunking the `.dub\build` folder.

**Comment by WebFreak001** [comment]
a pattern I often do if I want the pdb files is adding
```json
"lflags-windows": ["/PDB:path\\to\\output.pdb"]
```
to my dub.json to make the linker emit PDB files.

In my opinion having the PDB files being emitted by default would be quite nice, but also this changes the behavior where it is currently always exactly one output file (which some applications or libraries might depend on for cleanup or other usage)

**Comment by chrisoldwood** [comment]
> In my opinion having the PDB files being emitted by default would be quite nice...

The `.pdb` file is always emitted, you can see it in the `.dub/build` folder, it's just that it's not copied over to the `targetPath` at the end.

**Comment by chrisoldwood** [comment]
Looking at the source it feels like [copyTargetFile](https://github.com/dlang/dub/blob/7336602d36fdf711499a88f1ea40e52c2acbe452/source/dub/generators/build.d#L361) might be the right place to add this but reading @WebFreak001's comment above I see that some may already be relying on a different technique. Maybe it's enough to check if the `.pdb` file was generated by the linker alongside the `.exe` and only copy it if it was?

**Comment by WebFreak001** [comment]
I think to allow for more flexibility it would be nicer if the build output folder was available in the post build commands (maybe even pre build commands) through an environment variable like https://dub.pm/package-format-json.html#environment-variables

Then the PDB file (or any other generated files) could simply be copied using a copy command in the post build commands specified by the user.

**Comment by chrisoldwood** [comment]
One wrinkle I've run into with the `lflags "/PDB:bin\\64\\app.pdb"` approach is that the target folder needs to exist _before_ you start building otherwise you end up failing to link with:
```
Linking...
LINK : fatal error LNK1201: error writing to program database 'C:\...\bin\64\app.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
Error: linker exited with status 1201
```
At the moment `dub` appears to create the `targetPath` folder _after_ linking.

**Comment by s-ludwig** [comment]
One thing that needs to be taken into account is that PDB files are always referenced by absolute path within the executable, so moving it around will not work in the sense that the debugger is not going to find it.

**Comment by chrisoldwood** [comment]
> ...so moving it around will not work in the sense that the debugger is not going to find it.

The _first_ location searched is alongside the `.exe`, then the hard-coded path is one of the many fallbacks, see for example [PDB Files: What Every Developer Must Know](https://www.wintellect.com/pdb-files-what-every-developer-must-know/) by John Robbins:

> With the knowledge of how the debugger determines the correctly matching PDB file, I want to talk about where the debugger looks for the PDB files. You can see all of this order loading yourself by looking at the Visual Studio Modules window, Symbol File column when debugging. _**The first place searched is the directory where the binary was loaded**_. If the PDB file is not there, the second place the debugger looks is the hard coded build directory embedded in the Debug Directories in the PE file. If you look at the above output, you see the full path C:JUNKSTUFFHELLOWORLDOBJDEBUGHELLOWORD.PDB. (The MSBUILD tasks for building .NET applications actually build to the OBJ<CONFIG> directory and copy the output to DEBUG or RELEASE directory only on a successful build.) If the PDB file is not in the first two locations, and a Symbol Server is set up for the on the machine, the debugger looks in the Symbol Server cache directory. Finally, if the debugger does not find the PDB file in the Symbol Server cache directory, it looks in the Symbol Server itself. This search order is why your local builds and public build parts never conflict.

Hence there is no problem copying it to the target path. I even tested this with our app in case there was something different about a D program compared to the C++ apps I normally write and it still appeared to work correctly in the debugger.

**Comment by Temtaime** [comment]
Still no fix ?

**Comment by s-ludwig** [comment]
@chrisoldwood This has not been my experience, at least for LDC. I remember it being different in the past (with MSVC), though, so that might be something that is fixable.
