### ISSUE TITLE
CyberShadow DAutoTest should be run for DUB PRs

### ISSUE THREAD

**Issue by NilsLankila** [dlang/dub#1965]
The problem is that DAutoTest builds the changelog partly using this repo but DAutotest is not executed for this project so it can silently break the whole CI complex.

Example #1964.

**Comment by Geod24** [comment]
CC @CyberShadow

**Comment by CyberShadow** [comment]
Will have to add Dub to [d-dot-git](https://github.com/CyberShadow/D-dot-git), rebuild history, and then add a Digger component.

Are there any other repositories or D components which have changelogs but aren't tested by DAutoTest? (Or, D components/repositories in general that should be part of D-dot-git.)

**Comment by Geod24** [comment]
Just checked [the list](https://github.com/CyberShadow/D-dot-git/blob/559adcb7ae2a46f65501153befbed0742aa9cb74/d-dot-git.d#L27) and I can't think of anything else at the moment.

**Comment by CyberShadow** [comment]
Seems to be working.

**Comment by NilsLankila** [comment]
thanks for the quick reaction.
