### ISSUE TITLE
Dlang

### ISSUE THREAD

**Issue by Tek-God** [dlang/dub#1969]
### System information

- **dub version**: (e.g. dub 1.3.0)
`_-_` `**OS` Platform and distribution**: (e.g. Windows 10, Linux Ubuntu 

> 

> 16.04)

- **compiler version** (e.g. dmd-2.074.1)

**Comment by WebFreak001** [comment]
closing because this looks like accidentally sent without any information, make a new issue if you have anything to report or ask
