### ISSUE TITLE
Executing dub upgrade within a non dub project folder

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1970]
Executing `dub upgrade` within a folder containing no dub project creates:
- Folder `.dub`
- File `dub.selections.json`

Command line shows this output:
>There was no package description found for the application in 'C:\Users\User\git\dta'.
>Upgrading project in C:\Users\User\git\dta

Expectation is, no files / folder are created, only a message `There was no package description found for ...`

**Comment by GrimMaple** [comment]
I was unable to replicate on Windows, only `dub.selections.json` is created. Tried from `master`.
