### ISSUE TITLE
dub fails to recompile files which contain mixedin string imports 

### ISSUE THREAD

**Issue by crazymonkyyy** [dlang/dub#1978]
### Bug Description

If foo.d contains:
```d
   mixin(import("bar.mix"));
```
Dub has/appears to have nothing trying to predict that foo.d should be recompiled if bar.mix changes.

### Expected Behavior

I would suggest for a quick hack, detect the -J flag and assume that it should trigger -f or give me a warning that I've forgotten it

**Comment by andre2007** [comment]
Please use this attribute
`"extraDependencyFiles": ["dependency.txt"]`
To let Dub watch for file changes.

**Comment by crazymonkyyy** [comment]
```"extraDependencyFiles":["*.mix"],```

>works

fair enough, should probably be easier to find in the documentation

**Comment by andre2007** [comment]
You are totally right. I forgot to add it to the documentation. I will add it when I find some free minutes.

**Comment by andre2007** [comment]
https://github.com/dlang/dub-docs/pull/29
