### ISSUE TITLE
Can't `dub generate visuald` if directory .dub doesn't exist yet

### ISSUE THREAD

**Issue by p0nce** [dlang/dub#2019]
### System information
- **dub version**: 1.22.0
- **OS Platform and distribution**: Windows and VisualD

### Bug Description
For VisualD, `dub generate` would need to create `.dub` (some of the projects created will be hidden there).
But it doesn't create it.

In a fresh repo:
```
$ dub generate visuald
Cannot open file `.dub\panagement.visualdproj' in mode `wb' (No such file or directory)
```

As a VisualD user I stumble upon this issue about once per month.

### How to reproduce?
Checkout a clean repo.
Type: `$ dub generate visuald`

### Expected Behavior
Creating that directory.

**Comment by Imperatorn** [comment]
Just to clarify, you want the command to automatically "dub build" before generating sln?

**Comment by p0nce** [comment]
No.

`dub generate` generates IDE project, part of it being in `.dub` directory.
But it fails if the `.dub` directory is not already existing. The trick would be to ensure the directory is created before writing files inside.

**Comment by Imperatorn** [comment]
Yes, but isn't the directory created on dub build? 🤔

**Comment by p0nce** [comment]
All commands that need it should create the `.dub` directory !

**Comment by p0nce** [comment]
Oops, dupe of #1673
