### ISSUE TITLE
Current Working Directory not working in DUB for project files

### ISSUE THREAD

**Issue by ghost** [dlang/dub#202]
DUB is supposed to default the working directory to the targetPath, but when you create a project file (tested with VisualD)  the working directory is still set to the dub directory of the project/package.

I do not know if this is a bug in DUB or a feature missing in VisualD.

**Comment by WebFreak001** [comment]
working directory can be set using the "workingDirectory" directive in recipes, the .visualdproj file at least looks like it's doing its things properly with it.
