### ISSUE TITLE
Can't depend on different versions of same package using configurations

### ISSUE THREAD

**Issue by CyberShadow** [dlang/dub#2023]
I believe this is a "known issue", but I don't see this particular variant of it filed, so here is a formal record of this particular variation of the problem.

The gist is as follows:

```sdl
name "test"

configuration "a" {
	dependency "openssl" version="~>1.0"
	# ... other configuration settings ...
}
configuration "b" {
	dependency "openssl" version="~>2.0"
	# ... other configuration settings ...
}
```

(Any package works instead of `openssl`).

Attempting to build such a project results in:

```
Unresolvable dependencies to package openssl:
  test ~master depends on openssl ~>1
  test ~master depends on openssl ~>2
```

Essentially, [because of how the Dub dependency resolution process works](https://github.com/dlang/dub/wiki/FAQ), it's not possible to support multiple major versions of a library when they also require separate configuration in dub.sdl (such as `versions` or `libs`).

**Comment by nu8** [comment]
https://github.com/CyberShadow/ae/issues/47

**Comment by Geod24** [comment]
This is a duplicate of https://github.com/dlang/dub/issues/1706 (essentially) but since it's likely to be an issue users encounters, let's keep it open (and pinned).

**Comment by Geod24** [comment]
Actually there is: https://github.com/dlang/dub/issues/1217
