### ISSUE TITLE
Only Win-x86_64 had a 1.23.0 download

### ISSUE THREAD

**Issue by bcsgh** [dlang/dub#2038]
https://github.com/dlang/dub/releases Currently lists 7 files for v1.23.0-rc.1 but only 3 files for v1.23.0: 2x source archives and the win-x86_64 binary archive. The win-i686, linux and osx binary archives in the rc.1 are missing without any explanation. All other (non-beta) releases going back a year have all 7 files.

**Comment by Geod24** [comment]
For some reasons those assets seems to have gone under  Draft ??

<img width="1492" alt="Screen Shot 2020-11-18 at 19 49 06" src="https://user-images.githubusercontent.com/2180215/99574049-2b886a80-29d7-11eb-8ae8-562a08aa4db0.png">

**Comment by Geod24** [comment]
<img width="935" alt="Screen Shot 2020-11-18 at 19 50 57" src="https://user-images.githubusercontent.com/2180215/99574263-6d191580-29d7-11eb-82c3-fe1ee42278e1.png">

The issue might come from the pipeline setup, e.g. the way assets are added to a release.

**Comment by Geod24** [comment]
I fixed it, but we should look into what dlang-bot is doing here: https://github.com/dlang/dub/releases/tag/v1.23.0

**Comment by Geod24** [comment]
Things are still broken, opened an issue in the relevant repo: https://github.com/dlang/dlang-bot/issues/266
