### ISSUE TITLE
Dub creates temporary source files for all users in the same location, causing permission errors.

### ISSUE THREAD

**Issue by Kapps** [dlang/dub#205]
For example, assuming a clean directory and two users Foo, and Bar.
Foo runs dub test. It works, and creates /tmp/dub_test_root.d
Then su to Bar and run dub test. It will fail with "Error executing command test: Cannot open or create file '/tmp/dub_test_root.d'". The file is created in /tmp with Foo owning it, and Bar tries to overwrite it which fails because Bar lacks permission. This essentially makes dub (test) not work with multiple users unless you manually delete the temp file after each run.

**Comment by andre2007** [comment]
In the meantime a uuid is added to the filename (getTempFile).
Therefore this issue can be closed.
