### ISSUE TITLE
Running unit tests from DUB single file packages fails

### ISSUE THREAD

**Issue by drug007** [dlang/dub#2051]
### System information

- **dub version**: dub 1.17.0
- **OS Platform and distribution**: Debian 9
- **compiler version** dmd-2.088.1

### Bug Description

Running unit tests from DUB single file packages fails.
See [forum post](https://forum.dlang.org/post/rq5a3n$gcs$1@digitalmars.com) for additional information

### How to reproduce?
Running this:
```D
#!/usr/bin/env dub
/+ dub.sdl:
    name: "main"
+/

version(unittest) {}
else void main()
{
}

unittest
{
	auto input = [1721];
	assert(input[0] == 1721);
}
```
gives:
```
user@user:~/dub$ dub test --single ./test.d
Package main (configuration "application") defines no import paths, use {"importPaths": [...]} or the default package directory structure to fix this.
Generating test runner configuration 'test-test-application' for 'application' (executable).
Source file '/home/user/dub/test/test.d' not found in any import path.
```

### Expected Behavior
the result should be:
```
user@user:~/dub$dub test --single ./test.d
Package main (configuration "application") defines no import paths, use {"importPaths": [...]} or the default package directory structure to fix this.
Generating test runner configuration 'test-test-application' for 'application' (executable).
Performing "unittest" build using dmd for x86_64.
main ~master: building configuration "main-test-application" (default build policy: time)...
Linking...
Running ../../../../tmp/.dub/build/test-~master/test-test-application-unittest-linux.posix-x86_64-dmd_2088-9FDC9F7EC06E24A4F67D7D1E5B88EBD1/test-test-application 
All unit tests have been run successfully.
```

The reason of the bug is that in single mode dub, running test command, try to import the main source file as module and failed because can not find it in any import paths. The main source file should be excluded from this importing but current check for this fails because it can't compare absolute and relative paths correctly (it compares them by char).

**Comment by drug007** [comment]
@thewilsonator  reopen it and assign to me, please  - the PR is a non complete fix of the issue. Now dub does not run unit tests in single file package at all.

**Comment by thewilsonator** [comment]
Done.
