### ISSUE TITLE
`dub build --single source.d` does not perform a plain build but a debug one.

### ISSUE THREAD

**Issue by ghost** [dlang/dub#2054]
### System information

DUB version 1.23.0, built on Oct 18 2020

### Bug Description

`dub build --single source.d` does not perform a plain build but a debug one.

### How to reproduce?

create source.d:

```d
/+ dub.sdl:
    name "source"
+/
void main()
{
    import std.stdio;
    debug writeln("this is a debug build");
} 
```
then

```
$ dub build --single source.d
$ ./source
```

### Expected Behavior

no output

### Logs

> this is a debug build

**Comment by drug007** [comment]
But debug build is the default one. You can use `dub --single source.d --build=release` to get what you want. As for me it is expected result.

**Comment by nordlow** [comment]
I think this should be closed, @Geod24 @thewilsonator.

**Comment by WebFreak001** [comment]
I agree, debug is the default, plain is used very seldomly
