### ISSUE TITLE
Bitbucket documentation not updated with package

### ISSUE THREAD

**Issue by shiche** [dlang/dub#2078]
### System information
Example http://dateformat.dpldocs.info/dateformat.html

### Bug Description
I extended ddoc documentation many times, but documentation still '2020-11-03T06:37:03Z', although bitbucket contains fresh version of it.

### How to reproduce?
Make package on bitbucket with some documentation, then change it. Package will updates, but documentation not.

### Expected Behavior
Package updates with appropriate documentation.

**Comment by adamdruppe** [comment]
Those docs are reset by clicking the "clear cache" button at the bottom of the documentation page or by going to a specific git tag subdirectory. They do NOT update automatically.

So see a specific version like this:

http://dateformat.dpldocs.info/v0.2.1/dateformat.html

Or click the button at the very bottom of any doc page to get it to rebuild.
