### ISSUE TITLE
Cannot add dflags on dependencies when using SDL format

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#2079]
Dub v1.24.0 introduced [dflags on dependencies](https://dlang.org/changelog/2.095.0.html#dependency-build-settings), but this is only supported for the JSON format, not the SDL format.

CC @omerfirmak @mdparker

**Comment by s-ludwig** [comment]
Also, this needs to be [documented](https://github.com/dlang/dub-docs).

**Comment by Geod24** [comment]
Actually, @omerfirmak , could you also document it as Sonke mentioned ?
