### ISSUE TITLE
test suite - gracefully putting compilers, platforms and .no_{build|test|run} files all together

### ISSUE THREAD

**Issue by drug007** [dlang/dub#2111]
Currently the test suite does not build/test/run a package if the package has .no_{build|test|run} file. Moreover a compiler could be added to the file name to define compiler specific actions - for example if a package has .no_build_dmd file then the package won't be built by dmd compiler. To make a step further we need to add platform specific actions. Obviously using .no_build_dmd_windows is not our way. The suggestion is using only one .no_{build | test | run } file and encode compiler/platform specific actions in the file content like a regular matrix:
```
        | dmd   ldc   gdc
--------+-----------------
posix   | yes   no    no
windows | no    no    yes
```
What do you think?

**Comment by maxhaton** [comment]
Good idea probably - simple csv would do the trick I assume

**Comment by Geod24** [comment]
Agreed. Actually, we could just go with a single file, in an easy-to-parse format (could just be JSON).

**Comment by drug007** [comment]
I realized that we don't need add new axis (by platform) to the test suite because the test suite is (should be at least) single for all platforms (in contrast to compilers). Currently some tests fail in Windows but this is a temporary state due to transition and should be fixed. So the current using of `.no{build|test|run}` files do not need changing.

What about using single json file - I find that being able to take a look at a directory and clearly see will the package be build|run|tested is a useful thing. Using json I will be need to open the file to view in which manner the package will be tested. But this can be easily nitpicking.
