### ISSUE TITLE
Latest release page is outdated

### ISSUE THREAD

**Issue by shoo** [dlang/dub#2113]
Currently, dub version is 1.24.1 included in dmd 2.095.1. However, the top page of GitHub shows 1.23.0.
![image](https://user-images.githubusercontent.com/580704/109277225-657cce80-785a-11eb-9c55-bd4786f5208c.png)

Tags are existing.
https://github.com/dlang/dub/tags
![image](https://user-images.githubusercontent.com/580704/109277764-15ead280-785b-11eb-9777-79b9c5655de7.png)

Isn't the CI broken? Or have you abandoned the descriptions on the release page?

**Comment by shoo** [comment]
Although the relevance is unclear, the dub registry has 1.24.0 registered, and 1.24.1 is not.
https://code.dlang.org/packages/dub

**Comment by jmh530** [comment]
In addition, the `install.sh` script pings a site called [ https://dlang.github.io/dub/LATEST]( https://dlang.github.io/dub/LATEST), which has `v1.22.0` as the output. 

I am [trying ](https://github.com/dlang-tour/core-exec/pull/56)to get `run.dlang.org` to properly handle unittests with external dependencies. Right now, my version uses `install.sh` to install dmd/ldc and dub. However, it's a little tricky. For dmd, it is installed 2.096, which comes with the latest dub, and then it also installs this older version of dub. However, that older version isn't called here. For ldc, I think it just uses this older dub version.

**Comment by jmh530** [comment]
Something seems wrong with `install.sh`.

Tried to replace the `install.sh` command with below (and a number of other variations), but it failed 
```
RUN set -eux ; \
    if [ \"${DLANG_VERSION}\" == \"dmd\" ] ; \
    then \
        bash /tmp/install.sh -p /dlang install ${DLANG_VERSION} ; \
    else \
        bash /tmp/install.sh -p /dlang install ${DLANG_VERSION},dmd ; \
    fi
```
I got errors like
```
#8 7.370 Downloading and unpacking https://github.com/dlang/dub/releases/download/v/dub-v-linux-x86_64.tar.gz
#8 7.407 curl: (22) The requested URL returned error: 404 
```
I get the same thing with something simpler like
`RUN bash /tmp/install.sh -p /dlang install ${DLANG_VERSION},dmd`
(for both dmd and ldc)

It doesn't happen with 
`RUN bash /tmp/install.sh -p /dlang install ${DLANG_VERSION}`

The current (passing) version does not install dub separately and would skip the unittests on ldc.

**Comment by jmh530** [comment]
@PetarKirov I believe the issue with what I discuss above is that only `dub` can be used after the comma in install.sh, but there is no error about it. I filed an enhancement request [here](https://issues.dlang.org/show_bug.cgi?id=21786).

A workaround of
```
RUN if [ \"${DLANG_EXEC}\" != \"dmd\" ] ; then \
    bash /tmp/install.sh -p /dlang install dmd ; \
fi
RUN bash /tmp/install.sh -p /dlang install ${DLANG_VERSION}
```
seems to work better, though it's a little tricky to determine what version of dub is exactly being used. Something like `RUN bash /dlang/dub --version` doesn't work.

**Comment by Geod24** [comment]
Fixed
