### ISSUE TITLE
"dub test --single" inserts main

### ISSUE THREAD

**Issue by jmh530** [dlang/dub#2122]
It seems as if `dub test --single ...` inserts an empty main function, regardless of whether a main function is in there already. 

I put the text below in a file `foo.d` and ran with `dub run --single foo.d` and it prints "hello from main". However, if you run with `dub test --single foo.d`, then it has an error about two mains being defined. You have to remove the main function for it to print "hello from UT".
```
/++dub.sdl:
name "foo"+/

import std.stdio: writeln;

unittest
{
    writeln("hello from UT");
}

void main()
{
    writeln("hello from main");
}
```

**Comment by jmh530** [comment]
@WebFreak001 Ah. I had tried to create a normal default project and wasn't getting the error (b/c app.d). I hadn't realized what was driving it.

Thanks!

**Comment by PetarKirov** [comment]
I'd say that this is a frontend issue. Only compiler can reliably say whether `main` was already defined (e.g. in the presence of mixins) in the currently compiled module. I suggest we open a dmd issue instead.

**Comment by jmh530** [comment]
@PetarKirov Thanks.
