### ISSUE TITLE
main dub repo not updating

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#2128]
I tagged a [v0.5.2 release of ddbc in Feb](https://github.com/buggins/ddbc/releases) which is still not showing up on https://code.dlang.org/packages/ddbc

Any idea what's going on?

**Comment by shoo** [comment]
It may be related to issue #2123

By the way, there is a way to force the registry to propagate repository tags:
Log in -> [Manage packages](https://code.dlang.org/my_packages) -> enter page of package -> Push `Triger manual update`

**Comment by s-ludwig** [comment]
It seems like the last version of dub-registry that was deployed did not shuffle the update queue as it should. Since the update cycle has become much longer than it used to be, this is a necessary step to ensure fair update scheduling. I uploaded a fixed build a few hours ago and ddbc is now at 0.5.2.

**Comment by SingingBush** [comment]
awesome, thanks Sönke. I can't manually force registry updates for ddbc and hibernated as they were setup by [Vadim Lopatin](https://github.com/buggins). Should probably get them setup as a github organisation though. I don't think he plans to work on them again.

**Comment by Imperatorn** [comment]
> awesome, thanks Sönke. I can't manually force registry updates for ddbc and hibernated as they were setup by [Vadim Lopatin](https://github.com/buggins). Should probably get them setup as a github organisation though. I don't think he plans to work on them again.

Yeah, I tried contacting him by gh, email and FB but got no reply so far unfortunately...
