### ISSUE TITLE
Long paths on Windows: Cannot even use 260 chars

### ISSUE THREAD

**Issue by kinke** [dlang/dub#2143]
I'm seeing issues with long paths on a recent Windows 10, with LDC and Visual Studio 2019 in this case.

### Errors with the MS linker

E.g.:
```
LINK : fatal error LNK1181: cannot open input file '..\..\..\..\AppData\Local\dub\packages\unit-threaded-1.0.15\unit-threaded\subpackages\integration\.dub\build\library-debug-windows-x86_64-ldc_v1.27.0-beta1-sym1-55CBD351797D62157A88F9C8E869018F\unit-threaded_integration.lib'
```

Interesting because the relative path length is only 223, and the absolute one (`C:\Users\packer\AppData\…`) is 227 chars, nowhere near the 260 limit. **Edit**: Ah, `C:\Users\packer\dev\SIL\lang\test_plugin1\..\..\..\..\AppData\…` exceeds 260.

One workaround is using `-link-internally` with LDC, which makes it use the LLD linker integrated in LDC.

~~Another workaround is converting the relative path to `\\?\C:\Users\packer\AppData\…` (in the LDC cmdline issued by dub; these are simply forwarded to the linker). This could be done by LDC as well, but see below.~~ **Edit**: Nope, `link.exe` doesn't support the `\\?\` prefix for absolute paths > 260.

### Superfluous rebuilds

I was about to tackle this in LDC, but then came across another very annoying bit: such dependencies are rebuilt again and again, even if nothing has changed. Running dub with `-v` shows:
```
File ..\..\..\..\AppData\Local\dub\packages\unit-threaded-1.0.15\unit-threaded\subpackages\integration\.dub\build\library-debug-windows-x86_64-ldc_v1.27.0-beta1-sym1-4B9CC688E7DF7F085E7CCAC75893DE7E\unit-threaded_integration.lib doesn't exist, triggering rebuild.
```

(The file obviously exists.) So handling this in the compiler alone isn't sufficient.

**Comment by kinke** [comment]
So any path-shortening via relative paths starting with `..\` is counter-productive on Windows, as the expanded path is longer than the absolute one. I thought the culprit was https://github.com/dlang/dub/blob/4c1ce741d69316093d69721cdf73fc13666d6f83/source/dub/generators/build.d#L223 but it's not.

**Comment by PetarKirov** [comment]
@kinke @Geod24 @s-ludwig Wouldn't the correct solution be to use long Win32 paths? Specifically: 

1. Obtain the normalized absolute path 
2. Prepend prepend `\\?\` 
3. Call the Win32 File I/O functions with `W` suffix

( I haven't looked at the code in detail and It's been a while since I did Win32 programming or used Windows on a daily basis, so please correct if I'm wrong.)

**Comment by s-ludwig** [comment]
True, UNC paths would be the proper fix, although we'd have to try with all involved linkers and compilers whether they are able to handle those. It would also be nice though if Phobos would automatically perform that conversion, if needed.

**Comment by kinke** [comment]
As stated above, Microsoft's linker doesn't support long paths as of VS 2019. From the dub side, there are things that can be done, like using the wide I/O functions consistently. This issue was about dub further shrinking the max path length from 260 to ~220 though, depending on where your src repos are cloned to.

**Comment by WebFreak001** [comment]
@kinke you said Microsoft's linker doesn't support long paths anymore - do you mean it doesn't support UNC paths?

**Comment by kinke** [comment]
It has never supported them - IIRC, the `\\?\` prefix works, but doesn't make absolute paths > 260 chars work.

**Comment by kinke** [comment]
WTF - just tested it again to be sure, and it does seem to work now with an absolute path > 300 chars, not even requiring any prefix. This is on my native Win10 (21H1) box, the tests ~2 weeks ago were in a Win10 VM (20H2 or 20H1); I'm not sure whether the VS 2019 installation in the VM is totally up-to-date.

**Comment by kinke** [comment]
Seems independent from Windows, as it's not working with VS 2017 v15.9.25. VS 2019 v16.10 was a pretty recent upgrade IIRC, so I think it may have made the difference.

**Comment by PetarKirov** [comment]
Just FYI, there's an option on the Windows side to enable support for larger paths. I'm pretty sure that not much software is taking into an account, but perhaps this new VS update is forward compatible with it?
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by kinke** [comment]
I've checked the VS 2019 link.exe manifest, and it still doesn't specify `longPathAware`, so the registry/GPO hack shouldn't have any effect. (But hey, it's working anyway.) On a side note, I've also had to create the file in the console, as Windows Explorer apparently refuses to generate files with absolute paths > 260 chars...

---

I've also quickly looked into the dub file-exists check, which boils down to `std.file.exists`, which uses `GetFileAttributesW` IIRC; so that's apparenty a Phobos issue and would probably need to add the `\\?\` abomination.

**Comment by kinke** [comment]
Filed https://issues.dlang.org/show_bug.cgi?id=22059.
