### ISSUE TITLE
"Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847"

### ISSUE THREAD

**Issue by p0nce** [dlang/dub#2153]
### System information
DUB version 1.23.0, built on Oct 24 2020

### Bug Description

Consider the **dreadful** line:
```
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
```

I've been reading this warning message **for years**.
This is an irrelevant message 99.999% of the time.
My package.d doesn't even have unittests. Even if it had, when writing tests I make the test fail first to check.
I've found that this is a big usability difference, bad tools show lot of information to you. DUB is an excellent tool that should respect my time and deteriorating vision.

Please remove that message.

### How to reproduce?
`dub test` any DUB project.

### Expected Behavior
Clean output.

### Logs

This is the default output:
```
Generating test runner configuration 'intel-intrinsics-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using ldc2 for x86, x86_mscoff.
intel-intrinsics 1.4.2+commit.4.gc35c587: building configuration "intel-intrinsics-test-library"...
Linking...
Running .\intel-intrinsics-test-library.exe
```

Proposed change:
```
Generating test runner configuration 'intel-intrinsics-test-library' for 'library' (library).
Performing "unittest" build using ldc2 for x86, x86_mscoff.
intel-intrinsics 1.4.2+commit.4.gc35c587: building configuration "intel-intrinsics-test-library"...
Linking...
Running .\intel-intrinsics-test-library.exe
```
It is needlessly verbose, but at least all lines seem to be relevant to the task at hand.

EDIT:

Proposal 2: _let's dream_
```
"unittest" build (configuration: library) using ldc2 for x86, x86_mscoff...
All tests passed.
```

**Comment by rikkimax** [comment]
Compiler frontend version is known to dub, so this can be skipped for recent compiler frontend versions and it doesn't have to be turned off.

**Comment by WebFreak001** [comment]
is the issue actually fixed? The issue linked in the message is a cause for why it was omitted, but did the internal test runner from D actually fix it using the new traits? Additionally the currently popular unittest runners need to be checked if they still work with packages in there.

**Comment by p0nce** [comment]
The point is that DUB should not tell everyone all the time that a particular issue did exist at one point in DMDFE.

**Comment by dkorpel** [comment]
> But did the internal test runner from D actually fix it using the new traits?

No. I recently made a change that the console is not flooded with the same warning for every package (://github.com/dlang/dub/pull/2131) but the issue is still there.

**Comment by WebFreak001** [comment]
in the implementation you can see without having "tested" installed or a custom test module it just uses the DMD internal one:

https://github.com/dlang/dub/blob/7bf3584a4d003b1b1c5891fbed8f233dc2f7c2b0/source/dub/dub.d#L762
