### ISSUE TITLE
documented syntax for environment variables doesn't work in command directives

### ISSUE THREAD

**Issue by huglovefan** [dlang/dub#2192]
### System information
- **dub version**: dub 1.27.0
- **OS Platform and distribution**: windows, linux
- **compiler version**: dmd-2.098.0

### Bug Description

https://dub.pm/package-format-sdl.html#environment-variables  
https://dub.pm/package-format-json.html#environment-variables

> Inside of build setting values, it is possible to use variables using dollar notation. Any variable not matching a predefined name will be taken from the program environment. To denote a literal dollar sign, use `$$`.

so according to this, the variable syntax should be the about the same as in POSIX shell, but trying to use it that way in a command directive like `preRunCommands "echo $DUB_PACKAGE"` results in an error: `Invalid variable: DUB_PACKAGE`

what actually works on posix platforms is adding a second dollar sign like `preRunCommands "echo $$DUB_PACKAGE"`, and on windows you have to use percent signs, like `preRunCommands "echo %DUB_PACKAGE%"` but neither of these are obvious from the documentation (especially the windows one)

if i'm understanding it right, a way to fix this in the docs would be:

- clarify that the variables in the third table are real environment variables and use the syntax for the platform's shell (with posix requiring an extra dollar sign to skip dub's own variable expansion)
- remove the dollar signs from variable names in the third table to hint that they're different from those in the other tables which use `$` on all platforms

### How to reproduce?

1. do `dub init`
2. add this to dub.sdl: `preRunCommands "echo $DUB_PACKAGE"` or this to dub.json: `"preRunCommands": ["echo $DUB_PACKAGE"]`
3. do `dub run`

### Expected Behavior

should print the package name before running it

### Logs

```
% grep echo dub.sdl
preRunCommands "echo $DUB_PACKAGE"
% dub
Invalid variable: DUB_PACKAGE
```

**Comment by Geod24** [comment]
Using two dollars (`$$`) works.

>    "preRunCommands": ["echo $$DUB_PACKAGE"],

The documentation should be better though, and so should the error message.

**Comment by WebFreak001** [comment]
the workaround seems to only work on POSIX systems, presumably it calls spawnShell, which then substitutes `$DUB_PACKAGE` with the value. However this does not work on Windows and will break stuff there.

Sample output when using `$$DC`, while `$DC` works only if DUB is being started with a DC environment variable being set:
```
'$DC' is not recognized as an internal or external command,
operable program or batch file.
Command failed with exit code 1: $DC -run "D:\a\D-Scanner\D-Scanner/dubhash.d"
```
