### ISSUE TITLE
targetPath does not support platform customization

### ISSUE THREAD

**Issue by minexew** [dlang/dub#220]
This is what I'm trying to achieve:

```
    "targetType": "executable",
    "targetPath-osx": "app/osx",
    "targetPath-win32": "app/win32",
    "workingDirectory": "app"
```

However, when I try to `dub build` (v0.9.20) with this configuration, I get the error above. Shouldn't this be supported?

**Comment by WebFreak001** [comment]
configurations is the way to solve this.

Different "feature-sets" or things like that that can be specified multiple times are tracked in #128
