### ISSUE TITLE
Build subPackages as dynamicLibrary: "Dynamic libraries are not yet supported as dependencies - building as static library".

### ISSUE THREAD

**Issue by danykey** [dlang/dub#2206]
Hi, thanks for D language. Perhaps the issue is duplicated.

I had find some info about topic around and not clear why the "problem" not fixed already.
Not clear for what the restriction was made also.
I need compile many *.so files (where each lib(plugin) implements one common interface) and I will it load/unload dynamically.
The restriction blocks subPackages to compile as dynamicLibrary.

So, I just commented 4 lines to avoid the restriction in ```/source/dub/generators/generator.d``` lines 262 - 265 and now I gets .so files without any side effects:
```
else if (tt == TargetType.dynamicLibrary) {
	logWarn("Dynamic libraries are not yet supported as dependencies - building as static library.");
	tt = TargetType.staticLibrary;
}
```
My suggestion is keep warning only without reassignment TargetType.

**Comment by rikkimax** [comment]
I think that this might be a good step towards getting shared library support to a good level in D.

Dub will also need to copy inport libraries (Windows at the very least have these).

**Comment by rikkimax** [comment]
Oh and Optlink needs to be told to generate the import library (I don't think it does this automatically).
