### ISSUE TITLE
Add a "run" command to replace rdmd

### ISSUE THREAD

**Issue by skyline131313** [dlang/dub#2215]
Projects like dfmt are using it, it would be useful to have a command for building and then running a command using the current compiler selected by dub. This way it allows for the build to be done in a compiler agnostic way. Having trouble building dfmt because it relies on rdmd, which doesn't exist on ARM.

https://github.com/dlang-community/dfmt/issues/472

**Comment by WebFreak001** [comment]
Dub already has a feature for doing this (`dub --single`) but it still has some issues with caching. (almost never reuses the cached executable, but builds it again instead)

Code: https://github.com/dlang/dub/blob/12708c7ab3bebfa0a1f2551ea6a837ebe466fc57/source/dub/dub.d#L396

Docs: https://dub.pm/advanced_usage.html

Additionally you can use `$DC -run file.d` as preBuildCommand to make the compiler build and run (supported by DMD and LDC by now, GDC maybe also getting it? @ibuclaw ) This does not however include any caching at all and needs to be cached by DUB somehow. `preBuildCommands` might already not be called if no sources changed though I think.

**Comment by skyline131313** [comment]
`$DC -run file.d` would that work on Windows?

**Comment by WebFreak001** [comment]
not always, due to #2192 

fix incoming though
