### ISSUE TITLE
Build a static library and all its sub-dependencies

### ISSUE THREAD

**Issue by rtbo** [dlang/dub#2224]
When building a Dub static library (e.g. `dub build vibe-d:http`), Dub will build the static library itself, but not the dependencies of this library (simply because I think it is not needed).

Is it possible to get Dub build the complete chain with a single command?
This is useful when using Meson. In a Meson build, if one depends on say `vibe-d:http`, Meson expect to find all the needed Dub libraries already built. 
Running `dub build` for a dozen of packages is quite tedious and error prone as some packages will require a specific configuration.
I wrote a [script](https://gist.github.com/rtbo/52ca40f119e0b6c892cbfaebbab4f49b) to support that, but it would be better if it comes from Dub.

### System information

- DUB version 1.27.0
- Arch Linux
- DMD v2.098.1

**Comment by rtbo** [comment]
See https://github.com/mesonbuild/meson/pull/10019

**Comment by rtbo** [comment]
My script is now a dub package to ease its use for Meson users: [dub-build-deep](https://code.dlang.org/packages/dub-build-deep).

**Comment by MrcSnm** [comment]
Hey guys @WebFreak001 @mathias-lang-sociomantic could you take a look on that?
It seems it also solves the issue I've just opened which I have been in need: https://github.com/dlang/dub/issues/2687
I would like to get that merged ASAP for the next dub release being finally fixed for my engine
