### ISSUE TITLE
https://code.dlang.org/ link to Forum is Broken

### ISSUE THREAD

**Issue by vnayar** [dlang/dub#2235]
### System information
- **OS Platform and distribution**: Firefox 98.0.1 on Linux Ubuntu 20.04.4 LTS

### Bug Description
On the website, https://code.dlang.org/, the link from the menu "About" > "Forums" leads to https://forum.rejectedsoftware.com/groups/rejectedsoftware.dub

However, this site only shows:
```
404 - Not Found

Not Found

Internal error information:
No routes match path '/groups/rejectedsoftware.dub'
```

**Comment by adamdruppe** [comment]
works for me maybe it was already fixed or i guess i could hve it in cache

**Comment by rikkimax** [comment]
It hasn't been fixed, DNS is pointing to the wrong thing.

On the 26th of last month, the A record of rejectedsoftware.com was changed. On the 8th of this month, the CNAME for the subdomain was changed. It's pointing to the wrong server.

**Comment by s-ludwig** [comment]
I can't see what's wrong, "forum.rejectedsoftware.com" points to "bildhuus.com", which is 188.68.61.5. That is the correct server. I also get the right content and the right SSL certificate. For those who get the wrong result, which IP address do you get back?

**Comment by rikkimax** [comment]
Remote Address: [2a03:4000:e:14:a8b5:c0ff:fe53:189b]:443

It is showing Aspect's site.

**Comment by s-ludwig** [comment]
Okay, so the Nginx site configuration was missing the IPv6 listener. Can you confirm it works right now?

**Comment by rikkimax** [comment]
Confirmed, thanks!

**Comment by rikkimax** [comment]
1. Remote Address:
   [2a03:4000:e:14:a8b5:c0ff:fe53:189b]:443

It is showing Aspect's site.
