### ISSUE TITLE
preGenerateCommands doesn't work in dub dependency

### ISSUE THREAD

**Issue by atilaneves** [dlang/dub#2238]
When a source file to be built is generated, using preGenerateCommands works, and it gets included in the build, but not if it's a library dependency of *another* dub package. To reproduce:

```sdl
// oops/dub.sdl
name "oops"
targetType "library"
preGenerateCommands "cd $PACKAGE_DIR/gen && dub --single gen.d"
```

```d
// oops/gen/gen.d
#!/usr/bin/env dub
/+ dub.sdl:
name "gen"
targetType "executable"
+/

void main() {
    import std.file : thisExePath, write;
    import std.path : dirName, buildPath;
    const path = buildPath(thisExePath.dirName, "..", "source", "foo.d");
    write(path, "module foo;\nint answer() { return 42; }\n");
}
```
```d
// oops/source/oops.d
import std.stdio;
import foo;

void stuff() {
    answer.writeln;
}
```

```sdl
// ledep/dub.sdl
name "ledep"
dependency "oops" path="../oops"
```

```d
// ledep/source/app.d
import oops;

void main() {
    stuff;
}
```

When trying to build "ledep", the preGenerateCommands for "oops" is run, but `foo.d` isn't included in the oops build, yielding a linker error about the missing symbol `foo.answer`.

**Comment by WebFreak001** [comment]
hmm the code right here should guard against that: https://github.com/dlang/dub/blob/master/source/dub/generators/generator.d#L171-L173 but it might not be properly run for dependencies
