### ISSUE TITLE
dub generate x86 visuald project build error 

### ISSUE THREAD

**Issue by jpl111** [dlang/dub#2243]
### System information

- **dub version**:  dub 1.28.0
- **OS Platform and distribution**:  Windows 10(x64)
- **compiler version** : dmd.2.099.1

### Bug Description
I use the command "dub generate visuald --arch=x86"  to generate visual project,
then i open then solution with  vs2010  and build it, a link error occurred, The linker can't find something,
if i use command "dub generate visuald" genetate project , it  build successed,I don't known why.

**Comment by WebFreak001** [comment]
if this issue still persists, please reopen with logs
