### ISSUE TITLE
dependency ignored under buildType definition in dub.sdl

### ISSUE THREAD

**Issue by Timoses** [dlang/dub#2246]
### System information

- **dub version**: (e.g. dub 1.3.0) 
    DUB version 1.26.1, built on Aug  9 2021
- **OS Platform and distribution**: (e.g. Windows 10, Linux Ubuntu 16.04) 
   > cat /etc/os-release  | grep PRETTY
   PRETTY_NAME="Fedora 34 (Workstation Edition)"
- **compiler version** (e.g. dmd-2.074.1)
  > dmd --version
  DMD64 D Compiler v2.097.2

### Bug Description
Defining a `dependency` for the `buildType "debug"` is ignored by *dub*.
The dependency is not compiled in.

### How to reproduce?
```
mkdir test && cd test

cat <<EOF > dub.sdl
name "Test"

buildType "debug" {
    dependency "vibe-core" version="~>1.18.1"
}
EOF

mkdir source

cat <<EOF > source/app.d
import std.stdio;

import vibe.core.log;

void main() {
    writeln("Hello, World!");
}
EOF

dub build
```

### Expected Behavior
Since `dub build` by default runs with the `debug` buildType it should read in the dependency and compile successfully.
Running `dub build --build=debug` neither works.

### Logs
```
WARNING: DUB package names should always be lower case. Please modify the "name" field in /home/timoses/dotfim/test/test/test/test/dub.sdl accordingly. You can then add 'targetName "Test"' to keep the current executable name.
Performing "debug" build using /usr/bin/dmd for x86_64.
Test ~master: building configuration "application"...
source/app.d(3,8): Error: module `log` is in file 'vibe/core/log.d' which cannot be read
import path[0] = source/
import path[1] = /usr/include/dmd/phobos
import path[2] = /usr/include/dmd/druntime/import
/usr/bin/dmd failed with exit code 1.
```

**Comment by rikkimax** [comment]
This matches the documented behavior.

> The existing build types can be customized and new build types can be added using the global buildType directive. Any of the low level [build settings](https://dub.pm/package-format-sdl.html#build-settings) (excluding "dependencies", "targetType", "targetName", "targetPath", "workingDirectory", "subConfigurations") can be used inside those.

**Comment by Timoses** [comment]
> This matches the documented behavior.
> 
> > The existing build types can be customized and new build types can be added using the global buildType directive. Any of the low level [build settings](https://dub.pm/package-format-sdl.html#build-settings) (excluding "dependencies", "targetType", "targetName", "targetPath", "workingDirectory", "subConfigurations") can be used inside those.

Oh wow, I was sure I read through that. Must have overread 'dependencies' in the list.

Then I guess this issue can be closed.

And I suppose I do still need an extra `configuration` section and always have to run `dub build --config=debug` if I don't want to have `vibe-core` compiled into my `release`?!
