### ISSUE TITLE
DUB on WSL

### ISSUE THREAD

**Issue by p0nce** [dlang/dub#2249]
### System information

- **dub version**: 1.19.0-1build2
- **OS Platform and distribution**: Windows 10 but within WSL Ubuntu
- **compiler version:** ldc 1.20.1

### Bug Description

Can't run dub on WSL, after a `sudo apt install dub`

### How to reproduce?

- Install WSL Ubuntu on Windows
- run `sudo apt install dub`
- type `dub`

### Expected Behavior

DUB running.

### Logs

The error message displayed is:
`dub: symbol lookup error: dub: undefined symbol: _D3std3net4curl4HTTP9__mixin376onSendMFNdDFAvZmZv`

**Comment by rikkimax** [comment]
The method in question is:

https://github.com/dlang/phobos/blob/master/std/net/curl.d#L2155

Note: it is not templated or being used by a template it absolutely should exist. The only thing interesting about it is that it is being used via a mixin template.

This is a bug on the compiler side, not dub.

**Comment by veelo** [comment]
1. Ldc 1.20 is two years old now, Dub 1.19 is two and a half years old soon. Wasn't there an issue with symbol mangling of Phobos one time, causing link errors?
2. Can Ldc be used successfully by hand?
3. This looks like a bug in the compiler installation, it is not necessarily Dub's fault, right?
4. Does a manual installation of recent Ldc work? It includes Dub. https://github.com/ldc-developers/ldc/releases.
5. Could an installation in WSL be interfering with an installation in Windows natively?

**Comment by Geod24** [comment]
This is not a dub issue, but an issue with the packaging. I'm using dub on WSL on a daily basis and it works.
