### ISSUE TITLE
Define support for advanced target architecture/CPU specifications

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#228]
Currently there are only two valid values for the `--arch=` switch: x86 and x86_64. Compilers other them DMD support a variety of architectures, CPUs and architecture specific options (for LDC: `-march=`, `-mcpu=`, `-mattr=`). The first step is to define how to map this to DUB and the second step is how to map compiler specific values to the D/DUB specific ones (as used for [platform suffixes]()).

Possibilities:
1. Directly forward `--arch=`, `--cpu=`, `--arch-attribs` switches to the compiler, if supported. The values used for these switches would be completely compiler dependent.
   - Mapping this to the D/DUB specific values would require invoking the compiler once with a small dummy program that outputs those values as determined by the proper `version` statements.
   - Possibly will be an issue when the linker needs to be invoked separately, but has a different interface for specifying the target machine
2. Define a set of possible values where everything is encoded (e.g. `--arch=armv6-hardfloat-tegra3`) and map these to the proper compiler specific flags.
   - This would be the simplest solution, where the mapping is trivial, but it also suffers from an exponential explosion of possible values or from a lack of values for advanced use cases. 
3. Like the first option, but use a set of standard values that is mapped to the compiler specific values
   - The mapping is known a priori, but in contrast to the first option, this requires constant maintenance work to keep the list of supported values up to date.
   - On the other hand it has the advantage of providing a single standard for specifying the architecture, so it is not necessary to learn them anew for every different compiler

**Comment by epi** [comment]
After some recent experiences with various cross-build configurations, I think the following might be a workable solution:
4. Configure target platforms in user- or system-wide json files, e.g. ~/.dub/compilers.json

Rationale:
While native compilers are not so difficult to detect and map options to, cross-compilers are a different story. GDC is usually built to compile for one architecture (arch versions and specific features can be tweaked from command line) and OS (i.e. target libraries; can also be changed by linker options). LDC, on the other hand, can compile for any target that was enabled in LLVM build, but it requires detailed options to be specified in the command line.
One would usually keep the various cross-compilers somewhere in /opt or one's home directory, target OS libraries could be mapped via NFS or sshfs somewhere else, etc.
Making dub detect the appropriate locations and settings automatically is hardly possible.
Specifying all of them in dub command line for each build would be impractical.

So the proposed idea is:

Without any options specifying the target platform, dub would build with the default native compiler, either just one of "dmd", "gdc" or "ldc2" found in current $PATH, which could be overridden with a "default" entry in compilers.json.

Specifying "--compiler=xxx" could first attempt to read compilers.json to find "xxx".
"xxx" doesn't even need to be strictly standardized (though sticking to the traditional `<arch><sub>-<vendor>-<sys>-<abi>-<compiler>` won't probably hurt anyone), it's up to the user to configure their cross-compilers. If "xxx" is found in compilers.json, dub will use the path to the compiler executable and all compiler and linker options from there. The mapping between dmd, gdc and ldc options should probably still be done by dub as it is now, though.
If "xxx" is not found in compilers.json, the current behaviour can be still used.

Example that I'd use instantly (options are not exact, it's just to give an idea).
```json
{
    "compilers": {
        "arm-linux-gnueabihf-gdc": {
            "path": "/opt/arm-gdcproject-linux-gnueabihf/bin/arm-gdcproject-linux-gnueabihf-gdc"
        },
        "ldc": {
            "path": "/opt/ldc/bin/ldc2"
        },
        "arm-tizen-linux-gnueabi-ldc2": {
            "path": "/opt/ldc/bin/ldc2",
            "dflags": [
                "-mtriple=armv7l-tizen-linux-gnueabi",
                "-float-abi=softfp",
                "-I/opt/tizen/dimport",
                "-gcc=/opt/armv7l-tizen-linux-gnueabi/bin/armv7l-tizen-linux-gnueabi-gcc"
            ],
            "ldflags": [
                "-L/opt/tizen/lib"
            ]
        },
        "some-fancy-cortex-m-board-ldc2": {
            ...
        }
    },
}
```

What do you think? Has this form been already discussed elsewhere?

**Comment by epi** [comment]
Here's some rudimentary implementation of the proposed feature as described so people can try it out.
https://github.com/epi/dub/commit/425527d0fec21d3f2abfedd83375a6d606da5e96

Some open questions are:
- whether this is the preferable solution to this problem (it satisfies all my needs, but others' opinion is needed)
- if so, is the implementation appropriate? E.g. probably it should be possible to pass lflags directly to the compiler binary without prefixing them with -L, or some other issues.

**Comment by s-ludwig** [comment]
Initial sketch: https://github.com/dlang/dub/tree/issue_228_target_triples
Development progress: https://github.com/epi/dub/commits/issue_228_target_triples

**Comment by andre2007** [comment]
Implemented https://github.com/dlang/dub/pull/1755
