### ISSUE TITLE
Support custom paths for the default installation folder

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#229]
Currently all packages are installed to `~/.dub/packages/*` by default, or `%AppData%\dub\packages\*` on Windows. A setting in the `~/dub/settings.json` fie should be made available to change that default.

**Comment by John-Colvin** [comment]
See http://forum.dlang.org/post/sgtfnbmwtfaksffhqazf@forum.dlang.org and responses.

**Comment by jansengb** [comment]
Low priority? It's easy to move the directory and just use a symbolic link in the standard location. Maybe just add a comment to this effect in the documentation?

**Comment by wilzbach** [comment]
See also: https://github.com/dlang/dub/issues/839
