### ISSUE TITLE
Add *.pdb to .gitignore on dub init

### ISSUE THREAD

**Issue by lempiji** [dlang/dub#2383]
The pdb file is now copied on Windows, but `.gitignore` does not include this.

`*.exe` is already written in `.gitignore`, I think `*.pdb` should be as well.

see also: https://dlang.org/changelog/2.099.0.html#pdb

**Comment by rikkimax** [comment]
``*.lib`` may already be included (didn't check).

``*.exp`` should also be included if it hasn't been.
