### ISSUE TITLE
Replace MD5 with more secure hash in computeBuildName

### ISSUE THREAD

**Issue by nordlow** [dlang/dub#2385]
Shall we replace MD5 with SHA1 or SHA256 or some other hash in

```d
string computeBuildName(string config, in GeneratorSettings settings, const string[][] hashing...)
{
	import std.digest;
	import std.digest.md;

	MD5 hash;
	hash.start();
	void addHash(in string[] strings...) { foreach (s; strings) { hash.put(cast(ubyte[])s); hash.put(0); } hash.put(0); }
	foreach(strings; hashing)
		addHash(strings);
	auto hashstr = hash.finish().toHexString().idup;

    return format("%s-%s-%s-%s-%s_v%s-%s", config, settings.buildType,
			settings.platform.platform.join("."),
			settings.platform.architecture.join("."),
			settings.platform.compiler, settings.platform.compilerVersion, hashstr);
}
```

? If so, shall I truncate the result hash hex string to the same number of digits as MD5?

Phobos' module `std.digest.sha` currently defines

```d
alias SHA1 = SHA!(512, 160);  /// SHA alias for SHA-1, hash is ubyte[20]
alias SHA224 = SHA!(512, 224);  /// SHA alias for SHA-224, hash is ubyte[28]
alias SHA256 = SHA!(512, 256);  /// SHA alias for SHA-256, hash is ubyte[32]
alias SHA384 = SHA!(1024, 384); /// SHA alias for SHA-384, hash is ubyte[48]
alias SHA512 = SHA!(1024, 512); /// SHA alias for SHA-512, hash is ubyte[64]
alias SHA512_224 = SHA!(1024, 224); /// SHA alias for SHA-512/224, hash is ubyte[28]
alias SHA512_256 = SHA!(1024, 256); /// SHA alias for SHA-512/256, hash is ubyte[32]
```

Which one shall we pick?

Ping, @kinke @Geod24 @John-Colvin.

**Comment by Geod24** [comment]
I have a preference for Blake2b. I think we should decide on a unified function to use for the build ID and the dependency checksum.

**Comment by Geod24** [comment]
> Blake2b is not part of Phobos. I vote for SHA-256 in the mean time to get this in. We can always switch to Blake later on.

I don't see the urgency here though? The current hash function is good enough, the only reason I'm considering changing it (and this is just my personal opinion) is that we want to add checksums and it's a good time to revisit the hash function.

But if we're putting more focus on security, there's a lot of places where we can have a higher impact than changing the hash function.

Regarding SHA-256, it is susceptible to length extension attack which Blake2b isn't.

**Comment by Geod24** [comment]
Ah, but we're using MD5. Okay let's move to S256 first.
