### ISSUE TITLE
Make build metadata visible to packages

### ISSUE THREAD

**Issue by Herringway** [dlang/dub#2397]
It would be nice for a package to be able to access the same data available via `dub describe`'s output at compile time. This could enable a package to be able to report its own version as well as those of its dependencies, for example. This could be achieved through an autogenerated module, like `dub.build` or something along those lines.
While it is possible to achieve this through a pre-build step that processes `dub describe`'s output, it can be pretty unreliable to do it this way.

**Comment by Geod24** [comment]
Agreed. There is already an issue for it, although it focuses on the more obvious use case of the package version: #1438
Closing a duplicate.
