### ISSUE TITLE
Rename --colors to --color before next release?

### ISSUE THREAD

**Issue by nordlow** [dlang/dub#2398]
At https://github.com/dlang/dub/pull/2268, what is the reason for picking the naming `--colors` instead of `--color`?

IRC, --color is more established naming in other (GNU) CLI tools such as `ls` and `grep`.

Ping, @kinke @Geod24 @veelo.

**Comment by Geod24** [comment]
That's a good point. I'd be in favor of the rename. CC @WebFreak001 .

**Comment by veelo** [comment]
Indeed, it should be `--color`.

**Comment by WebFreak001** [comment]
sure, sounds good

**Comment by nordlow** [comment]
See https://github.com/dlang/dub/pull/2399.
