### ISSUE TITLE
Shall we rename -color=automatic to -color=auto for consistency with dmd flag -color[on,off,auto]?

### ISSUE THREAD

**Issue by nordlow** [dlang/dub#2411]
Or allow both `automatic` and `auto`?

Ping, @veelo.

**Comment by veelo** [comment]
The reason it is not `auto` is because that is a D keyword, and thus cannot be an enum member.

Since it is the default nobody should need to type `automatic`. We could consider to not document it by changing
```d
		args.getopt("color", &color_mode, [
			"Configure colored output. Accepted values:",
			"  automatic: Colored output on console/terminal,",
			"             unless NO_COLOR is set and non-empty (default)",
			"         on: Force colors enabled",
			"        off: Force colors disabled"
			]);
```
into something like
```d
		args.getopt("color", &color_mode, [
			"Override colored output. By default output is colored on the console/terminal, unless NO_COLOR is set and non-empty. Accepted values:",
			"         on: Force colors enabled",
			"        off: Force colors disabled"
			]);
```

**Comment by nordlow** [comment]
> The reason it is not `auto` is because that is a D keyword, and thus cannot be an enum member.

I'd say the reason is rather that the argparse library we are using doesn't support that rather it not being possible in D...

**Comment by veelo** [comment]
Of course.

**Comment by nordlow** [comment]
It's better to add an alias later on. Ok?

**Comment by nordlow** [comment]
Ok, I'll leave this issue open then. A better long-term solution would be to make args.getopt more flexible in that it can handle parameters and parameter values being D keywords.

**Comment by Geod24** [comment]
Fixed in https://github.com/dlang/dub/pull/2552
