### ISSUE TITLE
Using alias Path = NativePath

### ISSUE THREAD

**Issue by nordlow** [dlang/dub#2427]
Currently dub.internal.vibecompat.inet.path contains

```d
deprecated("Use NativePath instead.")
alias Path = NativePath;
```

. Why is that?

`NativePath` wastes more than twice twice the number of characters.

I strongly prefer using `Path` over `NativePath` in `dub` to reduce code size.

For comparison see [std::path::Path](https://doc.rust-lang.org/std/path/struct.Path.html).

Ping, @s-ludwig @Geod24.

**Comment by WebFreak001** [comment]
consistency with vibe.d, kinda important for the dub-registry / vibe.d usage
