### ISSUE TITLE
dub upgrade chokes on already built packages

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#244]
for example:

```
Error executing command upgrade: Alien files found in '/home/space/phujfj/.dub/packages/zeromq-master', needs to be deleted manually.
```

This is from a clean ~/.dub, followed by a dub build of a dependent package, followed by a dub upgrade of said package.

**Comment by s-ludwig** [comment]
This check has been removed a while ago (#377), but interestingly all the framing logic is still there, including the `--force-remove` switches. I'll undocument the switch and mark the associated APIs for scheduled deprecation.
