### ISSUE TITLE
Remove dependency on `libs "curl"`

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub#2512]
Use-case for e.g. dub-registry or others, see #1558

I'd suggest we could use the `requests` package from DUB, which is an excellent library for doing HTTP requests.

**Comment by Geod24** [comment]
Do we need the `libs` statement ? Phobos will load it dynamically...

**Comment by WebFreak001** [comment]
not sure what that libs statement was used for.

imo it might make sense to just use requests in general too.

**Comment by Geod24** [comment]
It's just pulling a hard dependency by linking it. But Phobos uses dlopen.
requests is a bigger change than removing a line.

**Comment by WebFreak001** [comment]
again, for actually not needing curl, continued here: #2524
