### ISSUE TITLE
Extensible dub

### ISSUE THREAD

**Issue by simendsjo** [dlang/dub#252]
This is just a thought and might not be a good idea.

Dub has quite some special knowledge, like `vibe.d`, `mono-d`, `visual-d` and `rdmd`.
This makes it a very handy tool, but it also requires every tool to be added in dub directly.

My thought is to forward these to special binaries; `dub-build-*` and `dub-init-*`. This way you can easily extend dub for custom libraries/projects without touching dub itself.
`dub-init-monod` would thus create a `mono-d` project etc.

**Comment by WebFreak001** [comment]
moved into #2210
