### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [dlang/dub#2535]
👋 it looks like `1.30.0` did not get marked as latest release, raising this issue to confirm if that is a miss in the release process, thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/115757

**Comment by Geod24** [comment]
Done, thanks!
https://github.com/dlang/dub/releases/tag/v1.30.0

**Comment by chenrui333** [comment]
That was quick, big thanks!! :D

**Comment by chenrui333** [comment]
That was quick, big thanks!! :D
