### ISSUE TITLE
Potential speed up: move getBestPackage to dub-registry

### ISSUE THREAD

**Issue by rikkimax** [dlang/dub#2551]
This is a potential speed-up for anyone who wants to give it a go.

Logic: https://github.com/dlang/dub/blame/1330c9d7bfee19421ec23b3034d2584f6142f8c9/source/dub/packagesuppliers/packagesupplier.d#L56

Used in maven (which we don't control) and https://github.com/dlang/dub/blob/1330c9d7bfee19421ec23b3034d2584f6142f8c9/source/dub/packagesuppliers/registry.d#L57

Registry lookup is quite expensive (dub gets a lot faster if you disable registry lookup).

So if we can half the number of lookups, that'll be a pretty decent speed-up.

**Comment by Geod24** [comment]
This is not in the hot path though (at least shouldn't be). A regular `dub build` (the most common, by far) should seldom query the registry, if at all.

**Comment by Geod24** [comment]
As mentioned in my previous comment, the speedup here is not significant. A regular `dub build` should not touch the registry.
