### ISSUE TITLE
App's CWD changed when running DUB with `--root=xyz`

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub#2582]
Since #2562 running applications using `dub run --root=xyz` will now run them in a different working directory, which could be considered a breaking change. Should we add a workaround to make it behave like the old way again? @Geod24 

Sample setup:
```
~/app/
    dub.sdl
```

the source code just printing the working directory.

before:
```
cd ~
dub run --root=app
# prints ~
```

now:
```
cd ~
dub run --root=app
# prints ~/app/
```

**Comment by WebFreak001** [comment]
I'll add a PR to change back the `--root=` behavior to the old one (inherit working directory from DUB)

Both with old and new DUB you are still able to explicitly set `"workingDirectory": "."` in the dub.json to make it behave like it does now, so I guess that's how people could use it right now. It's an edge case, but not a very uncommon one.

**Comment by Geod24** [comment]
> will now run them in a different working directory

It really is a bug fix, but...

> I think we should not add breaking changes like this, that's why I'll change the behavior back.

Unfortunately yes. How should we re-introduce this, though ?

**Comment by WebFreak001** [comment]
I found out setting "workingDirectory" to "." explicitly in your dub.json/dub.sdl caused the behavior also with previous DUB versions to be like it is with the current stable version.

That's why I think it's fine to revert this change permanently and instead tell people to set that in their recipe if they want the behavior of using the package root as working directory in every case.

I think there are use cases when to run from the current cwd, e.g. `dub run --root=/tools/makeSomething` in random arbitrary folders, instead of installing a binary on the system, e.g. in a CI environment from multiple folders it's quite easy to just use the cwd instead of using an argument.

**Comment by Geod24** [comment]
I think having `--root` not being respected for apps CWD is wrong and counter-intuitive. `--root` should behave 'as-is' you `cd` in a directory before running the command.
We also have means to build something *not* in the current directory, e.g. `dub build vibe-d`. I never liked that we conflate both local package and shared packages commands, but we have to be consistent, at the very least.
