### ISSUE TITLE
About tag 1.31.1

### ISSUE THREAD

**Issue by chenrui333** [dlang/dub#2601]
👋 Just want to raise this issue to confirm whether 1.31.1 is the latest release. If so, would you mind creating a latest release notes for it? (currently it still points to 1.30.0) Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/123498

**Comment by WebFreak001** [comment]
releases tagged (auto-generated description from PRs)

The nicer manually written changelog files are magically processed, cleared and inserted into https://dlang.org/changelog.html, where you can manually copy them from now. I think @ibuclaw could probably better tell you how they actually work.

**Comment by chenrui333** [comment]
It would best to avoid re-tagging, as it would cause some downstream package management pain. :)

> The nicer manually written changelog files are magically processed, cleared and inserted into https://dlang.org/changelog.html,

What would be exact url to look at? I could not see the changelog for dub.

**Comment by chenrui333** [comment]
anyway, thanks for the latest release tagging. it is helpful for me.

**Comment by chenrui333** [comment]
Also the sha did not get changed for 1.31.1, not quite sure what you mean by re-tagging. But I am gonna proceed on the homebrew side version bump now. Thanks again!

**Comment by WebFreak001** [comment]
sorry, I meant I attached release information to the existing tags on github, so they appear in the releases tab and not just under tags.

**Comment by WebFreak001** [comment]
> It would best to avoid re-tagging, as it would cause some downstream package management pain. :)
> 
> > The nicer manually written changelog files are magically processed, cleared and inserted into [dlang.org/changelog.html](https://dlang.org/changelog.html),
> 
> What would be exact url to look at? I could not see the changelog for dub.

since dub gets released alongside with the compiler, we pretty much just release on every compiler cycle, even if theoretically we have standalone capabilities.

You can for example find the latest dub changelog in https://dlang.org/changelog/2.102.1.html under "Dub changes", but it won't tell you for which dub version that is and you don't have any way to look up the compiler changelog per dub version.
