### ISSUE TITLE
Error Failed to download package colored from https://code.dlang.org/packages/colored/0.0.31.zip

### ISSUE THREAD

**Issue by katyukha** [dlang/dub#2645]
### System information
- **dub version**: It seems to be  1.31.1, but not sure
- **OS Platform and distribution**: Ubuntu 22.04, Ubuntu 20.04
- **compiler version**: ldc-1.32.0, dmd-2.102.2

### Bug Description
Frequent failure on github actions to fetch package colored
Just take a look at following job runs:
- https://github.com/katyukha/Odood/actions/runs/5038813705/jobs/9036560891
- https://github.com/katyukha/Odood/actions/runs/5012784594/jobs/8985140110
- https://github.com/katyukha/Odood/actions/runs/4945204536/jobs/8841601838
- https://github.com/katyukha/Odood/actions/runs/4916058738/jobs/8779336063
- https://github.com/katyukha/Odood/actions/runs/4893355700/jobs/8736219952

After job restart everything seems to be ok, but sometimes it may require two resstarts.
Some times it works find from first run.

And what is interesting - is that everyt time it fails on same package.

### How to reproduce?

Periodically this happens on Github Actions.

### Expected Behavior

System should automatically retry to fetch package.

### Logs

```
Run dub test -b unittest-cov -c unittest-silly --override-config=pyd/python38
  dub test -b unittest-cov -c unittest-silly --override-config=pyd/python38
  shell: /usr/bin/bash -e {0}
  env:
    DC: dmd
    LD_LIBRARY_PATH: /opt/hostedtoolcache/dc/dmd-[2](https://github.com/katyukha/Odood/actions/runs/4893355700/jobs/8736219952#step:9:2).102.2/x64/dmd2/linux/lib64
    POSTGRES_HOST: localhost
    POSTGRES_PORT: [3](https://github.com/katyukha/Odood/actions/runs/4893355700/jobs/8736219952#step:9:3)27[6](https://github.com/katyukha/Odood/actions/runs/4893355700/jobs/8736219952#step:9:6)[8](https://github.com/katyukha/Odood/actions/runs/4893355700/jobs/8736219952#step:9:8)
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
     Warning Sub package odood:lib, referenced by odood dub.package_.Package must be referenced using the path to its base package
     Warning Sub package odood:cli, referenced by odood dub.package_.Package must be referenced using the path to its base package
    Fetching tinyendian 0.2.0 (getting selected version)
    Fetching dpq 0.11.6 (getting selected version)
    Fetching pyd ~master (getting selected version)
    Fetching requests 2.0.[9](https://github.com/katyukha/Odood/actions/runs/4893355700/jobs/8736219952#step:9:9) (getting selected version)
    Fetching colored 0.0.31 (getting selected version)
Error Failed to download package colored from https://code.dlang.org/packages/colored/0.0.31.zip
Error: Process completed with exit code 2.
```

**Comment by Geod24** [comment]
Is this subsiding ? I assume that was a network error ?
