### ISSUE TITLE
1.33.0 tag did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [dlang/dub#2657]
👋 it looks like 1.33.0 tag did not get marked as latest release due to [some action run failure](https://github.com/dlang/dub/actions/runs/5153629948), create this issue to raise some awareness.

relates to https://github.com/Homebrew/homebrew-core/pull/132670

**Comment by WebFreak001** [comment]
oh it just didn't get tagged because nobody made a release, only a tag. I'll create a release for this.

**Comment by chenrui333** [comment]
no worries, thanks for publishing the release. 🙏
