### ISSUE TITLE
1.33.1 release job failed

### ISSUE THREAD

**Issue by chenrui333** [dlang/dub#2670]
👋 it looks like 1.33.1 release job failed, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/135565

**Comment by WebFreak001** [comment]
uhh the linked failed job is LDC on alpine, we don't have any release jobs in this repo, since dub is usually vendored / built by the DMD or LDC releases.

Would just close this as duplicate for #2556 if you want prebuilt releases

**Comment by chenrui333** [comment]
I see, with that being said, is 1.33.1 tag the latest release tag? Thanks!

**Comment by WebFreak001** [comment]
@ibuclaw can you also add to the script that it creates a release on github? There have been several issues opened that the latest tag didn't have a release on dub recently. #2670 #2657 #2601

**Comment by chenrui333** [comment]
> @ibuclaw can you also add to the script that it creates a release on github? There have been several issues opened that the latest tag didn't have a release on dub recently. #2670 #2657 #2601
> 
> It would also be a good place to copy the changelog content into

sorry about the issues that I created 😅 

basically, I am just looking for the release notes (it would be more semantics from the downstream package manager perspective)

anyway, I will go ahead releasing the change on the homebrew side.

Thanks again!

**Comment by ibuclaw** [comment]
> @ibuclaw can you also add to the script that it creates a release on github? There have been several issues opened that the latest tag didn't have a release on dub recently. #2670 #2657 #2601
> 
> It would also be a good place to copy the changelog content into

This is a github feature, not git?

**Comment by ibuclaw** [comment]
> > It would also be a good place to copy the changelog content into
> 
> This is a github feature, not git? 

Maybe https://cli.github.com/manual/gh_release
