### ISSUE TITLE
`dub fetch` for non-existent package name should have better error message

### ISSUE THREAD

**Issue by ntrel** [dlang/dub#2679]
### System information

- **dub version**: 1.33.0
- **OS Platform and distribution**: Linux Mint 21
- **compiler version** dmd v2.104.0

### How to reproduce?

```
nick@nmt-pc:~/git/english$ dub fetch libssl-dev 
             Getting a release version failed: (1): Error: Got JSON of type null_, expected object.
             Retry with ~master...
Error (1): Error: Got JSON of type null_, expected object.
```
### Expected Behavior

The code should show an error like:

    Error: No package `libssl-dev` found

**Comment by Geod24** [comment]
Fix: https://github.com/dlang/dub/pull/2763
