### ISSUE TITLE
[Feature Request] - Pass a custom file as the dub.json

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2684]
### System information

- **dub version**: (e.g. dub 1.3.0)
- **OS Platform and distribution**: (e.g. Windows 10, Linux Ubuntu 16.04)
- **compiler version** (e.g. dmd-2.074.1)

### Feature Description
Right now, dub only accepts directories. The only way to build a dub.json located in another directory is by using --root. The problem about this approach is that it still required a file to be named dub.json **and** the path will be relative to the root directory. I'm needing some way to pass a custom path for the dub.json and use the current directory as the cwd.

**Comment by Geod24** [comment]
> I'm needing some way to pass a custom path for the dub.json and use the current directory as the cwd.

What's your use case ?

**Comment by MrcSnm** [comment]
> What's your use case ?

I'm separating some part of `configurations` in other folders for my program, the problem is that I'm unable to pass it while keeping a custom root directory. It all started by my need of unnamed dependencies, I have a meta dub program which outputs those unnamed dependencies, but I'm trying to keep at least the main program from not using this meta thing.

**Comment by Geod24** [comment]
I still don't understand this use case. Why do you need unnamed dependencies ?

**Comment by MrcSnm** [comment]
> I still don't understand this use case. Why do you need unnamed dependencies ?

Because my engine is a main program which imports the user package as a dependency when in the release process. I'm still using it and I believe it won't change anytime soon.
