### ISSUE TITLE
Building a static library as a root doesn't build its dependencies

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2687]
### System information

- **dub version**:  Dub 1.31.1
- **OS Platform and distribution**:  Windows 10
- **compiler version** LDC 1.32.0

### Bug Description
Building a static library as a root doesn't build its dependencies

### How to reproduce?

Download and execute dub. You'll notice the log listed below it does find the dependency, but, it is only included as an importPath and it is not being actually built.

[static_libs_dep.zip](https://github.com/dlang/dub/files/12322673/static_libs_dep.zip)

### Expected Behavior
I'm not even expecting it to combine the libraries, but I would at least like to it build all its dependencies.
My usage is that I'm using dub to build the libraries and then move those libraries to use with another program.

### Logs
```
Found dependency deps @deps
Generating using build
Configuring dependent static_libs_dep, deps:"deps"
  Configuring dependent deps, deps:
    Starting Performing "debug" build using C:\D\ldc2\ldc2-1.32.0-windows-x64\bin\ldc2.exe for x86_64.
    Building static_libs_dep ~master: building configuration [library]
C:\D\ldc2\ldc2-1.32.0-windows-x64\bin\ldc2.exe -lib -ofC:\Users\Hipreme\AppData\Local\dub\cache\static_libs_dep\~master\build\library-debug-windows-x86_64-ldc_v1.32.0-894DC41A1ED4DA75A3034CE2A0F9A6A6C13C4E3390564189D51523ADE73606BC\static_libs_dep.lib -d-debug -g -w --oq -od=C:\Users\Hipreme\AppData\Local\dub\cache\static_libs_dep\~master\build\library-debug-windows-x86_64-ldc_v1.32.0-894DC41A1ED4DA75A3034CE2A0F9A6A6C13C4E3390564189D51523ADE73606BC/obj -d-version=Have_static_libs_dep -d-version=Have_deps -Isource -Ideps\source source\mainDep.d -vcolumns

```

**Comment by MrcSnm** [comment]
#2647 fixes that

**Comment by WebFreak001** [comment]
was by design, use the new `--deep` flag to build dependencies as well for static libraries.
