### ISSUE TITLE
Support additional compiler path search other than the PATH env var.

### ISSUE THREAD

**Issue by bruno-medeiros** [dlang/dub#269]
It would be helpfull if DUB were to support additional compiler path search other than the PATH env var. A bit more of motivation is described here:
http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/1134/

This path-list environment variable (say DUB_COMPILERS_PATH for example) ideally would have the same format as the PATH variable, so this should be a trivial feature to add.

**Comment by WebFreak001** [comment]
absolute paths to compilers have been introduced to DUB since a while ago.

Dub also automatically picks the compiler inside its own bin folder by default.
