### ISSUE TITLE
feature Request: Flag for dub don't process color tokens

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2701]
### System information

- **dub version**: dub 1.34.0
- **OS Platform and distribution**: All
- **compiler version** 2.105.0

Pass a flag for not processing the colors.
This is useful for being able to use executeShell in dub and even though you don't get the real time output, my program can process the color tokens and colorize itself.

This will also be useful for dub internal usage since I'm preparing a PR for dub dependencies compilation be parallelized. (Since you can't just log everything from more than one thread, the output would be confusing)

**Comment by WebFreak001** [comment]
`--color=always`
`--color=never`

see `dub --help`

**Comment by MrcSnm** [comment]
Doesn't work for me. I'm on Windows and dub has some kind of terminal emulator, so it will process its token on Windows API calls to change the conosle state. While color=never will simply won't output the ANSI escapes
