### ISSUE TITLE
dub registry did not show the latest 1.35.0

### ISSUE THREAD

**Issue by chenrui333** [dlang/dub#2721]
👋 it looks like the latest tag in dub registry is still 1.34.0, create this issue to raise some awareness. Thanks!

<img width="1271" alt="image" src="https://github.com/dlang/dub/assets/1580956/e1957d51-7f10-4f7c-bd90-656857d27662">

relates to https://github.com/Homebrew/homebrew-core/pull/156197

**Comment by jmh530** [comment]
It is updated now.
