### ISSUE TITLE
Dependency per system does not work

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2752]
### System information

- **dub version**: 1.35.0
- **OS Platform and distribution**: All
- **compiler version**: All

### Bug Description
Dub does not allow overriding/merging dependencies by system.

### How to reproduce?
```json
"dependencies-osx": {},
"dependencies-windows": {},
"dependencies-linux": {}
```
### Expected Behavior
It should override or merge them. There is a lot of dependencies that doesn't make sense based on system you're using.
e.g: Metal is OSX only. DirectX is Windows only. X11 is almost linux only.

**Comment by Geod24** [comment]
You already reported this in #2560
