### ISSUE TITLE
`dub init` colors are broken on cmd

### ISSUE THREAD

**Issue by brianush1** [dlang/dub#2774]
### System information

- **dub version**: DUB version 1.35.1, built on Jan  1 2024
- **OS Platform and distribution**: Windows 10 (in VMWare Player, but I doubt that matters)
- **compiler version** dmd-v2.106.1 not that it matters

### Bug Description

The colors are messed up, but what's odd is that it does succeed at coloring the last bit properly

![image](https://github.com/dlang/dub/assets/11414209/933996a8-a226-4dbe-b816-8b58063f697d)

### How to reproduce?

Run `dub init` in cmd on a fresh installation of Windows 10

### Expected Behavior

Colors

**Comment by rikkimax** [comment]
https://github.com/dlang/dub/blob/master/source/dub/commandline.d#L1008

Should be cwritef not writef.
