### ISSUE TITLE
Dub does not show verbose output for projects with preBuildCommand

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2822]
### System information

- **dub version**: 1.35.1
- **OS Platform and distribution**: Windows 10

### Bug Description
It skips showing the verbose output for projects with preBuildCommands

**Comment by Geod24** [comment]
What do you see, and what do you expect ? When I add:
```
preBuildCommands "ls -l"
```
To `dub.sdl` and use `dub build -v` I see:
```
   Pre-build Running commands
Running ls -l
[ls -l output]
```

I also tested with dependencies, e.g. `dub build -v -c library-nonet`:
```
     Pre-gen Running commands for openssl
Running /home/mlang/dlang/ldc-1.35.0/bin/ldc2 -run scripts/generate_version.d
```

**Comment by MrcSnm** [comment]
It is working here too, maybe I was sleepy when I saw the logs, sorry :(
