### ISSUE TITLE
looks like 1.37.0 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [dlang/dub#2895]
👋 looks like 1.37.0 release was not completed (while it got published to dlang registry, but the release notes did not get published to github releases), raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/167725

**Comment by Geod24** [comment]
Thanks for pointing it out, did it now: https://github.com/dlang/dub/releases/tag/v1.37.0

**Comment by chenrui333** [comment]
thanks @Geod24!
