### ISSUE TITLE
DUB doesn't automatically create selections JSON. 

### ISSUE THREAD

**Issue by Binero** [dlang/dub#295]
From my understanding, all dependencies are properly handled in 'dub.selections.json'. The 'dub.json' just forwards to that file. 

Whenever I initialize a new project, and add dependencies for it, it will not automatically create or modify this file. This is rather inconvenient, and should definitely be implemented.

**Comment by wilzbach** [comment]
As this is over three years old and heavily used, I am closing this issue. Please reopen if the issue still exists.
