### ISSUE TITLE
Windows LINK.EXE => uselessly show .lib and .exp?

### ISSUE THREAD

**Issue by p0nce** [dlang/dub#2979]
### System information
- **dub version**: DUB version 1.35.1, built on Jan  6 2024
- **OS Platform and distribution**: Windows 11
- **compiler version** LDC 1.36.0

### Bug Description

When building a shared library, DUB copies to the output directory:
- the dynlib created (ok)
- the .pdb created if `-g` (ok)
- the .lib (why)?
- a .exp (why)?

So I have to explain to users what are the .lib and .exp, since DUB goes out of its way to copy in recipe directory.
BUT the targetType is `"dynamicLibrary"` so in reality I only care about the executable and its `.pdb`

### How to reproduce?

Windows + MSVC:
- Build in Dplug repositery clone, build dplug-build and use it to build an example such as the template example.
- or `dub --compiler dmd`

### Expected Behavior
Only relevant output.

**Comment by rikkimax** [comment]
You need the import and export libraries to do two things:

1. Debug the symbols being exported
2. Link that shared library into a program statically

For Dplug where you are sticking with dub completely, or you are copying it into a host, you do not need them.

But other people such as myself do need them, this is why they are copied.

**Comment by p0nce** [comment]
So I guess the solution is to put that into ouputPath then

**Comment by rikkimax** [comment]
Into ``targetPath`` which it should already be doing.

If it is not, that is a bug.

**Comment by p0nce** [comment]
"targetPath" does work
