### ISSUE TITLE
Add plugin support to dub

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#304]
I've started writing toD compilers (e.g. .asn1 to .d) to facilitate the development process of certain projects. This involves sending arguments to a compiler executable depending on the build environment. It can also be useful for compiling *.dt to *.d on a per-file basis rather than increasing the compile-time of an entire project/library (also making it possible to have 100s of diet template pages).

I've thought of making a fork of dub to add the json arguments and additional compilation steps but this brought to mind the possibility of having these as plugin features in dub.
- A new json parameter (call it `plugins`) can select external/internal source dependency(ies) that, when compiled, create a new dub executable that embeds the plugins through template functions
- The newly compiled `plugin-enhanced` dub is forked and handles the entire compilation process without handling the `plugins` json parameter

Ideally, the way the plugins are compiled into dub would serve the purpose of facilitating an otherwise complex build process. They would have access to several template function calls on several occasions:
- Before opening the dub.json file a plugin can add a set of additional json identifiers and structures to be recognized
- After parsing the dub.json file a plugin can access the json data
- Before every project is compiled a plugin can be notified
- After every project is compiled a plugin can be notified

This is a minimal feature set that would truly empower dub and allow "sub-compilers" to be added to D projects seamlessly.

**Comment by WebFreak001** [comment]
moved into #2210
