### ISSUE TITLE
Support for Visual Studio linker

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#308]
So I copied the MSVC link.exe (from C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin) to dmd's bin folder and I get `Error executing command run: Failed to spawn new process (The system cannot find the file specified.)` 

My MSVC link.exe file is version 12.00.21005.1

It would be nice to have the option to use another linker, especially b/c 64bit compilation won't work on windows without this. see [here](http://wiki.dlang.org/Installing_DMD_on_64-bit_Windows_7_%28COFF-compatible%29)

**Comment by jmh530** [comment]
As far as I can tell, Visual Studio linker works with dub these days. Eligible to close?

**Comment by wilzbach** [comment]
@etcimon please reopen if this is still a problem.
