### ISSUE TITLE
dub remove should ignore built library files

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#314]
With dub-0.9.22-beta.2 removing a package will fail with "Untracked file found, aborting package removal" when the package folder contains a built library, e.g. libvibe-d.a.
The command should ignore temporary built files.

Moved from rejectedsoftware/vibe.d#646

**Comment by WebFreak001** [comment]
seems like this is no longer an issue on current dub versions (package directories are just deleted entirely, no matter if there are untracked files)
