### ISSUE TITLE
source/dub/version_.d ends up in staging area even if locally ignored

### ISSUE THREAD

**Issue by ghost** [dlang/dub#318]
I don't know how you're working around this, but for me `source/dub/version_.d` always ends up in git's staging area even if I add it to my local `exclude` file. Is there any way to work around this so I don't accidentally commit the auto-updated file?

**Comment by MartinNowak** [comment]
Apparently one can freeze files in git repos using .gitattributes, but it seems fairly complex.
http://stackoverflow.com/questions/23528104/how-to-freeze-a-file-in-a-repository/23532748#23532748

**Comment by WebFreak001** [comment]
only happened with build.d, but doesn't seem to happen anymore
