### ISSUE TITLE
Allow fetching packages to .dub/packages

### ISSUE THREAD

**Issue by ColdenCullen** [dlang/dub#319]
This would allow the user to specify `--cache=package` (or `project`, or something related), and have any fetched packages go in `.dub/packages/`.

**Comment by rsw0x** [comment]
Pinging this as a similar request was made on the D newsgroup.

http://forum.dlang.org/post/mailman.3669.1453029716.22025.digitalmars-d@puremagic.com

**Comment by Geod24** [comment]
This has been implemented
