### ISSUE TITLE
mainSourceFile should be automatically excluded from library dependencies

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#321]
This would allow to simplify dual-use executable/library packages.

``` js
    "mainSourceFile": "src/my_main.d",
    "configurations": [
        {
            "name": "application",
            "targetType": "executable",
        },
        {
            "name": "library",
            "targetType": "library",
        },
    ],
```

**Comment by MartinNowak** [comment]
In fact it either needs to include `mainSourceFile` with the exe when it's outside of `sourcePaths`, or exclude it from the lib when it's inside.

**Comment by Geod24** [comment]
A configuration's `mainSourceFile` is now automatically excluded from other configurations, unless included automatically, so this is now solved.
