### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by van-de-bugger** [dlang/dub#326]
Linux Fedora 20 with ldc2 compiler, installed from Fedora repository. dub is installed from rpm downloaded from http://code.dlang.org/download:

```
$ rpm -qa | grep -E 'ldc|dub'
ldc-druntime-2-57.20140305git6e908ff.fc20.x86_64
ldc-config-2-57.20140305git6e908ff.fc20.noarch
ldc-phobos-devel-2-57.20140305git6e908ff.fc20.x86_64
dub-0.9.21-1.x86_64
ldc-2-57.20140305git6e908ff.fc20.x86_64
ldc-phobos-2-57.20140305git6e908ff.fc20.x86_64
ldc-druntime-devel-2-57.20140305git6e908ff.fc20.x86_64
```

I am trying to start a new D package:

```
$ mkdir Foo
$ cd Foo/
$ dub init
Successfully created an empty project in '/home/xxx/Foo'.
$ dub build
foo: ["foo"]
Building foo configuration "application", build type debug.
Compiling...
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd-FC3E71A9A5A6C8DEA51EDBFD7BB84B8B foo executable
Error executing command build: Executable file not found: 
```

Something is wrong, but it is not clear what exactly. What the executable dub failed to find?

**Comment by joakim-noah** [comment]
This has long since been fixed, dub now says:

`Failed to invoke the compiler dmd to determine the build platform`

@wilzbach, do the deed.

**Comment by wilzbach** [comment]
> @wilzbach, do the deed.

We should get you rights for dub!
CC @andralex @WalterBright

**Comment by andralex** [comment]
@wilzbach don't understand... who should give rights to whom?

**Comment by John-Colvin** [comment]
I asume @joakim-noah

**Comment by joakim-noah** [comment]
I've been going through old dub bug reports lately, and telling Seb which ones can be closed, like this one.

**Comment by andralex** [comment]
ok done thx
