### ISSUE TITLE
dub --build=ddox doesn't work

### ISSUE THREAD

**Issue by ghost** [dlang/dub#328]
```
C:\dev\projects\dimgui>dub --build=ddox
Building configuration "library", build type ddox
Running dmd...
DMD v2.066 DEBUG
DDOX in C:\Users\Administrator\AppData\Roaming\dub\packages\ddox-0.9.19 is not built, performing b
uild now.
Error executing command run: Unknown dependency: vibe-d
```

I guess maybe i should file a bug against the ddox package though? Not sure.

**Comment by joakim-noah** [comment]
I built the ddox package as part of the dub tests on Android/ARM and linux/x64, and other than a few source fixes (vibe-d/vibe.d#1885) for Android, had no problem with dependency resolution.  @wilzbach?

**Comment by wilzbach** [comment]
@ghost please reopen if this is still an issue.
