### ISSUE TITLE
dub --compiler=xxx build fails

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#351]
```
geod@Barsoom:~/bin/dub-master$ ./dub --compiler=gdc-4.9 build
Error executing command run: Failed to find a package named 'build'.

geod@Barsoom:~/bin/dub-master$ ./dub build --compiler=gdc-4.9
Fetching vibe-d 0.7.20...
[...]
```

Which is pretty inconvenient if you have: `alias dub='dub --compiler=xxx'`

**Comment by joakim-noah** [comment]
>the new semantics break uses like `dub -b release`

Would it have to?  I don't know if you're using `std.getopt` or what, but presumably the options parser could know that `-b` expects a flag and that's not the command.  I realize it's more complex to implement, but users don't want to memorize the order if they don't have to.

**Comment by Geod24** [comment]
My use case was about having a 'default compiler', which is now supported through configuration file.
