### ISSUE TITLE
[enh] Integrate with gh-pages

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#355]
Currently dub allow one to build and display documentation on a local server.
However, considering the strong ties already existing between dub and Github, it could take advantage of the [gh-pages branch](https://help.github.com/articles/creating-project-pages-manually) to provide packets on code.dlang.org with an easy way to display their documentation, and keep it up to date.

**Comment by WebFreak001** [comment]
we have dpldocs.info run by Adam now, which hosts documentation for all packages, so I think we can be closing this.

For custom documentation on github especially, special GitHub Actions actions can be used to deploy to gh-actions, e.g. see https://github.com/dlang-community/libdparse/blob/master/.github/workflows/deploy-pages.yml
