### ISSUE TITLE
dub clean

### ISSUE THREAD

**Issue by zhaopuming** [dlang/dub#365]
I can't find a way to clean the builds/dependencies of a dub project, I know its easy because we can just `rm .dub  {project-name}`, but a `dub clean` is really handy.

**Comment by schveiguy** [comment]
dub clean currently doesn't remove the actual built binaries/libraries. Given that this is what most build systems do, shouldn't dub do this too?

**Comment by s-ludwig** [comment]
It should! The current implementation has just the minimum of the required functionality. Generated documentation would be another point (which can get hairy if the package places some custom resources in the "docs/" folder).

**Comment by MartinNowak** [comment]
Closing this as `dub clean --all-packages` is available.
