### ISSUE TITLE
Switch the working directory when executing build commands

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#384]
Currently, all pre/post build/generate commands are executed within the root package directory. The more useful default seems to be the directory of each package, though.

See also http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/1953/

**Comment by Abscissa** [comment]
PR: #659

**Comment by Geod24** [comment]
Can you check if #1820 correctly fixes this ?

**Comment by Geod24** [comment]
Tested, I confirm it's fixed by #1820
