### ISSUE TITLE
Publish Windows installer to Chocolatey

### ISSUE THREAD

**Issue by mcandre** [dlang/dub#386]
I'm glad that dub is available through `apt-get install dub` with the D-APT repo, and through `brew install dub` with Homebrew. This makes my life so much easier!

Could we also publish dub to [Chocolatey](http://chocolatey.org/) so that Windows users can `chocolatey install dub`?

**Comment by jmh530** [comment]
I believe this can be closed.

**Comment by wilzbach** [comment]
> I believe this can be closed.
https://chocolatey.org/packages/dub

Btw @PxlBuzzard (the maintainer of dub and dmd on chocolatey) - you seem to have outdated versions (DMD is at 2.074.0 and DUB at 1.3.0). Is there any way we can help to ensure fast version bumps?

**Comment by PxlBuzzard** [comment]
@wilzbach I've tried to find a better way to automate new releases. There's a couple issues:

- chocolatey wants all download links to be HTTPS from now on, and dmd is still http only.
- I need to update the scripts to check md5 hashes of the downloads, it was recently added as a new must-have by the chocolatey team.
- I just revisited [this page](https://chocolatey.org/docs/automatic-packages) and discovered they have a more simple way to automate new releases. If I got that set up it would certainly help with keeping up-to-date. Though it doesn't fix the HTTP problem.

**Comment by wilzbach** [comment]
> chocolatey wants all download links to be HTTPS from now on, and dmd is still http only.

Have you tried fetching it from S3 directly?
E.g.

https://s3-us-west-2.amazonaws.com/downloads.dlang.org/releases/2017/dmd.2.074.1.windows.7z

There's an outstanding issue to make [downloads.dlang.org https by default](https://trello.com/c/mWHZxwo5/89-https-for-s3-downloadsdlangorg), but currently it seems like there isn't an easy solution to use SSL with a S3 bucket (except for the expensive S3 cloudfront). Not sure if we can convince our release tzar @MartinNowak to upload the releases to somewhere else (e.g. GitHub releases).

**Comment by PxlBuzzard** [comment]
@wilzbach That sounds like a good enough workaround, I'll give it a shot.
