### ISSUE TITLE
dub test linker errors

### ISSUE THREAD

**Issue by PxlBuzzard** [dlang/dub#413]
When I run `dub test` on a project (that has 0 unittests, although the included packages have their own), it compiles everything but then dies in the linker. It appears to not include phobos or druntime, as there are lots of undefined references to std and core symbols.

dmd 2.066
dub 0.9.22-rc2

**Comment by wilzbach** [comment]
Add this is over three years old, I assume that the linker error has been fixed. Please reopen if the issue still exists.
