### ISSUE TITLE
How can i use the same library as static library and as a source of interfaces?

### ISSUE THREAD

**Issue by MrSmith33** [dlang/dub#427]
Suppose i have some library `library`
Then i have an application called `app` that depends on `library`.
Also i have a shared library called `shared`, which will be loaded by `app`.
So, in order to access interfaces stored in `library` i need to put it on import path of `shared`.
So, will be `library` compiled in while compiling `shared` even if it import a couple of files.
Nonetheless, i think i want to call some templated functions from `shared`, located in `library`.

What is the best `targetType` option for `library` here?

**Comment by WebFreak001** [comment]
if you want to inject code from a dependency into your shared library, use `injectSourceFiles` (@rikkimax can tell you more)

you might want to have `library` as another sharedLibrary if you don't want to link its code into `shared` which depends on it.
