### ISSUE TITLE
Add comments to json parser

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#439]
https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr

There's no reason why the json parser should refuse comments on a configuration file. Just pretend its being piped through jsmin, and enable them.

/\* */
/+ +/ 
//

**Comment by timotheecour** [comment]
reopening as this is issue is still bugging:

i was able to fix it locally as follows:

private string skipJsonString(R)(ref R s, int* line = null)
{
	// skip line comments
	if(s.startsWith("//")){
		//TODO:improve
		while(true){
			auto front=s.front;
			s.popFront();
			if(front=='\n'){
				break;
			}
		}
		s=s.stripLeft;
	}

	// TODO: count or disallow any newlines inside of the string
	enforceJson(!s.empty && s.front == '"', "Expected '\"' to start string:"~s.front.to!string);
	s.popFront();
	string ret = jsonUnescape(s);
	enforceJson(!s.empty && s.front == '"', "Expected '\"' to terminate string.");
	s.popFront();
	return ret;
}
