### ISSUE TITLE
No way to control doc output

### ISSUE THREAD

**Issue by Geod24** [dlang/dub#449]
While implementing #355 I realized that the doc generation didn't care about `targetPath`.

It would be nice to have a way to change this.
I see various solution:
- Output to `targetPath` instead of `docs` when `targetPath` is defined;
- Output to `targetPath`/docs when `targetPath` is defined;
- Extend `dub.json` to add an additional field that serve the same purpose as `targetPath`, but for docs.

I lean towards the 3rd option, as the other 2 can be problematic (the only downside of the 3rd one is yet another field to the package definition).

In addition, we will need a way to override `targetPath` and it's hypothetical addition. The main reason is scripting, which is very important for CI integration.

**Comment by wilzbach** [comment]
Closing as duplicate of #501
