### ISSUE TITLE
Start 0.9.23 Release Process

### ISSUE THREAD

**Issue by ColdenCullen** [dlang/dub#454]
0.9.22 has been out for a few weeks now, and it seems like we should probably start preparing for the next release. There have been plenty of features and fixes added, and I'd love to see then start getting tested more seriously.

**Comment by MartinNowak** [comment]
Very important, we need to update the travis-ci scripts to use the new http://code.dlang.org/download/LATEST mechanism instead of querying tags from github.
Otherwise we'd tag a new version before uploading the binaries, which would cause a travis-ci outage.
