### ISSUE TITLE
Incorrect extension when building static library with ldc + msvc linker

### ISSUE THREAD

**Issue by drsneed** [dlang/dub#465]
I'm building a 64 bit static library using LDC and MSVC linker.
dub spits out "ldc2 -lib -of.dub\build\library-release-windows-x86-ldc_0-795AE73CA9D67364B72D6893EA24DE43\libengine.a .."
The MSVC linker automatically appends .lib to the end of this so dub cannot find the output file:
"Error executing command build: Source file does not exist."
The file that was actually output was "libengine.a.lib, but in theory should output "engine.lib."

**Comment by s-ludwig** [comment]
Fixed as #618.
