### ISSUE TITLE
Add/remove compiler switches from DUB cmdline

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#49]
It would be very helpful during development to be able specify, on DUB's command line, compiler switches to be added/removed, without having to edit package.json and then remember to revert the changes.

**Comment by WebFreak001** [comment]
DFLAGS essentially already implemented what has been requested here, there hasn't been any activity on this, so I will just close this now. Dependencies can be injected with dflags as well, so that should work fine as well.
