### ISSUE TITLE
Conditional dependecies

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#509]
I'll need to add Botan TLS driver for vibe.d, but configurations are already used for TCP drivers, can we add an `ifDefined` option like:

in vibe.d:

```
"dependencies": { 
    "botan": { 
        "ifDefined": "USE_BOTAN",
        "version": "~master"
    },
    "openssl": {
        "ifDefined": "USE_OPENSSL",
        "version": "~master"
    }
}
```

in my project:

```
"versions": ["USE_BOTAN", ...]
```

**Comment by etcimon** [comment]
I'd also opt for something else though, making it possible to have multiple configurations would be ideal, with some type of bash/scripting predicate to verify if it can be selected or if not, fail graciously with a message as to why.

**Comment by MartinNowak** [comment]
I don't completely understand what you want here. Why can't you use configurations?

**Comment by MartinNowak** [comment]
Also look at https://github.com/D-Programming-Language/dub/issues/218.

**Comment by etcimon** [comment]
Configurations are exclusive right now. I want to be able to do the equivalent of:

```
enum configurations {
libasync,
libevent,
libev,
openssl
botan   
}
```

rather than
```
enum configurations {
libasync_openssl,
libasync_botan,
libevent_openssl,
libevent_botan,
libev_..
}
```

**Comment by WebFreak001** [comment]
moving into #128
