### ISSUE TITLE
Allow dependency on specific ~master commit hash

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#51]
I think this could be useful in many cases, particularly when dealing with unstable or pre-1.0 stuff.

**Comment by MartinNowak** [comment]
It looses the semantic part of semantic versioning, and it's literally free to use `0.0.1, 0.0.2, ...`.
Now that tags are mandatory to register a package this problem should be gone anyhow.

**Comment by timotheecour** [comment]
@MartinNowak @Abscissa @carlor 
can we re-open? this use case is so common; eg someone just pushed a commit to fix a bug yet I can't upgrade my dub.selections.json to point to that bugfix locally (unless i git clone and add a path dependency).
At least allowing it locally (and potentially preventing this on published dub packages) would be required

**Comment by wilzbach** [comment]
I agree that this is really useful. Especially if you made a fix to a project and they haven't merged your PR yet. Simply point to the commit hash of your repo and PR.
GitHub even allows to fetch any commit hash as zip / tar.gz e.g.

https://github.com/dlang/dmd/archive/9bed5b46cef44e5cd4e4ed49046329f582616021.zip

So this doesn't even depend on git support in dub (though that one would be nice too).

Also almost all package managers I know support fixing a dependency to a specific commit hash.

**Comment by timotheecour** [comment]
https://github.com/dlang/dub/pull/1403

**Comment by Geod24** [comment]
Fixed by https://github.com/dlang/dub/pull/1798
