### ISSUE TITLE
Evaluate biicode for C++ building

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#514]
This looks like an interesting dependency/build tool for C++, that can resolve used libraries using include paths. Maybe we can use it or some part of it to get C++ integrated with dub.
It also has a nice command line which might be an inspiration for some dub commands.

https://www.biicode.com/

**Comment by ColdenCullen** [comment]
This would be super cool. Trying to get C++ support in dub without using an external package manager is probably outside of the scope of dub, but simply instructing bii to do a compile without linking, and having the compiled objs linked into the dub build would be crazy helpful.

**Comment by s-ludwig** [comment]
Interesting indeed. Although my plan indeed was to integrate direct C class language support, maybe we can take a convenient shortcut here. I'm worried about the additional dependency, though.

**Comment by MartinNowak** [comment]
I'm not sure either, if it's worth the effort, but this doesn't preclude C/C++ support because only a few people would use bii.

**Comment by MordodeMaru** [comment]
Hi guys, sorry to peep in in the first place. biicode member here. If anyone needs further information, libs uploaded to our cloud or anything, just drop us an email to jordi _{dot}_ mon _{at}_ youknowtherest

Before I leave you alone, I'd like to tell you on behalf of the team that we are just flattered to serve, at least, as a glimpse of inspiration for the Dlang. Terrifically honoured.

Take care and keep the good work up!

**Comment by Geod24** [comment]
We definitely need better C++ integration, but it looks like BiiCode hasn't seen any activity for a few years.
