### ISSUE TITLE
Support specification of system dependencies (APT, ports etc.)

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#52]
This should invoke the platform specific package manager to install non-DUB dependencies and can also be used to automatically generate system specific packages for DUB application projects. @eskimor has posted a basic idea of how to manage such a system in #34.

**Comment by dhasenan** [comment]
The consensus here seems to be that it's a bad idea to get clever with regards to system packages. So can we close this ticket?

**Comment by wilzbach** [comment]
> So can we close this ticket?

Yup. A good way to move forward is to improve the built-in support for compiling C/C++ libraries on the fly (`preBuildCommands` works, but there's a lot of room for improvement).
