### ISSUE TITLE
[Feature request] .hgignore for dub init

### ISSUE THREAD

**Issue by dmi7ry** [dlang/dub#533]
`dub init projectname` will create a directory for the project with a `.gitignore` file. But some developers use Mercurial. Please add option for support Mercurial (or simple add `.hgignore` file - then developer can leave the desired file and delete other).

**Comment by Geod24** [comment]
The more I think about it, the more I think `dub init` should be more configurable: a dub.json template (for Authors / dependencies), custom file / structure, etc...

**Comment by s-ludwig** [comment]
But remember that `dub init` is mainly just a helper for newcomers or for having a quick sane default in case of experienced users. Making it too complex could easily raise the learning curve too much in relation to the benefit it provides.

A `--hg(ignore)` switch sounds fine, though.

**Comment by ColdenCullen** [comment]
It might be nice to make `dub init` interactive, in a similar vein to npm. This would make creating packages even easier, and would result in more complete starting points:
```bash
$ dub init
Package name [DIRNAME]: mypackage
Description ["A simple dub package"]: A basic package
License [MIT]: BSD
Authors [USERNAME]: Colden Cullen
```
would generate the following:
```json
{
    "name": "mypackage",
    "description": "A basic package",
    "license": "BSD",
    "copyright": "Copyright 2015 Colden Cullen",
    "authors": [ "Colden Cullen" ],
    "dependencies": {
    }
}
```
And so on and so forth.

**Comment by s-ludwig** [comment]
Could be an interesting default behavior indeed!

**Comment by grogancolin** [comment]
I think making init more customisable would be good, but personally I
wouldn't like it being interactive.

I'd rather just add lots of switches for setting each parameter, and if
switch isn't given just give it a default value.

**Comment by s-ludwig** [comment]
I'd just make the argument-less `dub init` use the interactive route. Adding any custom parameters would switch to standard mode.

The big advantage is that it drives people to use sane values for fields like description or author. There are currently a number of public projects where these have been left with default values.

**Comment by grogancolin** [comment]
Yeah, this is a good point.

**Comment by MartinNowak** [comment]
+1 for interactive
Another idea is to combine `dub init` with a `git init` call (or `hg init` for that matter).

**Comment by gedaiu** [comment]
I would like to have dub interactive by default. Maybe with a -i flag?

**Comment by MartinNowak** [comment]
https://github.com/D-Programming-Language/dub/pull/600#issuecomment-143574460
> For the purpose of having special init types for other libraries, I think it'd be best to do this as executable targets in the libraries, e.g. dub init -t mylib args would fetch mylib and run dub run -c init mylib -- args.

**Comment by carun** [comment]
Appreciate the support for Mercurial!

**Comment by s-ludwig** [comment]
Since "dub init" is interactive nowadays, we could pretty easily do the following:
- add an `-r <repotype>` switch ("git"/"hg"/"none"), still defaulting to "git"
- add an `--init-repo` switch to enable running "(git/hg) init"
- pose these two as questions in the interactive init process

What would be nice to get done if HG is added in this part, would be to also add support in [`determineVersionFromSCM`](https://github.com/dlang/dub/blob/9f7c8303ebe0f3c2066aad1901e9ca837930c292/source/dub/package_.d#L696). From my side, all of this sounds like a perfect task for a contributor who uses HG regularly. It should all be pretty straight forward once we have settled for the details.

**Comment by Geod24** [comment]
As mentioned [here](https://github.com/dlang/dub/pull/1057#issuecomment-630127477), we're in 2020 and in less than two weeks Bitbucket will remove all Mercurial repositories. I don't think it's productive to keep Mercurial-related issues open, they are far beyond the "nice to have", nor do we have someone interested in working on it.

We did need a better `init` system and I believe some of that have been covered, e.g.:
- https://github.com/dlang/dub/pull/1668
- https://github.com/dlang/dub/pull/1658
If there's more features needed, I'm sure 1) there's an issue for it somewhere, and 2) if not, there will be soon. So closing this as WONTFIX.
