### ISSUE TITLE
Error: only one main/WinMain/DllMain allowed

### ISSUE THREAD

**Issue by bubnenkoff** [dlang/dub#545]
I don't know is it's better to open new bug, or comment closed.
https://github.com/D-Programming-Language/dub/issues/13

I am getting such error on next project: http://dlang.ru/gdal-d-binding.zip
I can't understand why, because it have only one main.

**Comment by s-ludwig** [comment]
Looks strange, maybe it has something to do with the DLL/.lib that the app is linked against, at least I couldn't see anything else that would be suspicious. If you don't get further with it, I can have a closer look as time permits.

**Comment by Geod24** [comment]
We had a few issues like this over the years, but they haven't shown up recently.
The zip is 404 so I'm going to close this as it is not actionable. Please re-open with a repro case if you have one.
