### ISSUE TITLE
The subConfigurations tag gets removed in configurations

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#558]
I have a library [libhttp2](https://github.com/etcimon/libhttp2) with the following configuration:

```
    "configurations": [
        {
            "name": "regular"
        },
        {
            "name": "32mscoff",
            "dflags-windows-x86": ["-m32mscoff"],
            "subConfigurations": { "memutils": "32mscoff" }
        }
```

When running dub fetch, it is being rewritten to:

```
    "configurations": [
        {
            "targetType": "staticLibrary",
            "name": "regular"
        },
        {
            "dflags-windows-x86": [
                "-m32mscoff"
            ],
            "targetType": "staticLibrary",
            "name": "32mscoff"
        }
    ],
```

So dub eats up the subConfigurations tag. Also, I don't have the ability to have a `subConfigurations-windows-x86` which would help avoid making a separate configuration node.

**Comment by s-ludwig** [comment]
Resolved by 9eca792535da1accaecd24868166e27ff4c89773 (same as #745)

**Comment by etcimon** [comment]
oh thanks =)

Also, are you aware of a bug that prevented selecting subconfigurations of a library?

**Comment by etcimon** [comment]
ie. I can't select the full_openssl subconfiguration in botan like this:

```JSON
"configurations": [
                {
                        "name": "normal",
                        "subConfigurations": { "botan:base": "full_openssl" }
                }
```

**Comment by s-ludwig** [comment]
Is "botan:base" a direct dependency of that package? Or just an indirect one? Currently "subConfigurations" only works for direct dependencies and just silently does nothing otherwise. I'll fix this as soon as possible.

**Comment by etcimon** [comment]
OK no I added the dependency "botan" so that it compiles everything. Do you suggest it should enumerate all of the subpackages?

**Comment by s-ludwig** [comment]
The canonical way would be to "inherit" configurations in the base package, like vibe.d currently does: https://github.com/rejectedsoftware/vibe.d/blob/cc3c99309f8fcdb21f0a5d298ac383f822777293/dub.sdl#L35-L46
Then `"subConfigurations" {"botan": "full_openssl"}` would work.

The alternative is to simply add a dependency to "botan:base" in addition to "botan" to the recipe that wants to select a certain configuration.
