### ISSUE TITLE
Fetching info about upgradable packages must not block

### ISSUE THREAD

**Issue by schuetzm** [dlang/dub#559]
http://forum.dlang.org/thread/amspvvngynfmqakqkker@forum.dlang.org

I'd even prefer DUB to never check for available upgrades during building and running.

**Comment by MartinNowak** [comment]
We cache things since 0.9.23.

**Comment by s-ludwig** [comment]
Having an upgrade notification is important, IMO. (Almost) nobody is going to run `dub upgrade` in regular intervals just like that. Important (security?) fixes could stay unused for an indefinite amount of time like that.

However, we could simply add an option to settings.json to disable the update checks for those blessed with similar network issues.

**Comment by schuetzm** [comment]
Caching just means that it will still block once a day instead of every time.

And an option is not the right solution IMO, unless it defaults to off. Checking for updates is not necessary for building and running, therefore it shouldn't influence them by default. This means either disabling the update checks completely, or have them run asynchronously as I suggested (and with a low timeout, so that it won't make dub hang when the check is still not finished after building has completed).

**Comment by s-ludwig** [comment]
Hmm, we could spawn a separate process that can run until it's finished (not influencing the main dub process at all). It would just update the cache information, so that the next run could display the upgrade notification. Why do you see it as problematic to have a little delay once a day? Running build benchmarks?

**Comment by schuetzm** [comment]
Well, I'm just a fundam^M idealist on these matters. If building doesn't require internet access, then it shouldn't do it. The worker thread approach is fine though, IMO.

**Comment by s-ludwig** [comment]
Oh okay, I just missed the original context.

**Comment by WebFreak001** [comment]
DUB doesn't check for package updates when packages are already fetched & selected inside the dub.selections.json.

DUB only checks for upgrades:

1. with branch-based dependencies (`~master`) - they are discouraged/deprecated
2. for packages that don't have any selection yet in dub.selections.json

Forcing no internet lookup (and causing a build fail for missing dependencies) can be forced with `--nodeps`
