### ISSUE TITLE
is there a way to set a global library search path (eg in a ~/.dub/config.json or something)

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#590]
is there a way to set a global library search path (eg in a ~/.dub/config.json or something) that would work for all dub projects?

**Comment by s-ludwig** [comment]
It can be set globally for DMD using dmd.conf/sc.ini. We could also add a field to DUB's config.json, but I think all compilers already offer this one way or another.

**Comment by WebFreak001** [comment]
phobos paths can be configured using the compiler configuration.

Paths to where packages are stored can be configured with the `$DUB_HOME` and `$DPATH` environment variable or by setting `dubHome` in the dub user settings.
