### ISSUE TITLE
Implement automatic generation of a packageinfo.d module

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#6]
This module would contain the version of all dependencies to make it possible to have compile time decisions based on versions (e.g. for improved backwards compatibility). It could also contain the path of each used package so that their "public" (or "resources") folder can be accessed (or rather, they know where their own "public/" folder is).

**Comment by MartinNowak** [comment]
Maybe name the module dub.package info, to avoid conflicts.

**Comment by Geod24** [comment]
There is more conversation going on in https://github.com/dlang/dub/issues/1438 so closing this issue in favor of it.
