### ISSUE TITLE
--force-all to rebuild all dependencies

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#606]
Doing `dub build [project] --force` forces a rebuild of the root project (but not dependencies). That's good, but it'd be useful to also have a `dub build [project] --force-all` to automatically force rebuild of all dependencies in addition to the root project.

**Comment by p0nce** [comment]
I've always seen `--force` make all dependencies rebuild. What do we do differently?

**Comment by Abscissa** [comment]
Currently, dub's --force only forces the current/main/root project to be rebuilt. Which I think is a nice feature. But a way to force rebuild of all projects it depends on is also needed, as opposed to manually going through ```dub build (dep1) --force```, ```dub build (dep2) --force```, ```dub build (dep3) --force```, etc...

**Comment by s-ludwig** [comment]
Hm, @p0nce should be right. `--force` is intended to rebuild all dependencies. In fact, this is probably the main practical reason why it has been added, since often settings in the main package leak through to the dependencies (`-version=`, overridden string imports and so on).

**Comment by lablanu** [comment]
Is there currently a way to rebuild only the root project? Sometimes dub doesn't detect minor edits and rebuilding all dependencies or making sufficiently large edits is a pain. If currently not possible, please add this.

**Comment by p0nce** [comment]
>  Sometimes dub doesn't detect minor edits

Looks like this would be the true bug

**Comment by Geod24** [comment]
`-f` rebuilds dependencies, and I don't think having a flag to rebuild just the root package makes sense. If `dub` misses some edits, that's a bug we should fix.
