### ISSUE TITLE
no warning in misspelling of fields in dub.json

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#614]
E.g. If I accidentally type "subconfigurations" instead of "subConfigurations", I get no warning, it's just silently ignored.

**Comment by Geod24** [comment]
I am not sure it's something we should fix. Wrong keys can be used to provide comments. Additionally, they can be used for future extensions. And yes, we could add some heuristics (perhaps just use soundex) but that seems like chasing our own tail.

**Comment by Geod24** [comment]
I was wrong. https://github.com/dlang/dub/pull/2280 will fix it.

**Comment by Geod24** [comment]
Fixed by the aforementioned PR, will be in v1.30.0
