### ISSUE TITLE
Incorrect library extension for win64-msvc version of ldc2

### ISSUE THREAD

**Issue by mdparker** [dlang/dub#618]
dub assumes only dmd[1] uses the lib file extensions on Windows. Trying to compile a project that uses any libraries with the win64-msvc version of ldc2 results in:

> Error: unrecognized file extension a

[1] https://github.com/D-Programming-Language/dub/blob/master/source%2Fdub%2Fcompilers%2Fcompiler.d#L365

**Comment by s-ludwig** [comment]
Is LDC on Windows generally outputting .lib? In that case I'd turn the condition around and only use libX.a for GDC or on non-Windows systems.

**Comment by aldacron** [comment]
It depends on the backend. The release using MinGW puts out .a. I think the only two options to handle this are to either do it automatically by checking the output of ldc2 -version for 'windows-msvc' in the 'Default Target:' line, or to set up a separate configuration for ldc-msvc.

**Comment by s-ludwig** [comment]
I see, so `getTargetFileName` would have to be moved to the `Compiler` class and the `LdcCompiler` class could then parse `ldc2 -version`.

**Comment by cup** [comment]
https://github.com/dlang/dub/issues/835
