### ISSUE TITLE
Adding the dub-registry REST api to the dub command line tool

### ISSUE THREAD

**Issue by grogancolin** [dlang/dub#620]
Hi folks,

I'm in the middle of adding code.dlang.orgs REST api to dub.
The easiest way is to use vibe-d's rest interface client [1]. However, using this means adding vibe-d as a dependency to the "application" configuration in dubs dub.json.
Then, we'll need to copy the rest interface code over from dub-registry [2]

Would there be any opposition to this?
As far as I see it, that's the easiest way to get this in. 
@s-ludwig, Maybe you had a different plan here? If so, do advise :)

[1] http://vibed.org/api/vibe.web.rest/RestInterfaceClient
[2] https://github.com/D-Programming-Language/dub-registry/blob/master/source/dubregistry/api.d

**Comment by s-ludwig** [comment]
Missed this ticket until the closing notification arrived. So right now, using `dub-registry` as a (library) dependency should work already. `import dubregistry.api; auto cli = new RestInterfaceClient!IPackages("https://code.dlang.org/api/packages");` should then create a usable API client. This should of course be properly wrapped up in a separate API function.

But I think I may misunderstand part of the idea here. Was your intention to expose the REST interface on the command line instead? `dub search` currently exposes one endpoint, but it specifically avoids the vibe-d dependency and performs direct HTTP calls.

**Comment by grogancolin** [comment]
Hey Sonke,

No, my intention was to be able to communicate with the REST interface via code. Similar to what's been done now with `IPackages`.
This ticket predates the creation of that (or more, the completion of that) interface, hence I closed it.

Thanks for following up! :)

**Comment by s-ludwig** [comment]
Okay, I see. Maybe I'll manage tonight to make the api.d module a bit more complete w.r.t client access.

**Comment by s-ludwig** [comment]
OK, there is `dubregistry.api.connectDubRegistryAPI` now as a simple convenience function.
