### ISSUE TITLE
Fix build.sh on FreeBSD

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#63]
The default compiler has no rdmdm shipped with it and linker flags are messed up. Quoting the full problem description from an email conversation:

> The pkg-config call to get the library flags in compilers/dmd.d
> doesn't work on FreeBSD.  The first problem is that the "execute"
> function from stdx.process craps out on FreeBSD.  I tried running the
> unit tests for stdx.process and they crap out in std.stdio, didn't look
> into it further.  The other problem is that OpenSSL is installed by
> default on FreeBSD, so pkg-config gets confused by the calls to
> libcrypto and libssl to build vibe.d.  pkg-config only works if you ask
> it for libevent and libevent_pthreads.  I also had to feed the linker
> the "-lssl" flag and that got it to work.

**Comment by dhasenan** [comment]
It seems to be working now. Close?
