### ISSUE TITLE
[ldmd2] DUB puts .o in the current directory which breaks the build

### ISSUE THREAD

**Issue by p0nce** [dlang/dub#634]
**DUB file:**
https://github.com/p0nce/dplug/blob/master/examples/distort/dub.json

**DUB version**: 
v0.9.23 (didn't test in more recent)

**OS**: 
Mac OS X 10.10

**Compiler:** 
ldc2-0.15.2-beta2-osx-x86_64

**Command-line used:**
dub build --build=debug --arch=x86 --compiler=ldmd2 --force

**Result:**
All .o files get created in the current directory. This brings conflicts.

```
Error: Output file 'package.o' for module 'ae.utils.meta' collides with previous module 'ae.utils.graphics'. See the -oq option
```

**Comment by p0nce** [comment]
Still happen in DUB version 0.9.24-rc.2+7-g35a0cca

**Comment by p0nce** [comment]
Work-arounded by using --compiler=ldc2 instead.

**Comment by yazd** [comment]
I faced this problem on linux with `0.16.0-alpha3` as well.

**Comment by WebFreak001** [comment]
reproduction test case doesn't work since a while anymore, didn't see anyone open a similar issue in a while, will just close.

It's recommended to use ldc instead of ldmd anyway, and might just be an ldmd bug if it only happens with it.

**Comment by p0nce** [comment]
Absolutely agree
