### ISSUE TITLE
DUB option to choose local DUB registry workspace

### ISSUE THREAD

**Issue by bruno-medeiros** [dlang/dub#641]
The local DUB registry (ie, the directory with the `local-packages.json` file, as well as downloaded DUB packages), shouldn't be hardcoded to a single default. There should be a global option to control with location to use. The main use case for this is for test suites that use DUB (`--bare` is not fully adequate for this purpose).

**Comment by greenify** [comment]
(related to #557 and #383)

**Comment by andre2007** [comment]
For test suites the a good solution is to adapt the environment variable HOME while calling dub. 
Does this solve your issue?

**Comment by Geod24** [comment]
We now have `--skip-registry` and the ability to specify the registry in `dub.settings.json`.
