### ISSUE TITLE
rdub proposal

### ISSUE THREAD

**Issue by 9il** [dlang/dub#651]
The idea is to determine dependencies in user's source.d file like `rdmd` and Python's `pip`, but extended to dub package registry.

**Comment by jansengb** [comment]
It would be great to be able to create simple test programs/scripts, say mytest.d, using dub registry dependencies without having to explicitly create a dub project (i.e. dub --init mytest, manually add dependencies to mytest/dub.json, edit app.d, dub run).

**Comment by John-Colvin** [comment]
pip doesn't work like this. pip is just a package manager. python has its own import directories and uses these to find what it needs for ```import packageX```.

As an alternative, a standalone tool that generates a ```dub.sdl``` from analysing imports.

**Comment by jansengb** [comment]
> @John-Colvin how about a standalone tool that generates a `dub.sdl`

Fine. Then the tool (rdub?) could create the dub setup in some temporary working directory ala `rdmd` and run dub from there. Optionally the user could specify a non-temporary directory where the dub setup would be saved for further manual customization if desired. That would give the best of both worlds.

**Comment by wilzbach** [comment]
> Optionally the user could specify a non-temporary directory where the dub setup would be saved for further manual customization if desired. That would give the best of both worlds.

As long as the dependencies are cached, I guess having a temporary directory should be fine for most users ;-)

**Comment by jmh530** [comment]
Looks like there is an rdub project now.
https://code.dlang.org/packages/rdub
Eligible to close this?

**Comment by wilzbach** [comment]
> Looks like there is an rdub project now.

It doesn't do auto-detection, but DUB's built-in single-file gets pretty close.

**Comment by jansengb** [comment]
Looks good to close.

**Comment by wilzbach** [comment]
@9il @John-Colvin - please reopen if you disagree.

**Comment by s-ludwig** [comment]
What we could do would be to extend the single-file mode to make suggestions about missing dependencies. Automatic inclusion seems to be a bit too risky with an open system, where the same D package/module names can be used by many DUB packages.
