### ISSUE TITLE
Specify minimum DUB in dub.json

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#654]
As some packages may rely on features/bugfixes on newer releases of DUB, it may be good to have a way to specify in dub.json/dub.sdl the minimum version of DUB that the package requires. This way, DUB can say "Sorry, this packages requires a newer version of DUB. This is version XXXX, please upgrade to at least YYYY to use this package." instead of just chugging along and crapping out for the user who then has no idea why things went haywire.

**Comment by wilzbach** [comment]
See also: https://github.com/dlang/dub/issues/108

**Comment by andre2007** [comment]
See pull request https://github.com/dlang/dub/pull/1571

**Comment by andre2007** [comment]
Implemented.
