### ISSUE TITLE
Dub --version= enhancements

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#657]
It may be helpful, especially if we don't have #103, to be able to use --version like this:

``` bash
$ dub fetch somepackage --version=~>1.2.0
$ dub fetch somepackage "--version=>=1.3.0 <=1.3.4"
$ dub describe somepackage [--data=... or not] --version=1.2.4
$ dub describe somepackage [--data=... or not] --version=~>1.2.0
```

(Note that currently, `dub describe` doesn't support `--version=` at all.)

That way you could do:

``` bash
$ cat hi.d
// Needs libfoobar v1.2.x
import foobar : foo;
void main() { foo(); }

$ cat hi.sh
#!/bin/sh
dub fetch foobar -q --version=~1.2.0
dub describe foobar --version=~1.2.0 --data-0 --data=import-paths | xargs -0 -I % rdmd % hi.d

$ ./hi.sh
Works!
```

**Comment by WebFreak001** [comment]
package versions can be specified with `pkgname@1.0.0` now. You can get the latest version, but not a version range.

This syntax should work with most, if not all, dub commands.
