### ISSUE TITLE
Common dependencies different version access violations

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#666]
I often find myself debugging some access violations due to one executable building with another executable's common dependency compiled library built with different aggregated `versions` strings. 

ie. The dependencies (libraries) aren't recompiled when the global version strings differ between different dub projects.

I think it would be good to hash the upmost dub project's versions strings with the library dependency build. (Sorry if it sounds complicated with this explanation)

**Comment by s-ludwig** [comment]
The builds are already hashed with all version constants: https://github.com/D-Programming-Language/dub/blob/548dc1b0caf2be412b2d66a0117060c8a4d970df/source/dub/generators/build.d#L306

So it must be something else - one thing that currently doesn't get included in the hash is the full compiler version (only the major and minor version of the frontend), could that be the offender?

**Comment by WebFreak001** [comment]
closing, as the hash should contain everything needed.
