### ISSUE TITLE
interactive dub uninstall/remove in case of multiple versions

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#708]
If a tty console is present ask what to do, similar to this.

```
Select gem to uninstall:
 1. rspec-core-2.99.2
 2. rspec-core-3.0.3
 3. All versions
> 2
```

**Comment by jcao219** [comment]
Also it would be nice to have interactive `dub run` in case of multiple versions.

**Comment by WebFreak001** [comment]
this is what is being done since a while for dub remove.

`dub run` can specify exact versions now
