### ISSUE TITLE
"Illegal Instruction 4" on Mac OSX 10.11 (Homebrew version)

### ISSUE THREAD

**Issue by jchown** [dlang/dub#710]
I've installed everything via homebrew, and am attempting to build a trivial vibe.d project. I get:

```sh
Simple.Vibe jchown$ dub
Fetching memutils 0.4.1 (getting selected version)...
Placing memutils 0.4.1 to /Users/jchown/.dub/packages/...
Illegal instruction: 4
```

dub 0.9.24
dmd 2.068

**Comment by jcao219** [comment]
What about the output of `dub --vverbose`?

**Comment by jrtc27** [comment]
I have the same problem. Running `dub --vverbose`:

    Opening file /tmp/memutils-0.4.5.zip
    Extracting from zip.
    zip root folder: memutils-0.4.5
    Copying all files...
    Creating source/memutils/memory.d
    [1]    64192 illegal hardware instruction  dub --vverbose

It appears to be an issue with Homebrew's prebuilt (bottled) version, as I then installed with `brew install --build-from-source dub` and it works.

**Comment by stonemaster** [comment]
@jrtc27 Thanks for the hint! I had the same problem and running `brew remove dub` and `brew install --build-from-source dub` fixed the issue for me.

**Comment by jchown** [comment]
Yes, thanks @jrtc27 that fixed it for me too.
