### ISSUE TITLE
Dub describe issue on OS X 10.11

### ISSUE THREAD

**Issue by MatthewFrench** [dlang/dub#717]
Fails to work with the latest version website installer of DMD. Works fine with older homebrew version.

**Comment by Geod24** [comment]
How does it fail ? Does it produce any error message, error code, or it just doesn't output anything ?

**Comment by MatthewFrench** [comment]
Last login: Thu Nov  5 20:49:20 on ttys000
Matthews-MacBook-Pro:~ Matt$ /Users/Matt/D-Lang-Tools/dub describe
Failed to invoke the compiler dmd to determine the build platform: Error: cannot find source code for runtime library file 'object.d'
       dmd might not be correctly installed. Run 'dmd -man' for installation instructions.
       config file: (null)
Specify path to file 'object.d' with -I switch

Matthews-MacBook-Pro:~ Matt$

**Comment by Geod24** [comment]
As the message suggest, your compiler is not well installed. You have the compiler, but not the necessary runtime library.

**Comment by MatthewFrench** [comment]
I installed through the main site's package installer.

On Nov 6, 2015, at 6:04 PM, Mathias LANG <notifications@github.com<mailto:notifications@github.com>> wrote:


As the message suggest, your compiler is not well installed. You have the compiler, but not the necessary runtime library.

-

**Comment by Geod24** [comment]
This issue is quite old, and invalid to begin with. For anyone reading, on OSX, just use Homebrew.
