### ISSUE TITLE
specify -framework on osx using dub ?

### ISSUE THREAD

**Issue by extrawurst** [dlang/dub#720]
is there a way to set `-framework XYZ`that gets passed to clang on osx in a build ?

**Comment by s-ludwig** [comment]
`lflags "-framework" "XYZ"` should work (for dub.sdl).

**Comment by Geod24** [comment]
It does, see e.g. https://github.com/vibe-d/eventcore/blob/a7eeabcb10c909f8569b32d6f70f0694133018f9/dub.sdl#L25-L30
