### ISSUE TITLE
Report what signal killed a process with dub run

### ISSUE THREAD

**Issue by dhasenan** [dlang/dub#729]
I saw my application exiting with a nonzero exit code and no message when I ran it with `dub run`. I had declared my main function as returning `void`, so this surprised me.

When I run the executable directly, my shell reports:

`fish: “./test” terminated by signal SIGSEGV (Address boundary error)`

This tells me exactly what happened. It would be great if `dub run` did this sort of thing.

**Comment by BBasile** [comment]
The `main()` written in D is not the real main. There is another one, which is the real entry point.

You can see this in the stack trace:

```
??:? _Dmain [0x42417e]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x42480e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x42474c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4247ca]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x42474c]
??:? _d_run_main [0x4246a9]
??:? main [0x42420d]
??:? __libc_start_main [0xe326ab04]
```

The `main()` we write is `_Dmain`, the other, at the bottom always returns an exit code.

Now what fish did is just an interpretation of the error code (11).

**Comment by WebFreak001** [comment]
dub prints this since a while ago, e.g.

```
Error Program exited with code -15
```

**Comment by Geod24** [comment]
Related: https://github.com/dlang/dub/pull/1869
