### ISSUE TITLE
Output more specific error message for "invalid" dependencies

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#730]
Currently `DependencyResolver` cannot distinguish between dependencies that don't exist and dependencies that have no available versions/branches (unusual, but theoretically possible). A flag needs to be added to make that distinction and to enable outputting a clear error message ("Package x references non-existent package y.").

**Comment by WebFreak001** [comment]
error output has improved since 2015, new issues should be more specific what kind of improvements are needed.
