### ISSUE TITLE
Better error messages for package mismatches

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#748]
Currently when different parts of a dependency graph depend on unreconcilable versions of a library you only get an error message talking about one version saying e.g. `Root package server contains reference to invalid package vibe-d >=0.7.27-alpha.2 <0.8.0`, which is not at all clear about what the problem is (which was a dependent package listing a vibe-d ~master dependency)

**Comment by WebFreak001** [comment]
dependency issues have improved, showing the depender for mismatching versions.
