### ISSUE TITLE
code.dlang.org network very slow, need use mirror from other city!

### ISSUE THREAD

**Issue by zoujiaqing** [dlang/dub#750]
How to do ?

**Comment by greenify** [comment]
I read from time to time in IRC that code.dlang.org is offline or slow - is there any way we can help?
Where is your current bottleneck?

Did you consider to use the free CDN from [cloudfare](https://www.cloudflare.com/)?

**Comment by greenify** [comment]
@zoujiaqing - the according repo is at https://github.com/D-Programming-Language/dub-registry

**Comment by s-ludwig** [comment]
Most of the time the problem is that actually GitHub is offline or slow. The server load is still very manageable, but the connection between Germany and China is generally slow. CloudFlare might be an option, or we could set up a mirror registry, which would be a good idea anyway for backup purposes.

**Comment by zoujiaqing** [comment]
from China ... download package slow ..
Where is the mirror list?

**Comment by s-ludwig** [comment]
@zoujiaqing Is only downloading packages slow? Or is browsing the site also slow?

**Comment by wilzbach** [comment]
Did you give cloudfare already a try?

**Comment by MartinNowak** [comment]
> Did you give cloudfare already a try?

It's already fairly dynamic content, don't think it makes much sense.
Soon the site will need to be search focused, then a simple cache becomes pointless.
Also didn't have the best experience w/ cloudflare and similar services.

As @zoujiaqing said downloading packages is slow, so I think he means github.
At peak times I often get horrible throughput from US servers as well, b/c my provider (thx DTAG) doesn't book enough peer capacity w/ Level3.
Apparently github mirrors codeload.github.com in San Jose, CA, at least that's what  https://www.dotcom-tools.com/online-traceroute-network-latency-test.aspx told me for China (~250ms). They also told me that the download of github.com/MartinNowak/bloom/archive/v0.3.0.tar.gz took 50.12s (4.9KB that is), take this w/ a grain of salt.

**Comment by MartinNowak** [comment]
You can now mirror the original repo using `./dub-registry --mirror https://code.dlang.org`, so it should be easy to run a small mirror in your local network or anywhere near you.
https://github.com/dlang/dub-registry/pull/188
