### ISSUE TITLE
custom linker

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#769]
It is sometimes useful / necessary to use a specific linker.

**Comment by wilzbach** [comment]
Isn't this something that should be taken care of my the host OS? (Setting a symlink to ld.gold is trivial)
Do dmd or ldc allow selecting a specific linker?

**Comment by ZombineDev** [comment]
Yes, this is very important, especially for cross-compilation. Usually you have a separate toolchain (C compiler, linker, assembler, libc) for each target on your host system.
Also on Windows there's no linker that the OS provides - you need to manually specify a path. Also almost no one uses symlinks on Windows.

**Comment by s-ludwig** [comment]
DUB currently doesn't invoke the linker directly at all, only the compiler. So the first prerequisite for this would be to have the compiler be able to switch to a different linker through a command line option.

**Comment by MartinNowak** [comment]
The compiler doesn't invoke a linker either, and it's already possible to just set `CC` to whatever compiler driver you want to use for linking, e.g. `c++` or `clang++`.
https://github.com/dlang/dmd/blob/46e54185b928f43d06f466a71e3b28799b07cb67/src/ddmd/link.d#L476
For cross-compilation the D compiler should already be configured to use it's companion cc for linking.
