### ISSUE TITLE
Add comments to json parser [+fix]

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#770]
couldn't reopen https://github.com/D-Programming-Language/dub/issues/439 so re-creating issue:
[reopening as this is issue is still bugging:]

as i wrote here: https://github.com/D-Programming-Language/dub/issues/439#issuecomment-180716555

i was able to fix it locally as follows:

```
private string skipJsonString(R)(ref R s, int* line = null)
{
    // skip line comments
    if(s.startsWith("//")){
        //TODO:improve
        while(true){
            auto front=s.front;
            s.popFront();
            if(front=='\n'){
                break;
            }
        }
        s=s.stripLeft;
    }

    // TODO: count or disallow any newlines inside of the string
    enforceJson(!s.empty && s.front == '"', "Expected '\"' to start string:"~s.front.to!string);
    s.popFront();
    string ret = jsonUnescape(s);
    enforceJson(!s.empty && s.front == '"', "Expected '\"' to terminate string.");
    s.popFront();
    return ret;
}
```

ugly but works for line comments

**Comment by dhasenan** [comment]
You can use sdl instead.

While adding comments to JSON is nice for documentation, it's bad for tooling. You wouldn't be able to use std.json or any other standards-compliant json parser. Vim and emacs will both yell at you for using comments.
