### ISSUE TITLE
dub dependency version problems

### ISSUE THREAD

**Issue by Laeeth** [dlang/dub#776]
Unfortunately I don't understand things well enough to reduce to a simple test case.  You can speak to John Colvin who may understand what's going on a bit better.  But I have had some nightmarish cyclical dependency problems with dub where the packages of a project reference different versions of another package (eg vibe-d).  One problem is that the error reporting from dub is very unhelpful:

Root package server references unknown package vibe-d

This seems to be the consequence of subpackages referencing different versions of vibe-d.

Another problem is that dub (build and verbose) gets stuck in a loop and never finishes.

I build a primitive tool here to report all versions used by dub.sdl or dub.json projects in subdirectories of a particular directory, and this helps a lot.  Will post gist shortly.

**Comment by Laeeth** [comment]
Gist is here: https://gist.github.com/Laeeth/9e62861414329721ca39  sort doesn't work, but I didn't bother figuring out why.

**Comment by MartinNowak** [comment]
Might be related to https://github.com/D-Programming-Language/dub/issues/652.

**Comment by Geod24** [comment]
This looks a lot like #1706 / #1217 . Regarding the need for more information on dependencies, Jan is working on https://github.com/dlang/dub/pull/2359
