### ISSUE TITLE
dub add-override allows for multiple overrides with the same path

### ISSUE THREAD

**Issue by whitebyte** [dlang/dub#778]
``` shell
$ dub add-override dchip 0.1.2 ./dchip-0.1.2/
Added override dchip 0.1.2 => ./dchip-0.1.2/

$ dub add-override dchip 0.1.2 ./dchip-0.1.2/
Added override dchip 0.1.2 => ./dchip-0.1.2/

$ dub add-override dchip 0.1.2 ./dchip-0.1.2/
Added override dchip 0.1.2 => ./dchip-0.1.2/

$ dub list-overrides
dchip 0.1.2 => ./dchip-0.1.2/
dchip 0.1.2 => ./dchip-0.1.2/
dchip 0.1.2 => ./dchip-0.1.2/

$ dub --version
DUB version 0.9.24, built on Nov 27 2015
```

Are multiple overrides legit at all? Ever if so, multi-overrides with the same path don't make sense, and DUB should prevent this.

`dub remove-override` silently removes one last override. If `add-override` gives us a message on completion, `remove-override` should also do it.

**Comment by WebFreak001** [comment]
overrides have been deprecated / removed, use path based dependencies instead.
