### ISSUE TITLE
dub add-override: doesn't reference an existing package

### ISSUE THREAD

**Issue by whitebyte** [dlang/dub#779]
```
$ dub add-override dchip 0.1.2 ./dchip-0.1.2/
Added override dchip 0.1.2 => ./dchip-0.1.2/
$ dub build
Package override dchip 0.1.2 ->  ./dchip-0.1.2/ doesn't reference an existing package.
```

Found an old thread: https://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/5195/
Surprisingly, still actual. Tried absolute path, tilda (~) and period(.) variants, still no luck. I didn't find aly examples of `dub add-override` usage in the docs, so maybe I'm just doing something wrong?

DUB 0.9.24, tested both on SDLang and JSON projects.

**Comment by luismarques** [comment]
Happened to me again, and now I see I'm not the only one stumbling against this.
This time it was with `dub add-override ncurses "~master" ~/Projects/ncurses`.

**Comment by cruisercoder** [comment]
I get that same error.  The path reference can be to a local git project, correct?

dub add-override dstddb "*" ~/src/dstddb
dub build
Package override dstddb >=0.0.0 ->  /Users/erik/src/dstddb doesn't reference an existing package.

**Comment by Timoses** [comment]
Same here...

```
Package override dyaml 0.5.3 ->  /Users/xxx/.dub/packages/dyaml-dlang-tour-0.5.5 doesn't reference an existing package.
```

Especially annoying as dyaml doesn't compile with newest dmd any more -.- ...

**Comment by s-ludwig** [comment]
Path based package overrides were completely broken. The path was treated as a version string instead of as an actual path.

**Comment by s-ludwig** [comment]
Relative paths are also fixed now.
