### ISSUE TITLE
Add build option to package for specific config

### ISSUE THREAD

**Issue by QAston** [dlang/dub#78]
For example, we have a config like this
https://gist.github.com/QAston/5670098

Intention of the config file is to add some specific version identifiers (could be dependencies, or maybe anything) for building testing executable for a library. Right now dub warns about enforcing a particular build type (using dflag unittest). My proposal is:
adding build="unittest" entry in "tests" config section could have same effect as using --config="tests" --build="unittest" in command line.

**Comment by FeepingCreature** [comment]
Very late ping.

First of all, this contradicts the documentation: https://code.dlang.org/docs/commandline

>  Specifies the type of build to perform. Note that setting the DFLAGS environment variable will **override** the build type with custom flags.

Second, it means that it's impossible to inject DFLAGS into a dependency except via config overriding, so if a project has a version flag then this flag cannot be set when pulling in the project as a dependency.
