### ISSUE TITLE
use dub.pm as a domain

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#781]
As originating from [this discussion](http://forum.dlang.org/post/xmrdesqhehkbydlmjfut@forum.dlang.org), `dub.pm` seemed very nice as a domain for dub (pm: package manager).
@WebFreak001

I mapped root and all subdomains (wildcard) to 79.140.41.234, which means 

1) you can use `dub.pm` now :) :)
2) that you can use subdomains like

```
my-fancy-package.dub.pm
vibed.dub.pm
enigma.dub.pm
...
```

I don't know what exact setup you have and whether you use nginx or apache2, but such a redirect should be relatively with both.

Sorry that I moved forward with this without full agreement, but I was more convinced that buying `dub.pm` would fail ;-)

If someone is worried about
a) costs -> it's just 14.5€ a year
b) rights/control -> I am more than willing to transfer this to anyone officially related with dub/D or to an organization (I don't know whether there is one)

I love D and dub - so see this as an acknowledgement & small heads up that you did awesome work so far ;-)

**Comment by WebFreak001** [comment]
Yeah I would love to have that as an alternative. Also rewriting `XYZ.dub.pm` to `code.dlang.org/packages/XYZ` sounds like a good idea.

But if there is no redirect, it should also use an SSL certificate. https://letsencrypt.org/ is in public beta, so that can probably be used in the future

**Comment by s-ludwig** [comment]
I've set up a basic redirect to code.dlang.org now. Mapping sub domains to packages could be interesting, but I'd wait with that until there is a clear vision (to avoid creating broken links when changing things later).

Long term it would probably make most sense to let the D foundation own the domain, maybe you can get in touch with Walter/Andrei for that.

**Comment by s-ludwig** [comment]
Regarding SSL/TLS, I'm already using letsencrypt for all open source domains. It's still opt-in, because there were still some issues with the certificates, but I'll change that soon.

**Comment by greenify** [comment]
> Long term it would probably make most sense to let the D foundation own the domain, maybe you can get in touch with Walter/Andrei for that.

@WalterBright @andralex - do you already have an official foundation? What is your opinion on this?
I just created the Gandi account for this domain, so as a temporary solution - I could share that with you ;-)

Encryption
-------------

LetsEncrypt already works pretty well - I use it e.g. for my [blog](https://seb.wilzba.ch) or the [DLang Functional Garden](https://garden.dlang.io)

Hmm it seems like wildcards won't be supported in the near future by LetsEncrypt and currently they limit one to 10 domains per IP per week, so relying on LetsEncrypt for all subdomains might no work.
https://github.com/letsencrypt/letsencrypt/issues/66

However there is always the option of buying the wildcard certificate, but this will be ~50$.

**Comment by greenify** [comment]
> I've set up a basic redirect to code.dlang.org now. Mapping sub domains to packages could be interesting, but I'd wait with that until there is a clear vision (to avoid creating broken links when changing things later).

One thing that is always trivial to implement is to shorten the path from `dub.pm/package/foo` to sth. like `dub.pm/p/foo` - a couple of package manager websites also do this
I actually did this myself for [biojs.io](http://biojs.io) and people liked it - it seems that people just love short urls ;-)

**Comment by greenify** [comment]
ping @andralex @WalterBright - would be happy to move forward and transfer the domain to the DLang foundation.
ping @s-ludwig - how do you want to proceed with new `dub.pm` domain? Can we get it as "main" domain before the DConf?

**Comment by s-ludwig** [comment]
Just stumbled over this in an open tab. An idea that was floating in my head was to put anything related to DUB itself on dub.pm, but to leave the registry at code.dlang.org (a redirect from "dub.pm/p/..." to code.dlang.org would be fine). That would give more space to properly document DUB and would make the registry project slimmer, which is good for build time and build-time memory consumption, and it would remove everything that is unnecessary for hosting a private registry.

**Comment by andralex** [comment]
If you guys like dub.pm, the Foundation can take it. Just don't get couple hundred more :)

**Comment by wilzbach** [comment]
I just got a notification:

> This domain  will expire at the Registry in 14 days, on 2017-03-01 18:41.

So I will give this another try for 2017.
Also I just enabled automatic sub-domain rewriting, s.t. all subdomains get redirected to the respective code.dlang.org page:
`mir.dub.pm` -> `https://code.dlang.org/packages/mir`

> An idea that was floating in my head was to put anything related to DUB itself on dub.pm, but to leave the registry at code.dlang.org
> That would give more space to properly document DUB and would make the registry project slimmer, which is good for build time and build-time memory consumption,

It's just a DNS setting away ;-)

**Comment by WebFreak001** [comment]
It would be cool if you could host project documentation/static html files like on github pages on `projectname.dub.pm`

**Comment by wilzbach** [comment]
> It would be cool if you could host project documentation/static html files like on github pages on projectname.dub.pm

How would the upload work? If someone wants to look into automatically running ddox for all packages and dumping the result on S3, I am happy to help with domains.

**Comment by s-ludwig** [comment]
I mean, while we planned to provide this automatically using a build farm of some kind, just uploading a JSON file manually could be a viable alternative. If this would be integrated with the Travis-CI D support somehow, it could even work automatically.

**Comment by p0nce** [comment]
A way to have (opt-in) automatic Ddoc for project in the DUB registry would be awesome.

**Comment by WebFreak001** [comment]
But maybe for more than ddoc, until recently I always ran a program adding styles to the documentation because it looked so ugly. While that might not be the case anymore, it would still be cool if you could run a program processing the html files so we can have a sidebar with a list of all modules.

**Comment by rikkimax** [comment]
It would have to be pretty configurable/extendable since I am only
interested in adrdox based.

**Comment by WebFreak001** [comment]
https://dub.pm should redirect to https://code.dlang.org, I always go on dub.pm because it's faster to type but then there is only that default "It Works!" Apache site

**Comment by wilzbach** [comment]
@WebFreak001: thanks for the ping. The subdomain  package redirects changed this. I fixed the redirect for http://dub.pm and will setup letsencrypt for https://dub.pm tomorrow.

**Comment by Geod24** [comment]
So should this issue be closed ?

**Comment by WebFreak001** [comment]
I still like using `<packagename>.dub.pm` for redirects but it has currently been broken for a few weeks so I think this could stay open

**Comment by Geod24** [comment]
That can maybe be a separate issue, and https://github.com/dlang/dub-registry might be a better place to discuss this ?
