### ISSUE TITLE
dub build fails when using Debian GtkD packages from http://d-apt.sourceforge.net/

### ISSUE THREAD

**Issue by jeanbaptistelab** [dlang/dub#782]
Hi,

I've switched to using the GtkD packages from the above mentioned repository as they provide a shared-library version of GtkD which (as far as I know) is not (yet?) possible using dub itself.
My config uses `"libs" : ["gtkd3"]` which causes dub to use `pkg-config --libs gtkd3` for library and linker flags resolution.

The issue here is that the pkg-config `.pc` files for the Debian packages from that repository are written for a build context using the D compiler (dmd, ldc and friends) **_directly**_, either from the command line or from a Makefile. More generally, they are written so that the output of `pkg-config --libs <pure-d-library>` is passed unmodified to the D compiler. DUB however massages this output by calling the `BuildSettings.addLFlags` method for each argument returned by `pkg-config` which prefixes them with an extra `-L` flags.

An sample output might be easier to understand the above description:

Output of `pkg-config --libs gtkd3`:

```
-L-L/usr/lib/x86_64-linux-gnu -L-L/usr/lib/i386-linux-gnu -L-l:libgtkd3.so -L-l:libdl.so.2 -L--no-warn-search-mismatch -defaultlib=libphobos2.so
```

Ouput of `dub build`:

```
Using pkg-config to resolve library flags for gtkd3, sqlite3.
dmd -c -of.dub/build/posix-debug-linux.posix-x86_64-dmd_2070-51125FF0CA3A1BF02DDAD201D7FF67B9/ttracker.o -debug -g -w -version=USE_SQLITE -version=Have_ttracker -version=Have_docopt -version=Have_ttracker_ddbc -Isrc/ -I../../../../usr/include/dmd/gtkd3 -I../../.dub/packages/docopt-0.6.1-b.5/source -Iddbc/source/ -Jres/ src/ttracker/activitylist.d src/ttracker/app.d src/ttracker/db.d src/ttracker/models.d src/ttracker/package.d src/ttracker/utils.d -vcolumns
Linking...
dmd -of.dub/build/posix-debug-linux.posix-x86_64-dmd_2070-51125FF0CA3A1BF02DDAD201D7FF67B9/ttracker .dub/build/posix-debug-linux.posix-x86_64-dmd_2070-51125FF0CA3A1BF02DDAD201D7FF67B9/ttracker.o ../../.dub/packages/docopt-0.6.1-b.5/libdocopt.a ddbc/lib/libttracker_ddbc.a -L--no-as-needed -L-L-L/usr/lib/x86_64-linux-gnu -L-L-L/usr/lib/i386-linux-gnu -L-L-l:libgtkd3.so -L-L-l:libdl.so.2 -L-L--no-warn-search-mismatch -L-defaultlib=libphobos2.so -L-lsqlite3 -g
```

which produces a linker warning and linker errors (unresolved symbols):

```
/usr/bin/ld: warning: cannot find entry symbol faultlib=libphobos2.so; defaulting to 0000000000524e70
.dub/build/posix-debug-linux.posix-x86_64-dmd_2070-51125FF0CA3A1BF02DDAD201D7FF67B9/ttracker.o:(.rodata+0x98): undefined reference to `_D3gtk9ListStore12__ModuleInfoZ'
...
```

Here are the flags that are causing the issue (notice the duplicate **-L** flags): **-L-L-L/usr/lib/x86_64-linux-gnu -L-L-L/usr/lib/i386-linux-gnu -L-L-l:libgtkd3.so -L-L-l:libdl.so.2 -L-defaultlib=libphobos2.so**

dub should output the following command for the build to succeed:

```
dmd -of.dub/build/posix-debug-linux.posix-x86_64-dmd_2070-51125FF0CA3A1BF02DDAD201D7FF67B9/ttracker .dub/build/posix-debug-linux.posix-x86_64-dmd_2070-51125FF0CA3A1BF02DDAD201D7FF67B9/ttracker.o ../../.dub/packages/docopt-0.6.1-b.5/libdocopt.a ddbc/lib/libttracker_ddbc.a -L--no-as-needed -L-L/usr/lib/x86_64-linux-gnu -L-L/usr/lib/i386-linux-gnu -L-l:libgtkd3.so -L-l:libdl.so.2 -L-L--no-warn-search-mismatch -L-L-defaultlib=libphobos2.so -L-lsqlite3 -g
```

Relevant fixed part of the command line: **-L-L/usr/lib/x86_64-linux-gnu -L-L/usr/lib/i386-linux-gnu -L-l:libgtkd3.so -L-l:libdl.so.2 -L-L-defaultlib=libphobos2.so**

I've forked dub and fixed the issue there,I'm currently browsing through the tests to understand how I can write a test case for this issue, I'll submit a PR when I have.

Cheers,

JB

**Comment by s-ludwig** [comment]
Also related: The `-pthread` option in #444. The C/D compiler situation is a bit unfortunate currently when pkg-config comes into play.  Some libraries assume a C command line and some assume a D command line. Maybe the best that can be done is to maintain a list of known command line flags and their conversion to (currently) the D compiler command line (i.e. basically to what you already did in ee0bf72).

**Comment by jeanbaptistelab** [comment]
Yeah, I only handled the flags that gave me issue and the ones that do look like they are D ready (double "-L" flags are an obvious candidate), but my change allows me to use the GtkD Debian packages, so it's good enough for me ;)
The test case I added fails due to the phobos shared library not being in a known LD_LIBRARY_PATH. As I'm not familiar with the Travis CI, can I ask for help here as to how to fix this?

**Comment by s-ludwig** [comment]
Ah okay, so that reinforces my suspicion that `-defaultlib=xxx` should rather be passed to `addDFlags` instead of directly to the linker.

**Comment by jeanbaptistelab** [comment]
@s-ludwig I've scratched the old PR (#783) and created a new one for it #794 which should hopefully meet the criteria...

**Comment by wilzbach** [comment]
Closing as this has been fixed and was forgotten
