### ISSUE TITLE
Linker error with `dub test` and DMD 2.070

### ISSUE THREAD

**Issue by stonemaster** [dlang/dub#787]
I'm not sure whether this a DMD or DUB issue but starting with DMD 2.070.0 I'm getting weird linker issues when running `dub test` on my project (`dub build` is working fine though). This doesn't happen with DMD 2.069.2.

`
Linking...
../../../.dub/packages/vibe-d-0.7.28/libvibe-d_http.a(typecons_129b_4c2.o): In function `_D13typecons.47639__modtestFZv':
/home/travis/dmd2/linux/bin64/../../src/phobos/std/typecons.d:(.text._D13typecons.47639__modtestFZv+0x0): multiple definition of `_D13typecons.47639__modtestFZv'
../../../.dub/packages/dyaml-0.5.2/libdyaml.a(typecons_129b_ef9.o):/home/travis/dmd2/linux/bin64/../../src/phobos/std/typecons.d:(.text._D13typecons.47639__modtestFZv+0x0): first defined here
../../../.dub/packages/vibe-d-0.7.28/libvibe-d_http.a(typecons_129b_4c2.o):(.rodata+0x110): multiple definition of `_D13typecons.476312__ModuleInfoZ'
../../../.dub/packages/dyaml-0.5.2/libdyaml.a(typecons_129b_ef9.o):(.rodata+0x110): first defined here
collect2: error: ld returned 1 exit status
--- errorlevel 1
dmd failed with exit code 1.
`

I have dependencies to **Vibe.d** and **dyaml**.

I am filing this here because the normal build process is working correctly with `dub build`.

The complete TRAVIS CI logs
DMD 2.069.2 (**working**):
https://travis-ci.org/stonemaster/dlang-tour/jobs/115525464
DMD 2.070 (**FAILING**):
https://travis-ci.org/stonemaster/dlang-tour/jobs/115523315

**Comment by wilzbach** [comment]
This is over a year old and thus I assume that the lining issue has been resolved. Please reopen if the issue still exists
