### ISSUE TITLE
Root package ... references unknown package dub

### ISSUE THREAD

**Issue by catb0t** [dlang/dub#796]
The title is the error given by running `dub` on any valid D project folder, like https://github.com/Pure-D/workspace-d-installer or https://github.com/Pure-D/workspace-d, or even on its own source folder.

What'm I doing wrong?

**Comment by skoppe** [comment]
I am experiencing a similar issue. I think it is causes whenever code.dlang.org is not accessible, as is the case now (Fri Sep 22 09:05:40 CEST 2017).

**Comment by MartinNowak** [comment]
There should be more verbose logging on HTTP request failures by now.

We've added fallback mirrors to the dub command line tool to mitigate server side issues.
https://github.com/dlang/dub/pull/1190
https://github.com/dlang/dub/pull/1246
This will be part of the next release.

**Comment by catb0t** [comment]
I appreciate it!
