### ISSUE TITLE
any chance of a new release build

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#798]
it's been 6 months since the last release and it'd be convenient to have a new build available for download, even if it's a alpha/beta.

I want the fix to https://github.com/D-Programming-Language/dub/issues/206 available to my travis-ci build without loads of `before_install` steps.

**Comment by greenify** [comment]
@SingingBush I guess a new release will be appear around 2.071 (scheduled at the beginning of april - [more infos](http://forum.dlang.org/thread/ncvhdj$1v7u$1@digitalmars.com))
a bit off-topic: a new official release might also feature [a redesign of code.dlang.org / dub.pm](https://github.com/D-Programming-Language/dub-registry/pull/141)), which still requires some small tweaks.

**Comment by s-ludwig** [comment]
The only thing that I'd like to see finished in the new release is #785, so that the final 1.0.0 API has at least a bit of a chance to get used before 1.0.0 is actually released. But before that, I think it wouldn't hurt at all to tag an alpha release.

**Comment by SingingBush** [comment]
nice work on the redesign. I've been looking through the commit history, looks like there's a lot of changes on the way.

**Comment by wilzbach** [comment]
ping @s-ludwig - how far are you with #785?
I see that no one else yet took his/her time to review. That's a shame - we definitely need more manpower for `dub`!

**Comment by s-ludwig** [comment]
#785 should be good to go. The only thing left is an isolated change that will be necessary in a later PR.

**Comment by wilzbach** [comment]
@s-ludwig - I guess this can be closed now?
Once the dmd/dub integration is done, we hopefully get official releases in a regular cycle :)

**Comment by s-ludwig** [comment]
Yes, it should indeed be integrated with the rest of the release process then.
