### ISSUE TITLE
Separate linking for LDC

### ISSUE THREAD

**Issue by Rikarin** [dlang/dub#809]
Hello,
when will be implemented separate compilation and linking for LDC by `--build-mode=singleFile`?

Its quite slow when I must recompile whole project when I change some lines of code and this should be a useful feature to implement as fast as its possible.

Thanks.

**Comment by p0nce** [comment]
Not sure if it would be faster.
Building by package should avoid compilation of whole project. Perhaps separate your project in more packages?
For `--force` builds, using `--combined` is usually the fastest.

**Comment by Rikarin** [comment]
I am generating RTInfo for every method of every class and its slow when I have 50 classes in project.

**Comment by s-ludwig** [comment]
If you know how it would work on the command line, you could give it a go and make a pull request. It should  be straightforward implementation-wise. [`LDCCompiler.invokeLinker`](https://github.com/dlang/dub/blob/85ed67fc1c3b211eabb8086ca6350c4ec49fbee5/source/dub/compilers/ldc.d#L191) just needs to be implemented and [`DMDCompiler.inokeLinker`](https://github.com/dlang/dub/blob/85ed67fc1c3b211eabb8086ca6350c4ec49fbee5/source/dub/compilers/dmd.d#L206) can be used as a template.

**Comment by kinke** [comment]
Resolved by #1755.
