### ISSUE TITLE
defaultlib

### ISSUE THREAD

**Issue by Rikarin** [dlang/dub#812]
Cannot disable default libs. 
-nodefaultlib is deprecated in ldc and dub override my -defaultlib flag passed like
`"dflags-ldc": ["-defaultlib= ", "-debuglib= "],` so I cannot remove phobos from default libs.

**Comment by Rikarin** [comment]
When i define `"dflags-ldc"` in dependency its used for whole project, not only for that dependency

**Comment by Rikarin** [comment]
https://github.com/D-Programming-Language/dub/blob/master/source/dub/compilers/ldc.d#L167

-defaultlib=phobos is defined in ldc2.conf. This arg is redindant and do shitty things...

**Comment by p0nce** [comment]
Should be fixed in DUB master.
