### ISSUE TITLE
dub add-local not compatible with auto local discovery

### ISSUE THREAD

**Issue by vadim-goryunov** [dlang/dub#813]
on Windows with cygwin:

I have 2 local directories:
git/vibe.d  // clone of https://github.com/rejectedsoftware/vibe.d.git
project/test // my test project

I want to compile test project with locally modified vibe.d from git/vibe.d directory.
For that I use
$ dub add-local "C:\Users\vadim\git\vibe.d"
then
project/test $ dub build ----> OK

But when I am trying to build vibe.d itself:
git/vibe.d $ dub build ----------> ERROR
Unknown dependency: vibe-d:core

It seems like dub add-local prevents dub from using the current directory.
To make vibe.d building again I have to "dub remove-local" first.

$ dub add-local "C:\Users\vadim\git\vibe.d"
$ dub list
Packages present in the system and known to dub:
  vibe-d 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
  vibe-d:core 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
  vibe-d:utils 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
  vibe-d:data 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
...
$ dub remove-local "C:\Users\vadim\git\vibe.d"
$ dub list
Packages present in the system and known to dub:
  vibe-d 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:core 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:utils 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:data 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:http 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:mail 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\

vibe.d/dub.json:
"dependencies": {
                ":utils": "_",
                ":data": "_",
                ":core": "_",
                ":http": "_",
                ":mail": "_",
                ":diet": "_",
                ":mongodb": "_",
                ":redis": "_",
                ":web": "*"
        },

**Comment by rikkimax** [comment]
This was meant to have been fixed by https://github.com/dlang/dub/pull/807 but it seems it has since regressed or it never fully worked.
