### ISSUE TITLE
dub build -b dscanner

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#814]
It would be nice to have [Dscanner](https://github.com/Hackerpilot/Dscanner) and it's linting smoothly integrated into `dub` and add a new build type ala `ddox` or `cov`.

Ping @HackerPilot

Probably Dscanner should automatically detect if there's an `.dscanner.ini` file in the main repository - otherwise this logic could also be handled by dub.

**Comment by wilzbach** [comment]
Closing as everyone can simply fetch `dscanner` themselves.
With https://github.com/dlang/dub/pull/1082 this could even be a one-step process - `dub run dscanner`

**Comment by gizmomogwai** [comment]
seems that `dub lint` is implemented.
