### ISSUE TITLE
additional build steps during build

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#816]
I use Java a lot so am used to using Maven/Gradle which can have plugins applied to add functionality to the build process.

I'd like to use [SASS](http://sass-lang.com/) in my web project and have the files converted to CSS when doing a build and also to minify some javascript (when doing a release).

I've been looking at the [dub docs](http://code.dlang.org/package-format?lang=json) and it looks like this may be possible with `preGenerateCommands` or `preBuildCommands` (not sure which to go for). I'm thinking along the lines of using [nodejs](https://nodejs.org/) and [Bower](http://bower.io) to download dependencies such as Bootstrap then getting dub to move all the relevant js/css files to my project so that they are included as part of the build.

Is this something that is commonly done? does anyone have example build settings that are used to do a similar process?

If not, it would be handy if dub could do this. perhaps via some kind of plugin support. There could be some kind of _dub-sass-plugin_ that could take care of it.

**Comment by SingingBush** [comment]
I've made some progress with this. Thought it worth sharing:

```json
	"preGenerateCommands": [
		"if ! type \"npm\" > /dev/null; then echo -e \"You need to have Node.js and npm installed in order to build this project\nvisit https://nodejs.org for more info\"; exit 1; fi",
		"if ! type \"bower\" > /dev/null; then echo -e \"You need to have Bower installed in order to build this project\n run \"npm install -g bower\" to install it using the Node Package Manager\nvisit http://bower.io/ for more info\"; exit 1; fi",
		"bower install",
		"mv bower_components/jquery/dist/jquery.min.js public/js/jquery.min.js"
	],
```

**Comment by Geod24** [comment]
A lot of people use either `preBuildCommands` or `preGenerateCommands` for this, yes. In our case, we build C++ code in `preBuildCommands`. As for plugin support, there is https://github.com/dlang/dub/issues/304 . Closing as there is no actionable item, but feel free to open a discussion if you want to discuss the topic more. I'm just trying to trim down the issue list to reach a point where it can be acted on.
