### ISSUE TITLE
Transitive dflags

### ISSUE THREAD

**Issue by Rikarin** [dlang/dub#817]
Why is dflags attrib transitive?

I have 3 projects
-main
   druntime
   phobos

in druntime and phobos I set `"dflags": ["-conf="]` which works fine but in main project where I have these two dependencies as 
`"dependencies": {
    "druntime": {"path": "source/druntime"},
    "phobos2": {"path": "source/phobos"},
    ":core": "*",
},`

In main project is dflags attrib included 2 times and should be 0 becasue I dont want to use that dflags attrib for main project.

**Comment by WebFreak001** [comment]
can't reproduce transitive behavior

it's also now possible to specify dflags on dependency to inject them to certain dependencies.
