### ISSUE TITLE
subPackages declarations very brittle and unhelpful error message

### ISSUE THREAD

**Issue by Laeeth** [dlang/dub#822]
dependency "kaleidic-api:snappyd" version="*"
subPackage "./snappyd/"

if you write subPackage "./snappyd" nothing works and the error is very unhelpful.  perhaps it should be unncessary to declare the subPackage on a separate line anyway, and it should assume a default that the package directory is the same as the subpackage name.  but if nothing else is changed, subPackage should accept a directory that isn't / terminated.

**Comment by WebFreak001** [comment]
directories without trailing slash have been fixed a while ago

Problem with assuming from dependency is that directories may have other names than the package names, e.g. for generic things like `init-exec` you might want to pick a better name, and not depend on the submodule at all.
