### ISSUE TITLE
dub test shouldn't execute tests in dependencies

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#823]
As a user of a library, I expect it to be tested - so `dub test` should only run my own tests.

**Comment by wilzbach** [comment]
I just realized this is blocked by the dmd compiler. 
See also https://forum.dlang.org/post/pzphtoodygdyrcjkzojk@forum.dlang.org

Apparently @nordlow and I are similarly annoyed by this.

**Comment by rjframe** [comment]
dub could do a release build for dependencies so their tests are never compiled into the test exe. If that becomes the default behavior, there needs to be a way to override it so dependencies can be tested/debugged when necessary.

**Comment by s-ludwig** [comment]
This has been fixed on DUB's side by 1896b09d93b0eeb27f4170f2a6ddd72d9d7b1fb7 as part of #640. If all test are supposed to be run, using "dub test --combined" is currently the only way that works (because unit tests in static libraries are never run).

**Comment by wilzbach** [comment]
> This has been fixed on DUB's side by 1896b09 as part of #640.

Oh ... yet another reason for a soon release and having more frequent releases in the future ;-)

**Comment by s-ludwig** [comment]
The plan has always been to have about monthly releases, but the lack of work force has made that impossible recently. I was busy with external projects (and still am) and a lack of PR reviews lead to further delays. However, as soon as we reach 1.0.0, releases will almost certainly be tied to DMD releases, following the same branching scheme.

**Comment by wilzbach** [comment]
> This has been fixed on DUB's side by 1896b09 as part of #640.

Just gave it a try with the latest beta and it still builds the tests if the library specifies itself as `sourceLibrary`.

```
{
	"name": "bar",
	"authors": [
		"foo"
	],
	"description": "A test D application.",
	"copyright": "Copyright © 2016, foo",
	"license": "proprietary",
	"dependencies": {
            "dgraph": "~>0.0.2",
	}
}
```

**Comment by s-ludwig** [comment]
Okay, for `sourceLibrary` it indeed won't work, but a `sourceLibrary` package is prone to run into linker anyway, if it contains anything more than function prototypes. The documentation needs to stress that point. So in this case, "dgraph" should definitely not be a `sourceLibrary`.

**Comment by andre2007** [comment]
@wilzbach I think this issue can be closed?
