### ISSUE TITLE
Support wildcards in `sourceFiles`

### ISSUE THREAD

**Issue by CyberShadow** [dlang/dub#825]
I've tried adding a Dub configuration to Digger. Its directory structure is as follows:

```
Digger/ [project root]
|- dub.sdl
|- digger.d
|- bisect.d
|- (...)
|- ae/ [Git submodule]
|  |- dub.sdl
|  +- ...
+- work/
   +- repo/
      |- dmd/
      |  +- (DMD source files...)
      |- phobos/
      |  +- (Phobos source files...)
      +- (...)
```

The goal is to add all `*.d` files in the current directory only, but excluding subdirectories (as those belong to their own Dub project).

My first attempt was: `sourceFiles "*.d"`. I noticed that `excludedSourceFiles` allows glob matching explicitly, and `sourceFiles` uses the word "pattern" as a placeholder in the documentation, so I thought that'd work. Didn't.

My second attempt was:

```
# In lieu of `sourceFiles "*.d"`
sourcePaths "."
excludedSourceFiles "*/*"
excludedSourceFiles "digger-web.d"
```

However, although this did allow `dub build` to work, `dub describe` took an unreasonable amount of time (and my editor runs that command every time I open a file in that project). I'm guessing this is because Dub first tries to find all `*.d` files under `sourcePaths`, which in this case includes all of DMD/Druntime/Phobos and their tests, then filters out everything that has a forward slash in its path.

I'm going to just enumerate all `.d` files by hand for now, but maybe it'd be nice if `sourceFiles` supported wildcards, or if `excludedSourceFiles` was applied early during the `sourcePaths` scan as an optimization, or something.

**Comment by Geod24** [comment]
https://github.com/dlang/dub/pull/1002
