### ISSUE TITLE
dub init --format json (broken in beta)

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#826]
I guess the `--format` is no longer checked for?

```
dub init --format json
Package recipe format (sdl/json) [json]:
```

**Comment by wilzbach** [comment]
Ah sorry - just realized that the interactive mode can be disabled by `-n` :)
Sorry for the spam.

**Comment by s-ludwig** [comment]
We could turn this into an enhancement request, actually. If `--format` is present, the interactive question could be skipped altogether - probably not a frequent use case, but still a good idea.
