### ISSUE TITLE
error: Non-optional dependency not found in dependency tree

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#828]
At [mir](https://github.com/libmir/mir/blob/master/dub.json) we have specified the dependency `imageformats` for some subconfigs. However it should not be needed for compiling the library or running the tests. With the attached json I get:

```
dub
Fetching imageformats 6.0.0 (getting selected version)...
Non-optional dependency imageformats of mir not found in dependency tree!?.
```

```
{
	"name": "bar",
	"authors": [
		"foo"
	],
	"description": "A test D application.",
	"copyright": "Copyright © 2016, foo",
	"license": "proprietary",
	"dependencies": {
            "mir": "~>0.15.2"
	}
}
```

**Comment by s-ludwig** [comment]
I missed #803 when preparing the beta. I'd hope that this fixes this issue, would be great if you could retry with GIT master. Otherwise, the next beta will contain those fixes.

**Comment by wilzbach** [comment]
> I'd hope that this fixes this issue, would be great if you could retry with GIT master.

Just tried - nope :/

**Comment by s-ludwig** [comment]
I tried with the package recipe above and it works for me (both the beta and master). Anything else that could be necessary to reproduce this? How does "dub.selections.json" look like?

**Comment by wilzbach** [comment]
> I tried with the package recipe above and it works for me (both the beta and master). Anything else that could be necessary to reproduce this?

Removing the packages from the cache worked:

```
rm -rf ~/.dub/packages/imageformats-*
rm -rf ~/.dub/packages/mir-*
```

Thanks for taking your time :)
I think it might be due to the fact that the format changed and you now use a folder in folder?

```
~/.dub/packages/imageformats-6.0.0/imageformats/
~/.dub/packages/mir-0.15.2/mir/
```

I guess this could potentially also break other setups, so probably at least worth a notice to clean the cache.
So instead of "Contains some critical changes regarding path based dependencies", you should put this at top and advise to remove the entire `~/.dub` after upgrade.

**Comment by s-ludwig** [comment]
Indeed seems to have something to do with the directory structure. I've moved the existing files back to their parent folder and get the error now. However, the transition is supposed to be seamless and we need to get this fixed. I'll look into this in the evening if I get some more time.

**Comment by s-ludwig** [comment]
So the problem was that imageformats, although present, wasn't correctly detected due to its "imageformats" sub folder, which lead DUB to believe that it already had the new folder structure. The fetch operation that got triggered as a consequence couldn't complete, because the target directory already existed.
