### ISSUE TITLE
dependencies being pulled for unused configurations 

### ISSUE THREAD

**Issue by cyisfor** [dlang/dub#844]
dub is pulling all dependencies from all configurations, even if a particular configuration is selected.

To reproduce:
$ clone https://github.com/buggins/ddbc
$ dub -v build --config=SQLite
...
Search for versions of mysql-native (1 package suppliers)
...
Fetching mysql-native 0.1.4 (getting selected version)...
...

This is probably a similar issue to #831.

**Comment by Geod24** [comment]
Duplicate of either #1217 or #1706
