### ISSUE TITLE
Pass all arguments to dub scripts

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#856]
As probably the first tester of the new dub script feature I want to make a request:
Dub should send all arguments after the script to it, because

```
dub my-script.d --flag // doesn't work
./my-script --flag // doesn't work
```

of course I can use `dub my-script.d -- --flag`, but this feels more than unintuive.

@s-ludwig would you accept a PR that fixes this?

Related to #805.

**Comment by Geod24** [comment]
It would feel very weird to me to have this special case. `--` is well known in the Linux world and I've personally always found that syntax consistent with other tool.
I don't think introducing a new syntax depending on the arguments order wouldn't be an improvement.

**Comment by wilzbach** [comment]
> It would feel very weird to me to have this special case. -- is well known in the Linux world and I've personally always found that syntax consistent with other tool.
> I don't think introducing a new syntax depending on the arguments order wouldn't be an improvement.

My point was that now with the `#!/usr/bin/env dub` shebang line dub is now an "interpreter", hence it shouldn't read any of my flags when I call the file - that's how all other interpreter work too!

```
./foo.sh -my-flag   // works
./foo.rb -my-flag   // works
./foo.py -my-flag   // works
./foo.pl -my-flag    // works
./foo.js -my-flag    // works
./foo.dub -my-flag // doesn't work
```

**Comment by s-ludwig** [comment]
I was worried about the special case here, too, it also means that the `dub script.d` syntax won't support passing any arguments to DUB itself. However, this syntax is already there primarily to support shebang scripts, and AFAIK this is the only portable way to be able to pass parameters to the application.

So my proposal is to document the `dub script.d [script-args...]` syntax as something specific to shebang scripts. `dub run script.d [dubargs...] -- [appargs...]` will still be available as a generic counterpart.

**Comment by wilzbach** [comment]
> So my proposal is to document the dub script.d [script-args...] syntax as something specific to shebang scripts.

Thanks - that was my idea too!
