### ISSUE TITLE
dub fails to resolve (prerelease) dependencies for Dscanner

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#867]
We're having some problem with Dscanner to corrrectly resolve dependencies.

https://github.com/Hackerpilot/Dscanner/issues/350#issuecomment-224228507

It seems that dub can't resolve `"libdparse": "==0.7.0-alpha11"` from dscanner and `"libdparse": ">=0.7.0-alpha9 <0.8.0"` from dsymbol (dscanner requires `"dsymbol": "~>0.2.0-alpha7"` which is correctly resolved to `0.2.0-alpha7`).

As a second problem, it's also a bit unclear what the wobbly version specification (`~>0.7.0-alpha11`) does, is it `>=0.7.0-alpha11 < 0.7.1` or `>=0.7.0 <0.7.1`). It should be the former, but dub is selecting `0.7.0-alpha9` in that case. Might be related to the above issue though.

**Comment by s-ludwig** [comment]
Just quickly responding to the second one:

> As a second problem, it's also a bit unclear what the wobbly version specification (~>0.7.0-alpha11) does, is it >=0.7.0-alpha11 < 0.7.1 or >=0.7.0 <0.7.1). It should be the former, but dub is selecting 0.7.0-alpha9 in that case. Might be related to the above issue though.

"-alpha11" is less than "-alpha9" according to SemVer, because it's compared lexicographically. Should be "-alpha.11" and "alpha.9" respectively instead.

**Comment by Hackerpilot** [comment]
>"-alpha11" is less than "-alpha9" according to SemVer, because it's compared lexicographically.

wat

**Comment by s-ludwig** [comment]
The pre-release part is compared by splitting it into `.` separated sub strings. Strings starting with a digit will be compared numerically and must only contain digits, and other strings are compared lexicographically. See also http://semver.org#spec-item-9 and http://semver.org#spec-item-11

**Comment by MartinNowak** [comment]
Anything we should do about this? Explicitly mentioning that in the paragraph about versioning, modifying the semver parser to recognize this regularly used pattern, or add it as a warning to the dub registry?
Unfortunately `alpha.11` sorts less than even `alpha1` (if I understood that right), so we can't go back and add the tags.

**Comment by s-ludwig** [comment]
I wouldn't deviate from the SemVer rules, but adding a warning sounds like a good idea. It should just be narrow enough to not flag false positives.

**Comment by WebFreak001** [comment]
opened an issue on dub-docs, closing this
