### ISSUE TITLE
the curl.lib included in the source is corrupt when building with ldc

### ISSUE THREAD

**Issue by KevinBrogan** [dlang/dub#873]
Wanted to build dub on windows with ldc since it's my compiler and I don't want to install dmd just to built dub.

build.bat fails to detect ldc2 so I renamed ldmd2 to dmd and the compilation completed fine. The linker was unable to link in the curl.lib however.

> C:\Windows\system32\cmd.exe /s /c "C:\ldc2\bin\amd64.bat link.exe /NOLOGO /LARGEADDRESSAWARE:NO /DEBUG /OPT:REF /OPT:ICF /OUT:bin\dub.exe bin\dub.obj curl.lib /LIBPATH:C:/ldc2/bin/../lib phobos2-ldc.lib druntime-ldc.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib"
> WARNING: no Visual Studio installation detected
> curl.lib : fatal error LNK1136: invalid or corrupt file
> Error: `C:\Windows\system32\cmd.exe /s /c "C:\ldc2\bin\amd64.bat link.exe"` failed with status: 1136

I moved over the copy of curl.lib (14 KB) that comes with ldc and replaced the copy that comes with dub (9 KB). Build succeeds now.

You can ignore the bit about "WARNING: no Visual Studio installation detected", as I have installed only the build tools and not the full studio package.

**Comment by wilzbach** [comment]
This seems to have been an LDC issue.
As it's over a year old and most likely fixed, I am closing this. Please reopen if still existent

**Comment by wilzbach** [comment]
This seems to have been an LDC issue.
As it's over a year old and most likely fixed, I am closing this. Please reopen if still existent
