### ISSUE TITLE
how to update package description?

### ISSUE THREAD

**Issue by zoujiaqing** [dlang/dub#881]
hunt framework description is updated:
https://github.com/putao-dev/hunt

but, dub site package page don't update!
http://code.dlang.org/packages/hunt

**Comment by BBasile** [comment]
Add a new git tag, this is the only way. Amend/rebase won't work, (see also https://github.com/dlang/dub-registry/issues/151, which was asking for this but actually closed because I don't give a damn, "just put a new tag" works).

**Comment by BBasile** [comment]
@ohdatboi, i'm curious to know how did you manage to close an issue that you didn't open. Are you in dlang organization ?

**Comment by ohdatboi** [comment]
@BBasile yes I am. Hi!

**Comment by BBasile** [comment]
Can you update your membership visibility so that we can see you in this list : https://github.com/orgs/dlang/people please ?
