### ISSUE TITLE
single file package, random failure

### ISSUE THREAD

**Issue by BBasile** [dlang/dub#885]
I use the example posted on dlang.org NG 1.0 announce to test the feature, implemented in Coedit. I've get some random failure, with always the same message:

> spawnProcess(): Failed to execute program: Text file busy
Program exited with code 1
error: the process (/home/basile/bin/dub) has returned the signal 512

**Comment by s-ludwig** [comment]
Could it be that two DUB instances are running in parallel? It appears that the compiled executable gets modified while it is still being executed. A possible fix within DUB in that case would be to `rm` the file before invoking the linker.

**Comment by BBasile** [comment]
This wouldn't be logical. On linux, executable files are not locked when executed and we can recompile them even if the previous version is being run. I will invistigate more but I keep this issue opened as a reminder.
