### ISSUE TITLE
Warnings printed during dub describe

### ISSUE THREAD

**Issue by tofuninja** [dlang/dub#886]
Warnings are printed when dub describe is called, this will break tools that are expecting just pure json. 

Edit: 
Just to clerify, I am talking about warnings like... 

```
## Warning for package dgraphics, configuration Editor_debug ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

debugMode: Call DUB with --build=debug
debugInfo: Call DUB with --build=debug
unittests: Call DUB with --build=unittest
```

**Comment by s-ludwig** [comment]
Warnings should always be emitted on `stderr` instead of `stdout`, so that the tool can still use the raw JSON and can possibly display the `stderr` output somewhere else. I've double-checked for the warning above and it gets correctly written to `stderr`.

**Comment by tofuninja** [comment]
Hmm, well I only posted because it was breaking DKit on sublime text for me. I looked and as far as I can tell it shouldn't be capturing stderr when invoking dub but it is, suppose it's a Dkit bug then...

**Comment by wilzbach** [comment]
> suppose it's a Dkit bug then...

Closing.
