### ISSUE TITLE
single file package. A way to generate exe on project folder ?

### ISSUE THREAD

**Issue by Zardoz89** [dlang/dub#887]
I'm trying to use ```dub build --single my_program.d``` with a "script" program that I wrote. Previously, I was using rdmd, and now I'm trying to use dub 1.0.0, so I can access dub packages. 

I use "-v" option to see that dub puts my executable file inside of a mangled directory on the temporal files folder. I need to have the executable file on the same folder where the source file is, or at least on a predictable path, so I can copy it to /usr/local/bin/ . 

I try to set **targetPath** and **wordkingDirectory** to "/usr/local/bin" and to "$PACKAGE_DIR" without any success.

**Comment by s-ludwig** [comment]
Currently single-file are packages always forced to be built with `--temp-build`. The main idea of this was to support D script files with shebang lines, but for pure "dub build" it indeed doesn't really make sense. The question is if it should only be enabled for the `dub somescript.d` syntax, or also for `dub run --single somescript.d` (and never for `dub build --single somescript.d`). I'd say it should only be enabled for the special shebang syntax, to keep the other two consistent with normal builds.

**Comment by Zardoz89** [comment]
Perhaps  --temp-build not should be forced  if targetPath is defined.
