### ISSUE TITLE
Homebrew Dub version 

### ISSUE THREAD

**Issue by dkdewitt** [dlang/dub#889]
Im showing the homebrew version of dub as 0.9.25.  Debian is showing the current version as 1.0.0

dub --version
DUB version 0.9.25, built on May 24 2016

brew update
Already up-to-date.

**Comment by JackStouffer** [comment]
I just ran into this as well.

**Comment by John-Colvin** [comment]
Sorry, haven't been keeping up. Just waiting on this to be merged: https://github.com/Homebrew/homebrew-core/pull/3622

**Comment by John-Colvin** [comment]
Should be up to date now
