### ISSUE TITLE
Internal compiler error (gdc-4.8 on raspberry pi 1 B+)

### ISSUE THREAD

**Issue by DenianArthurShades** [dlang/dub#890]
Hi,

I'm trying to compile dub on my raspberry pi 1 B+, but after about an hour to an hour and a half, the process fails. The only message is "internal compiler error: killed (cc1d)", accompanied by some generic stuff about reading up on the known bugs.

I found a hint somewhere that this might be caused by a lack of memory. Can somebody confirm whether this is the case or whether I need to do something else?

I'm using gdc-4.8, the "build-gdc.sh" (after changing line 5 to read "GDC=gdc-4.8") and have installed libcurl4-openssl-dev, so I don't know what else I might be missing...

**Comment by s-ludwig** [comment]
Yes, this is very likely to be the reason. You can, at the expense of a very slow compilation process, work around it by creating a swap file/partition (see the "swapon" command). I'm not sure of it works on the RPi, but you could also try the pre-compiled ARM binary (should be ARMv6, but I'd have to double-check): http://code.dlang.org/files/dub-1.0.0-linux-arm.tar.gz

**Comment by DenianArthurShades** [comment]
Thanks, I'll try using a swap file. The precompiled binary terminates with the message "Invalid instruction" (or similar, my system language is set to German...), which is why I'm trying to compile it in the first place.

**Comment by DenianArthurShades** [comment]
Ok, I tried increasing the size of my swap file from 100 MB to 1 GB. Instead of the "killed (cc1d)" thing, my output now loks like this:

`Generating version file...`
`Running gdc-4.8...`
`source/dub/dub.d: In member function ‘getPackage’:`
`source/dub/dub.d:1311: internal compiler error: Speicherzugriffsfehler`
`Please submit a full bug report,`
`with preprocessed source if appropriate.`
`See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.`

Specherzugriffsfehler ~ memory access violation, I think... Is this still due to insufficient memory?

**Comment by s-ludwig** [comment]
That appears to be a different cause. If this is the latest version of GDC, you should probably report this to the GDC devs: <http://bugzilla.gdcproject.org>
BTW, if you haven't already, you might also want to try LDC, because it is much more up to date regarding the compiler front end used.

**Comment by wilzbach** [comment]
Closing as this over a year old and seems to be a compiler issue.
LDC has vastly improved their arm support lately and I know that dub is available on Termux on Android.
