### ISSUE TITLE
Confusing error message for non existing version

### ISSUE THREAD

**Issue by jacob-carlborg** [dlang/dub#896]
If I specify a package as a dependency with a version that doesn't exist I get this not so descriptive error message:

```
Root package <package> references unknown package <dependency>
```

From the error message it sounds like the actual dependency doesn't exist when in fact it's the specified version.

**Comment by s-ludwig** [comment]
Usually the error message would be slightly better:

    Root package <package> reference <dependency> <version> cannot be satisfied.

The error message above probably stems from the fact that it currently cannot distinguish between non-existent packages and packages with no available versions. Is the dependency on code.dlang.org in your case? Otherwise, which tagged version(s)/branch(es) was/were available at the time where that error occurred?

**Comment by jacob-carlborg** [comment]
>  Is the dependency on code.dlang.org in your case?

Yes, `vibe-d`. I though I remembered that `0.7.30` had been released but it's still only in alpha.

**Comment by s-ludwig** [comment]
Interesting, I get "Root package missingdeptest reference vibe-d ~>0.7.30 cannot be satisfied.", as expected. My only guess is that the connection to code.dlang.org failed for one reason or another. So the enhancement should probably be to output an additional warning whenever connecting to the/a registry fails.

**Comment by jacob-carlborg** [comment]
it occurs when I run `dub upgrade`, if that makes any difference.

**Comment by s-ludwig** [comment]
So it does still occur, with code.dlang.org being reachable? Can you share your package recipe?

**Comment by jacob-carlborg** [comment]
> So it does still occur, with code.dlang.org being reachable?

Yes, it's reachable.

```sdl
name "foo"
description "foobar"
copyright "Copyright © 2016"
authors "Jacob Carlborg"

dependency "ddb" version="~>0.2.4"
dependency "dyaml" version="~>0.5.2"
dependency "string-transform-d" version="~>1.0.0"
dependency "vibe-d" version="0.7.30-alpha.3"

configuration "application" {
  targetType "executable"
  versions "VibeDefaultMain"
}

buildType "release" {
  excludedSourceFiles "source/spec/**/*"
  buildOptions "optimize" "inline"
}
```

**Comment by jacob-carlborg** [comment]
It's the `ddb` dependency that causes the issue. I was able to reproduce the issue with a newly generate vibe.d application (using dub 1.0.0) and then adding `ddb` as a dependency and selecting a version of `vibe-d` that doesn't exist.

**Comment by s-ludwig** [comment]
Okay thanks, got it! It was a flag that got overwritten after the version candidates for the "foo" and the "ddb" packages got merged, so that it thought that vibe-d actually had no version candidates at all.

**Comment by jacob-carlborg** [comment]
Thanks.
