### ISSUE TITLE
Dub fetch all vibe-d dependencies, even if there is no reason

### ISSUE THREAD

**Issue by Kozzi11** [dlang/dub#899]
I have small test app with this dub.json:

    {
	    "name": "cronchecker",
	    "authors": [
	    	"Daniel Kozak"
	    ],
	    "dependencies": {
	    	"mysql-native": "~>0.1.4",
	    	"vibe-d:data": "~>0.7.29"
	    },
	    "description": "Small cron distribute checker",
	    "copyright": "Copyright © 2016, Eurosat C.S. spol. s r.o.",
	    "license": "proprietary"
    }

But when I try use dub build it try to download complete vibe-d instead of vibe-d:data

    Fetching libevent 2.0.1+2.0.16 (getting selected version)...
    Placing libevent 2.0.1+2.0.16 to /home/kozak/.dub/packages/...
    Fetching openssl 1.1.4+1.0.1g (getting selected version)...
    Placing openssl 1.1.4+1.0.1g to /home/kozak/.dub/packages/...
    Fetching memutils 0.4.6 (getting selected version)...
    Placing memutils 0.4.6 to /home/kozak/.dub/packages/...
    Fetching libasync 0.7.9 (getting selected version)...
    Placing libasync 0.7.9 to /home/kozak/.dub/packages/...
    Performing "debug" build using dmd for x86_64.
    vibe-d:utils 0.7.29: building configuration "library"...
    vibe-d:data 0.7.29: building configuration "library"...
    vibe-d:core 0.7.29: building configuration "libevent"...
    vibe-d:http 0.7.29: building configuration "library"...
    vibe-d:diet 0.7.29: building configuration "library"...
    vibe-d:mail 0.7.29: building configuration "library"...
    vibe-d:mongodb 0.7.29: building configuration "library"...
    vibe-d:redis 0.7.29: building configuration "library"...
    vibe-d:web 0.7.29: building configuration "library"...
    vibe-d 0.7.29: building configuration "libevent"...
    mysql-native 0.1.4: building configuration "library"...

**Comment by s-ludwig** [comment]
The problem is that `mysql-native` has the vibe.d umbrella package as a dependency: https://github.com/mysql-d/mysql-native/blob/master/package.json#L15

It should be changed to  `vibe-d:core`.
