### ISSUE TITLE
dub build lib version

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#900]
dub build lib (eg: libdparse) only builds the earliest version of lib it seems; how to specify which version to build?
likewise with fetch

**Comment by s-ludwig** [comment]
`dub fetch` supports a `--version=...` flag, but for `dub build`, `--root` is currently the only candidate (e.g. `dub build pack --root=~/.dub/packages/pack-1.0.0/pack`). Supporting `--version` there doesn't seem like a bad idea, though.

**Comment by WebFreak001** [comment]
version spec is supported in most places through `dub build libdparse@0.0.0` now
