### ISSUE TITLE
List paths

### ISSUE THREAD

**Issue by jmh530** [dlang/dub#908]
Dub has the ability to list packages. However, it does not have the ability to show what are the paths that dub is actually searching for. For instance, if I add-path a folder and add-local a package, then there are times where I might want that information rather than just the list of packages that result in those decisions. For instance, it might have been some time since I put in those commands. I might have done a fresh install of dub and want to re-set all the paths or something. Alternately, I might have put in a path incorrectly and would want to view what is in there.

I think what would resolve this is a flag for list that would print out what is in (on Windows at least):
[pathtouser]\AppData\Roaming\dub\packages\local-packages.json

**Comment by WebFreak001** [comment]
duplicate / moving into #705
