### ISSUE TITLE
Using wrong Libraries for LDC2 on Windows.

### ISSUE THREAD

**Issue by skl131313** [dlang/dub#912]
Get the following error when I try to build using dub with "dub --build=debug --compiler=ldc2 --arch=x86". I get the following error:

> Using Visual Studio: C:\Program Files (x86)\Microsoft Visual Studio 14.0\
> phobos2-ldc.lib(gzlib.c.obj) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'
> Error: `C:\Windows\system32\cmd.exe /s /c "C:\ldc2\bin\x86.bat link.exe"` failed with status: 1112 ldc2 failed with exit code 1112.

Compiling a single source file results in the correct libraries being used thus a successful compile. With the command "ldc2 -m32 -g main.d". Not sure if dub is the cause of the error but it seems it might be.

**Comment by MrSmith33** [comment]
Can confirm. 32 bit build produces 64 bit executable

**Comment by WebFreak001** [comment]
seems like this may have been compiler configuration issues in the past. Current compiler and dub versions properly build a 32 bit executable.
