### ISSUE TITLE
Dub 1.0.1 release

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#913]
While submitting a benchmark PR to https://github.com/kostya/benchmarks/pull/101, we bumped into #887 which was fixed with  2a9bfe367b177d53d5446aa90e1fd7ca678309f5 about two months ago. 

While I personally don't mind (I really ok with building from source), I think it would be nice if patches are released more quickly as this casts a bad light on D's infrastructure.

I know that minor releases are supposed to be synchronized with DMD, but I guess there's simply no procedure on how to release patch releases yet? How about simply as said releasing a patch version when a major bug has been fixed and synchronizing the minor release with @MartinNowak?

CC @9il

**Comment by s-ludwig** [comment]
The plan is to synchronize DUB and DMD releases, starting with DMD 2.072.0. Right now, we could still do an intermediate minor release (there are already functional changes, so it would be 1.1.0).

**Comment by s-ludwig** [comment]
Hmm, sorry, I didn't manage to pull this off. I was completely busy for a month and then the 2.072.0 release got so close that it didn't make sense to put out a release directly beforehand.
