### ISSUE TITLE
DUB is slower than rdmd when a build error occurs

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#915]
I accidentally discovered that `dub` is noticeable slower than `rdmd` when a build error occurs.
I found this with an  [example](http://sprunge.us/HKJj) taken from the [template meta programming gem](http://tour.dlang.io/tour/en/gems/template-meta-programming) of the DTour.

```
> python -m timeit -n 20 -s 'import os' 'os.system("rdmd --force foo.d 2> /dev/null")'
20 loops, best of 3: 169 msec per loop
> python -m timeit -n 20 -s 'import os' 'os.system("dub run --single --force foo.d > /dev/null 2>&1")'
20 loops, best of 3: 211 msec per loop
```

I tested a couple of more files by randomly inserting errors and the build times and their difference shown above stayed similar.

Interestingly I could only observe this behavior on errors, for successful single file builds `dub` [seems to be faster](https://issues.dlang.org/show_bug.cgi?id=16431). So the "fight" is 1:1 atm ;-)

**Comment by s-ludwig** [comment]
My guess is that DUB has a higher initialization overhead, while RDMD's dependency pass overhead vanishes if an error occurs (linker errors should be different, though).

**Comment by wilzbach** [comment]
> My guess is that DUB has a higher initialization overhead, while RDMD's dependency pass overhead vanishes if an error occurs (linker errors should be different, though).

Yep I learned that RDMD runs DMD twice on the root file (especially with all the CTFE that's quite an overhead), however if an error occurs it obviously already terminates on the first run.
FWIW I might be [successful at hacking rdmd](https://github.com/dlang/tools/pull/191) to avoid running DMD twice if only the standard library is imported, so then only DUB's overhead would be left.

**Comment by Geod24** [comment]
There's quite a bit of overhead in dub, and we definitely need to improve things, but I don't think we have much actionable items in this issue which are not in other issues (most recently https://github.com/dlang/dub/issues/2338 ) so I'm going to close this.
