### ISSUE TITLE
wrong behaviour when run `dub test` for new vibe.d projects

### ISSUE THREAD

**Issue by deviator** [dlang/dub#916]
dub automatically added `VibeCustomMain` for test projects and new vibe does not compiles with static assertion in vibe.appmain ("Both, VibeCustomMain and VibeDefaultMain are defined....")

https://github.com/dlang/dub/blob/eeff313d6e797276f273b0e7efa62821fefa5f1c/source/dub/dub.d#L511

**Comment by s-ludwig** [comment]
Fixed by dee4a6028f89c45ab3f86b557a49a83735e9421a
