### ISSUE TITLE
DUB scripts, need to call DUB two times to build dependencies

### ISSUE THREAD

**Issue by BBasile** [dlang/dub#921]
I've started to use this feature because it's perfect for libraries examples. However I've noticed that the first time one types `dub example.d`, the compilation fails because of a missing dependency (e.g with a message saying `folder/libstuff.a: no file or folder of this type`. The second time the dependency is build and it works. I'd expect the script to works _directly_ the first time.

**Comment by s-ludwig** [comment]
Do you have an example package recipe? I didn't quite get how/where the library and the application each get built in this case.

**Comment by BBasile** [comment]
Yes, and I can say also that it happens when the script has "level 2" dependencies:

In https://code.dlang.org/packages/kheops, the file https://github.com/BBasile/kheops/blob/master/runnable/btn_grid.d shows the issue.

To reproduce it I have to delete the dub package for the dependency iz (In .`dub/packages/`). I also removed all the .dub stuff (hidden folder + selection.json + binary) folders inside the main kheops repo.

Then the first time I get:

> cc: error: .dub/packages/iz-0.6.0-alpha4/iz/lib/libiz.a: Aucun fichier ou dossier de ce type
--- errorlevel 1
dmd failed with exit code 1.

The second time it works.

**Comment by BBasile** [comment]
I wonder if what happens is that the sub dependency is being build during the first call but not yes produced when the script is compiled.

**Comment by s-ludwig** [comment]
Fix is ready for review: #921

**Comment by s-ludwig** [comment]
The problem was that the dependencies were built in the system temp folder (because the script invocation syntax causes a "temporary" build), but read from their original location. And due to another bug, they actually got copied from the temp folder to their original location on the second run, so that it actually worked in that case.

**Comment by BBasile** [comment]
No, the problem is still there.

**Comment by BBasile** [comment]
I don't know if it helps but the setup is: kheops is obtained via `git clone`, not via `dub fetch`. Then in the git repo you browse to `/runnable` and `dub btn_grid.d`, but only after removing the `/bin` content of the git repo (if any) and the bin produced for iz (if any in `dub/packages/`).

**Comment by BBasile** [comment]
sorry, just forget the previous comments, I thought it was merged already !

**Comment by BBasile** [comment]
#922 seems ok.
