### ISSUE TITLE
LDC Config Using Wrong DefaultLib For Linux

### ISSUE THREAD

**Issue by marktrz** [dlang/dub#927]
Currently it is setting the default lib to be "phobos2", this causes ldc to link to dmd's library instead of to it's own. It needs to instead link to phobos2-ldc.so to function correctly.

https://github.com/dlang/dub/blob/master/source/dub/compilers/ldc.d#L205

**Comment by ZombineDev** [comment]
BTW, for GDC it should be `libgphobos`. They've recently added support for shared libraries:
https://github.com/D-Programming-GDC/GDC/pull/214

**Comment by p0nce** [comment]
My opinion is that `-defaultlib` belongs to the compiler configuration, not DUB.

**Comment by s-ludwig** [comment]
Fixed by #979.
