### ISSUE TITLE
Couldn't resolve host name on handle

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#928]
```
dub fetch mir --version=0.17.0-alpha2
Fetching mir 0.17.0-alpha2...
Couldn't resolve host name on handle 1EAE6D0
```

**Comment by dhasenan** [comment]
Can't reproduce on linux64 with latest dub. Is this error still occurring? If so, can you provide more info on the environment you used to produce this error?

**Comment by MartinNowak** [comment]
That's a temporary curl name resolving error, we've added more verbose error output for request errors recently.
https://github.com/dlang/dub/pull/1104
