### ISSUE TITLE
Dub generate don´t create  ldc compiler flag on sublime

### ISSUE THREAD

**Issue by SrMordred** [dlang/dub#931]
On:
Windows 10 (x64) 
Dub 1.0.0

`dub generate sublimetext --arch=x86_64 --compiler=ldc_or_path_to_ldc`

generate the project.sublime-project with:

`"cmd": [
   "dub",
   "build",
   "--build=debug",
   "--arch=x86_64"
]`
(without the compiler flag)

**Comment by s-ludwig** [comment]
Fixed by #983.
