### ISSUE TITLE
wrong dependency solving of local packages

### ISSUE THREAD

**Issue by deviator** [dlang/dub#934]
If I create 3 projects A, B, C, and use A in B, A and B in C I get strange error: Sub package a: doesn't exist. But if I don't write dependency A in dub.sdl in C project all builds successful.

packA/dub.sdl:
```
name "packa"
targetType "library"
```
packA/source/packa.d:
```d
module packa;
float superFunc(float a, float b) { return a + b; }
```
packB/dub.sdl:
```
name "packb"
dependency "packa" path="../packA"
targetType "library"
```
packB/source/packb.d:
```d
module packb;
import packa;
float someCode(float a, float b) { return superFunc(a,b) * a; }
```
packC/dub.sdl:
```
name "packc"
dependency "packa" path="../packA" // if comment it out all builds and works fine
dependency "packb" path="../packB"
targetType "executable"
```
packC/source/app.d:
```d
import std.stdio;

import packa;
import packb;

void main()
{
    writeln(superFunc(3,4));
    writeln(someCode(3,4));
}
```

dub from master
```
dub --version
DUB version 1.0.0, built on Sep 23 2016
```

**Comment by MrSmith33** [comment]
I have the same issue. I use relative path-based dependencies.
Package graph is the same.

**Comment by s-ludwig** [comment]
PR: #969

**Comment by s-ludwig** [comment]
Turned out to be an different instance of #959, which is already fixed on stable (not yet in a beta release).
