### ISSUE TITLE
specify compiler in dub file

### ISSUE THREAD

**Issue by deviator** [dlang/dub#935]
For example [mir](https://github.com/libmir/mir) can builds only with LDC. It can be useful to specify `defaultCompiler` in dub.sdl (dub.json) and list of available compilers for resolving dependencies compiler variants.

**Comment by s-ludwig** [comment]
Related: #108

**Comment by andre2007** [comment]
In the meantime you can specify compiler as toolchain requirement in dub.json and you can place a settings file within the dub project folder in which you can specify the default compiler.
