### ISSUE TITLE
Command to list dependency paths being used

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#937]
It'd be helpful to have a cmdline command to list, for the current project, all the dependencies being used AND the actual paths being used for each of them. This would be particularly helpful to see whether a local override is or isn't being used.

I find I'm often double-checking the --verbose output to see which copy of a package is being used, but that's difficult to read.

**Comment by WebFreak001** [comment]
overrides are deprecated/removed and the whole thing should be more transparent to the user now. A command like this is likely not needed in regular basis anymore, verbose output or some kind of "dub where" command (#1991) should be enough to cover most use-cases.
