### ISSUE TITLE
using a dub built library outside of dub

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#939]
is this use case supported?

Suppose somelib depends on other (dub) libaries.

```
dub fetch somelib && dub build somelib
rdmd -L-L~/.dub/packages/somelib-1.0.0/somelib -L-lsomelib -I$HOME/.dub/packages/somelib/source mymain.d
```

I am getting undefined sumbol errors on symbols defined in dependencies of somelib.

What would be a workaround?

Furthermore, could we have a command to generate -L-L~/.dub/packages/somelib-1.0.0/somelib -L-lsomelib ?
eg:

dub get_dmd_flags somelib
-L-L~/.dub/packages/somelib-1.0.0/somelib -L-lsomelib

or, perhaps more useful (and usable both in dmd and ldc):

```
dub get_flags_imports somelib
~/.dub/packages/somelib-1.0.0/somelib/source

dub get_flags_libdirs somelib
~/.dub/packages/somelib-1.0.0/somelib

dub get_flags_libnames somelib
somelib
```

**Comment by WebFreak001** [comment]
This usecase should work, as long as you properly expose functions and use them as needed.

Other build tools rely on this behavior as well.

For shipping libraries to users, issue #2191 might be better to track this.
