### ISSUE TITLE
dryrun option (list commands that would be executed, without executing them)

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#942]
would be useful, eg to use dub, understand what compile flags, libraries, import paths are used, and possibly use them outside of dub (useful for a number of cases where dub falls short)

EDIT:
just found --annotate; dub --annotate doesn't seem to print anything though; also it's hard to find (should also mention dryrun in docs to describe what it does, easier to search)

EDIT: using `dub --verbose build` is a workaround (but not an actual dryrun)

**Comment by s-ludwig** [comment]
Yeah, `--annotate` must be dragged down to a lower level - `BuildGenerator` in particular. Currently it exits too early. I also agree that `--dry-run` is a better name, both should be supported for a while before `--annotate` gets removed (preferably only from the CLI documentation).

**Comment by WebFreak001** [comment]
moving into #353
