### ISSUE TITLE
dub's support for source libraries where the package root is the repository root is incomplete?

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#948]
cf: https://github.com/CyberShadow/Digger/issues/38#issuecomment-250526099
this is blocking Digger from being included in dub repository

**Comment by s-ludwig** [comment]
Hm, they should work correctly since 0.9.25. The corresponding issue is #502.

**Comment by CyberShadow** [comment]
Sorry for being so vague Sönke :) I remember running into an unexpected problem when I tried setting it up a while ago but the details escape me. Naturally I wouldn't file a bug without collecting the specifics, this has been on my backlog for a while.

Anyway, I can give it another go now if you can transfer ownership of http://code.dlang.org/packages/ae to me.

**Comment by s-ludwig** [comment]
Before the transfer, can you pull @Paxa's current version to some branch in your original repository, as well as the v1.0.0 and v1.0.1 tags? Otherwise this would likely break some dependent code.

**Comment by CyberShadow** [comment]
ae is definitely not at v1.0.0 (as far as SemVer is concerned) :/

I doubt there is going to be any code breakage, because that version doesn't compile with recent DMD versions any more (besides also that that fork is unofficial and unsupported).

**Comment by CyberShadow** [comment]
Pushed the branches, though.

**Comment by s-ludwig** [comment]
Fair enough, if it doesn't compile with current compiler versions. I've had a look at the downloads and the meta data has been downloaded 15 times in September (only counting downloads using the DUB CLI), so at least someone attempted to use it. But there are no public packages using it, so the impact should be small. I'll make the switch!

**Comment by s-ludwig** [comment]
Okay, done now. You'll still have to change the GitHub repository from the package management page.

**Comment by CyberShadow** [comment]
Thanks! Everything seems to work now. I don't remember what problems I had run into (or how I even concluded that they were there since I had no control over the ae repository), but they're evidently gone now.

http://code.dlang.org/packages/digger

I guess this issue can be closed.
