### ISSUE TITLE
`dub test` Mysteriously stopped passing `-unittest` to compiler

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#950]
This is really weird as I know it was working before with the exact same dub binary on the same project. But it just..._stopped_ passing "-unittest" to the compiler and now I can't run my unittests...

``` console
$ git clone https://github.com/Abscissa/SDLang-D.git check-dub-test
$ cd check-dub-test
$ dub test --verbose 2>/dev/null | grep -- -unittest
Running ./bin/sdlang-unittest
$
```

**Comment by Abscissa** [comment]
I've just pushed a change to my project that works around the issue by adding a couple `buildOptions "unittests"` to dub.sdl, but you can still recreate the problem by just deleting those lines right after cloning.

**Comment by MaksimZh** [comment]
Does your third command show any compile commands without grep?
If I see it right, they are sent to stderr:
https://github.com/dlang/dub/blob/3efb6657c4f5d4df3e4dac31f59437b214fa9204/source/dub/compilers/dmd.d#L203
https://github.com/dlang/dub/blob/44be25f45ac0a8338172722408bc02e28e8c3326/source/dub/internal/vibecompat/core/log.d#L77

**Comment by Abscissa** [comment]
>Does your third command show any compile commands without grep?

Yes, all expected comile commands are shown and run. They're just missing the -unittest flag.

**Comment by WebFreak001** [comment]
this may have happened due to custom unittest configurations, which now work however. Feel free to reopen with reproduction test case if this issue persists.
