### ISSUE TITLE
avoid unnecessary network requests

### ISSUE THREAD

**Issue by p0nce** [dlang/dub#955]
I very often use DUB in poor networks (sometimes 50 kbps/secs) with sometimes 80% packet loss, and I wish DUB would not check the network for everything. This often means 30 secs of lost time or whatever is the network timeout.

Literally the only times when I want to check the network are when using `dub upgrade`. I wish `--skip-registry=all` was the default because it make me lose lots of time.

**Comment by MartinNowak** [comment]
The only thing we don't cache is the branch dependencies, but there are still some around and used.
What project has this problem.

But in general I agree that those "new version for X" messages aren't worth hitting the server.

**Comment by p0nce** [comment]
For example, today I work from a place with 25% packet loss, for a project like :
https://github.com/AuburnSounds/dplug/tree/master/examples/distort

The command:
`dub generate visuald`

takes minutes to fail. I wish it would fail faster so I can type `dub generate --skip-registry=all visuald` earlier.

**Comment by wilzbach** [comment]
So last year the regular upgrade check was removed: https://github.com/dlang/dub/pull/1509

Does this fix your problem or are there other commands which still triggered unwanted requests?

**Comment by Geod24** [comment]
Ping @p0nce

**Comment by p0nce** [comment]
I haven't seen this problem for a while yes. Thank you for the continuous effort behind DUB !
