### ISSUE TITLE
please provide stacktraces on errors

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#957]
eg, got this:

Digit expected at beginning of number

impossible to know what this refers to without grepping the code.
Simply providing stacktrace upon throwing exceptions would go a long way.
(eg, the hack of `--export-dynamic` helps with showing meaningful stacktraces, unless you have a better way)

**Comment by MartinNowak** [comment]
Proper error handling in the parser is the way to go.

**Comment by timotheecour** [comment]
> Proper error handling in the parser is the way to go.

@MartinNowak  @s-ludwig 
Meh. The fix in https://github.com/dlang/dub/commit/fc8d314b3468c22ac126d85a519b120da4614a31 also makes the code more bloated. Simply having stacktraces (and when necessary just print the relevant runtime values) is a general and economic fix that should provide enough context when error happens, without making the code bloated with noisy error handling (a la `go`)
