### ISSUE TITLE
Do something useful when "building" targetType none packages

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#97]
Either an informative error message should appear, or, when sub packages exist, DUB could build all sub packages instead for example See also #87.

**Comment by LightBender** [comment]
*bump* I know it's a low priority but it would be very helpful when working on large scale projects with many components and dependencies.

**Comment by SimonN** [comment]
_bump_ -- I'd love to build two target binaries.

Or are there idiomatic solutions, besides running dub twice e.g. from a script/makefile?

**Comment by s-ludwig** [comment]
Fixed by #1364
