### ISSUE TITLE
dub --cache should be able to take a path

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#980]
sometimes neither of the 3 options currently available are good enough.

~~Workaround: cd to the directory you want to use as a cache, use `--cache=local` and `--root=xxxx` to point dub to the right place.~~ That doesn't work, as the cache also seems to be moved by `root`

**Comment by WebFreak001** [comment]
you can rely on the regular cache and use the new DUB_HOME or DPATH environment variable to control where the cache is put now.
