### ISSUE TITLE
Incorrect platform chosen

### ISSUE THREAD

**Issue by baruch** [dlang/dub#984]
I tried to create a project based on dfuse on Linux. The empty project build will try to build with the OSX library which obviously fails because the library is not available. When I reordered the platforms section it built the first one which is Linux, previously the first one was osx.

```
        "configurations": [
                {
                        "platforms": [
                                "linux"
                        ],
                        "name": "dfuse",
                        "targetType": "library",
                        "libs": [
                                "fuse"
                        ]
                },
                {
                        "platforms": [
                                "osx"
                        ],
                        "name": "dfuse",
                        "targetType": "library",
                        "libs": [
                                "osxfuse_i32"
                        ]
                }       ],
```

In the form above it works, when the order is exchanged (as it is in the original dfuse repo) the build fails.

**Comment by s-ludwig** [comment]
The problem is that both configurations have the same name and one of them will be dropped. This should result in an error message, but currently doesn't.

**Comment by baruch** [comment]
Thanks, that seems to work now.
