### ISSUE TITLE
Avoid special-casing POSIX in copyFile

### ISSUE THREAD

**Issue by WebDrake** [dlang/dub#992]
The `copyFile` function in `dub.internal.vibecompat.core.file` uses a `version (Posix)` block to special-case the preservation of file permissions:
https://github.com/dlang/dub/blob/v1.0.0/source/dub/internal/vibecompat/core/file.d#L118-L129

However, this ignores the `preserve` parameter of `std.file.copy`:
https://dlang.org/phobos/std_file.html#.copy

Is there a good reason for this special-casing and avoiding using the `preserve` parameter, or is it an oversight?  If the latter, I would suggest just setting the `preserve` parameter to always preserve permissions (regardless of platform).

**Comment by WebDrake** [comment]
I should declare a vested interest here: I'm trying to create a snap package of dub, and the `chown` call on L126 conflicts with snap-package containerization.  So it would be great if that was avoidable.

`std.file.copy` uses a call to `fchmod` but no `chown` call.

**Comment by s-ludwig** [comment]
Is see no places where preserving ownership would be critical, switching to use the preserve parameter (which I *think*  didn't exist back when this code was introduced in DUB) should be safe.

**Comment by WebDrake** [comment]
Cool, thanks.  I'll submit a PR sometime this week; before I do, I would like to verify that it really does solve the containment issue I encountered when trying to create a snap package, and that it doesn't create any other issues (e.g. wrong user for the built binaries).

Assuming all goes OK, would it be possible to have a v1.0.1 release with the fix in?

**Comment by s-ludwig** [comment]
v1.1.1 actually, but it should be small enough to put it in a patch release. I'll add it to the milestone.

**Comment by WebDrake** [comment]
Great, thank you very much.  I'll follow up when I've confirmed the change solves my own issues.

**Comment by s-ludwig** [comment]
Fixed by #994.
