### ISSUE TITLE
Optional dependencies are sticky and that is bad

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#997]
It introduces a strange "action at a distance" effect.

E.g.

A optionally depends on B
C depends on A only
D depends on A and B

Imagine C and D are entirely unrelated projects\*. If you build C first, it will not include B. If you build D first and then build C, *C will include and depend on B*.

This is a pretty crazy situation. I suggest it is a symptom of using by-default auto-generated files (`dub.selections.json`) as also user-customisable, which is fine for the "root" package but creates a nightmare when a package is part of 2 independent dependency chains.\*\*

\*perhaps even belonging to different users if A is system installed!

\*\* I think the fundamental difficulty is that you can't tell the difference between user settings that must be obeyed and auto-generated ones that could need to be different depending on all sorts of other things.

**Comment by John-Colvin** [comment]
I came up against this because I have optional dependencies that I want to *not* be included if they're not required by another package in the dependency graph. Unfortunately, because of the stickiness, any build that *does* require that dependency means all subsequent builds also include it.

**Comment by John-Colvin** [comment]
A workaround is to add `rm -f dub.selections.json` as a post-build command, but something cleverer is needed if you are already actually using `dub.selections.json` to store manual specifications of branch etc.

**Comment by s-ludwig** [comment]
Perhaps I'm misunderstanding something, but dub.selections.json only has an effect for the root package. This means that building D first will generally not change the fact that building C alone won't include B.

There is a big "however", though: All sub packages currently share the same dub.selections.json file with their base package, which violates the principle that they should generally behave like individual packages. Is it possible that this is what you stumbled over?

**Comment by John-Colvin** [comment]
Hmm, yes, it seems like I was mistaken. Perhaps it was the sub-packages that were causing the problem.
