### ISSUE TITLE
postBuildCommands are executed multiple times and from wrong path

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#998]
A depends on B & C, B depends on C. C defines a postBuildCommands entry.

What happens now if you build A:

The postBuildCommands are run once for building C, once for building B and then twice when building A. All 4 times they are run from the current working directory (regardless of which package is being build or --root=).

What I would expect to happen when building A:

The postBuildCommands are run once when building C, from the package directory of C.

workaround for the wrong path: use $PACKAGE_DIR to get/refer to the right place

**Comment by Geod24** [comment]
Tested with master, works.

Here are the 3 `dub.json` files I used:
```json
{
    "name": "issue998",
    "postBuildCommands": [ "echo \"I am package postBuildCommand: `pwd`\"" ],
    "dependencies": {
        "depa": { "path": "./depa" },
	"depb": { "path": "./depb" }
    }
}
{
    "name": "depa",
    "postBuildCommands": [ "echo \"I am depa postBuildCommand: `pwd`\"" ]
}
{
    "name": "depb",
    "dependencies": { "depa": { "path": "../depa" } },
    "postBuildCommands": [ "echo \"I am depb postBuildCommand: `pwd`\"" ]
}
```
You can infer the directory structure. Also had to move the `app.d` file to `lib.d` so that library configuration works.

Result:
```console
Performing "debug" build using dmd for x86_64.
depa ~master: building configuration "library"...
Running post-build commands...
I am depa postBuildCommand: /Users/geod24/projects/aports/testing/ldc/issue998/depa
depb ~master: building configuration "library"...
Running post-build commands...
I am depb postBuildCommand: /Users/geod24/projects/aports/testing/ldc/issue998/depb
issue998 ~master: building configuration "application"...
Linking...
Running post-build commands...
I am package postBuildCommand: /Users/geod24/projects/aports/testing/ldc/issue998
```
